-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY neurondec_boom IS
PORT(
  reset	: IN STD_LOGIC;
  clk	: IN STD_LOGIC;
  c_neuron_dec	: IN STD_LOGIC;
  out_neuron_index	: OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
  out_neuron_reset	: OUT STD_LOGIC
);
END neurondec_boom;

ARCHITECTURE RTL OF neurondec_boom IS
  SIGNAL rtlalc_4	: STD_LOGIC;
  SIGNAL rtlalc_3	: STD_LOGIC_VECTOR(2 DOWNTO 1);
  SIGNAL rtlalc_2	: STD_LOGIC;
  SIGNAL rtlalc_1	: STD_LOGIC;
  SIGNAL count	: STD_LOGIC_VECTOR(4 DOWNTO 0);
  SIGNAL aux0	: STD_LOGIC;
  SIGNAL aux1	: STD_LOGIC;
  SIGNAL aux2	: STD_LOGIC;
  SIGNAL aux3	: STD_LOGIC;
  SIGNAL aux5	: STD_LOGIC;
  SIGNAL aux6	: STD_LOGIC;
  SIGNAL aux8	: STD_LOGIC;
BEGIN
  out_neuron_index(3) <= rtlalc_2;
  out_neuron_index(2) <= rtlalc_3(2);
  out_neuron_index(1) <= rtlalc_3(1);
  out_neuron_index(0) <= rtlalc_4;
  out_neuron_reset <= rtlalc_1;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (((aux0 AND c_neuron_dec) OR reset) = '1')
    THEN rtlalc_4 <= '1';
    ELSIF ((NOT(aux0) AND NOT(reset)) = '1')
    THEN rtlalc_4 <= '0';
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (reset = '1')
    THEN rtlalc_3(2) <= '0';
    ELSIF ((c_neuron_dec AND NOT(reset)) = '1')
    THEN rtlalc_3(2) <= count(2);
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF ((c_neuron_dec AND (NOT(reset) AND aux2)) = '1')
    THEN rtlalc_3(1) <= '1';
    ELSIF ((reset OR NOT(aux2)) = '1')
    THEN rtlalc_3(1) <= '0';
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (((c_neuron_dec AND aux1) OR reset) = '1')
    THEN rtlalc_2 <= '1';
    ELSIF ((NOT(aux1) AND NOT(reset)) = '1')
    THEN rtlalc_2 <= '0';
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF ((aux5 AND (NOT(count(4)) AND aux8)) = '1')
    THEN rtlalc_1 <= '1';
    ELSIF ((NOT((aux5 AND (NOT(count(4)) AND aux8))) AND (c_neuron_dec AND NOT(reset))) =
 '1')
    THEN rtlalc_1 <= '0';
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (((aux5 AND NOT(aux6)) OR reset) = '1')
    THEN count(4) <= '0';
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (reset = '1')
    THEN count(3) <= '1';
    ELSIF ((NOT(reset) AND (NOT(count(2)) AND NOT(aux3))) = '1')
    THEN count(3) <= NOT(count(3));
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (((count(3) OR count(4)) AND (NOT(aux2) AND aux8)) = '1')
    THEN count(2) <= '1';
    ELSIF ((NOT(aux3 AND NOT(reset)) AND (NOT(count(3) OR count(4)) OR (aux2 OR NOT(aux8)
))) = '1')
    THEN count(2) <= '0';
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF ((NOT((aux1 OR (count(4) OR aux6))) OR reset) = '1')
    THEN count(1) <= '0';
    ELSIF (((aux1 OR (count(4) OR aux6)) AND (NOT(reset) AND NOT(aux0))) = '1')
    THEN count(1) <= NOT(count(1));
    END IF;
    END IF;
  END PROCESS;
  PROCESS ( clk )
  BEGIN
    IF  ((clk = '1') AND clk'EVENT)
    THEN 
    IF (reset = '1')
    THEN count(0) <= '1';
    ELSIF ((c_neuron_dec AND NOT(reset)) = '1')
    THEN count(0) <= NOT(count(0));
    END IF;
    END IF;
  END PROCESS;
  aux0 <= (NOT(c_neuron_dec) OR count(0));
  aux1 <= (count(3) OR NOT(c_neuron_dec));
  aux2 <= NOT((NOT(count(1)) AND c_neuron_dec));
  aux3 <= (aux2 OR count(0));
  aux5 <= NOT(((count(3) OR count(1)) OR NOT(c_neuron_dec)));
  aux6 <= (count(0) OR count(2));
  aux8 <= (NOT(count(0)) AND (NOT(reset) AND NOT(count(2))));
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_neurondec_boom of neurondec_boom is
  for RTL
  end for;
end CFG_neurondec_boom;
