-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY multiplier_final IS
PORT(
  ab0	: INOUT STD_LOGIC_VECTOR(7 DOWNTO 0);
  ab1	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
  ab2	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
  c2	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
  p1	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
  p2	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
  s	: OUT STD_LOGIC_VECTOR(10 DOWNTO 0);
  b	: IN STD_LOGIC_VECTOR(2 DOWNTO 0);
  a	: IN STD_LOGIC_VECTOR(7 DOWNTO 0)
);
END multiplier_final;

ARCHITECTURE RTL OF multiplier_final IS
  COMPONENT a2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT buf_x2
  PORT(
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

BEGIN
  ab0_7_ins : a2_x2
  PORT MAP (
    i0 => b(0),
    i1 => a(7),
    q => ab0(7)
  );
  ab0_6_ins : a2_x2
  PORT MAP (
    i0 => b(0),
    i1 => a(6),
    q => ab0(6)
  );
  ab0_5_ins : a2_x2
  PORT MAP (
    i0 => b(0),
    i1 => a(5),
    q => ab0(5)
  );
  ab0_4_ins : a2_x2
  PORT MAP (
    i0 => b(0),
    i1 => a(4),
    q => ab0(4)
  );
  ab0_3_ins : a2_x2
  PORT MAP (
    i0 => b(0),
    i1 => a(3),
    q => ab0(3)
  );
  ab0_2_ins : a2_x2
  PORT MAP (
    i0 => b(0),
    i1 => a(2),
    q => ab0(2)
  );
  ab0_1_ins : a2_x2
  PORT MAP (
    i0 => a(1),
    i1 => b(0),
    q => ab0(1)
  );
  ab0_0_ins : a2_x2
  PORT MAP (
    i0 => a(0),
    i1 => b(0),
    q => ab0(0)
  );
  ab1_7_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(7),
    q => ab1(7)
  );
  ab1_6_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(6),
    q => ab1(6)
  );
  ab1_5_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(5),
    q => ab1(5)
  );
  ab1_4_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(4),
    q => ab1(4)
  );
  ab1_3_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(3),
    q => ab1(3)
  );
  ab1_2_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(2),
    q => ab1(2)
  );
  ab1_1_ins : a2_x2
  PORT MAP (
    i0 => b(1),
    i1 => a(1),
    q => ab1(1)
  );
  ab1_0_ins : a2_x2
  PORT MAP (
    i0 => a(0),
    i1 => b(1),
    q => ab1(0)
  );
  ab2_7_ins : a2_x2
  PORT MAP (
    i0 => a(7),
    i1 => b(2),
    q => ab2(7)
  );
  ab2_6_ins : a2_x2
  PORT MAP (
    i0 => a(6),
    i1 => b(2),
    q => ab2(6)
  );
  ab2_5_ins : a2_x2
  PORT MAP (
    i0 => b(2),
    i1 => a(5),
    q => ab2(5)
  );
  ab2_4_ins : a2_x2
  PORT MAP (
    i0 => b(2),
    i1 => a(4),
    q => ab2(4)
  );
  ab2_3_ins : a2_x2
  PORT MAP (
    i0 => b(2),
    i1 => a(3),
    q => ab2(3)
  );
  ab2_2_ins : a2_x2
  PORT MAP (
    i0 => a(2),
    i1 => b(2),
    q => ab2(2)
  );
  ab2_1_ins : a2_x2
  PORT MAP (
    i0 => a(1),
    i1 => b(2),
    q => ab2(1)
  );
  ab2_0_ins : a2_x2
  PORT MAP (
    i0 => a(0),
    i1 => b(2),
    q => ab2(0)
  );
  s_10_ins : buf_x2
  PORT MAP (
    i => c2(7),
    q => s(10)
  );
  s_9_ins : buf_x2
  PORT MAP (
    i => p2(7),
    q => s(9)
  );
  s_8_ins : buf_x2
  PORT MAP (
    i => p2(6),
    q => s(8)
  );
  s_7_ins : buf_x2
  PORT MAP (
    i => p2(5),
    q => s(7)
  );
  s_6_ins : buf_x2
  PORT MAP (
    i => p2(4),
    q => s(6)
  );
  s_5_ins : buf_x2
  PORT MAP (
    i => p2(3),
    q => s(5)
  );
  s_4_ins : buf_x2
  PORT MAP (
    i => p2(2),
    q => s(4)
  );
  s_3_ins : buf_x2
  PORT MAP (
    i => p2(1),
    q => s(3)
  );
  s_2_ins : buf_x2
  PORT MAP (
    i => p2(0),
    q => s(2)
  );
  s_1_ins : buf_x2
  PORT MAP (
    i => p1(0),
    q => s(1)
  );
  s_0_ins : buf_x2
  PORT MAP (
    i => ab0(0),
    q => s(0)
  );
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_multiplier_final of multiplier_final is
  for RTL
    for all: a2_x2 use entity sxlib.a2_x2(vital); end for;
    for all: buf_x2 use entity sxlib.buf_x2(vital); end for;
  end for;
end CFG_multiplier_final;
