-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY neuronreg_boog IS
PORT(
  clk	: IN STD_LOGIC;
  reset	: IN STD_LOGIC;
  c_reset_reg	: IN STD_LOGIC;
  c_nreg	: IN STD_LOGIC;
  in_nreg_val	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
  out_nreg_val	: OUT STD_LOGIC_VECTOR(20 DOWNTO 0)
);
END neuronreg_boog;

ARCHITECTURE RTL OF neuronreg_boog IS
  SIGNAL not_in_nreg_val	: STD_LOGIC_VECTOR(6 DOWNTO 6);
  SIGNAL not_reg_nreg	: STD_LOGIC_VECTOR(19 DOWNTO 0);
  SIGNAL not_rtlalc_1	: STD_LOGIC_VECTOR(18 DOWNTO 5);
  SIGNAL not_rtlcarry_0	: STD_LOGIC_VECTOR(19 DOWNTO 2);
  SIGNAL reg_nreg	: STD_LOGIC_VECTOR(20 DOWNTO 0);
  SIGNAL rtlalc_1	: STD_LOGIC_VECTOR(20 DOWNTO 0);
  SIGNAL rtlcarry_0	: STD_LOGIC_VECTOR(12 DOWNTO 1);
  SIGNAL xr2_x1_sig	: STD_LOGIC;
  SIGNAL xr2_x1_2_sig	: STD_LOGIC;
  SIGNAL on12_x1_sig	: STD_LOGIC;
  SIGNAL on12_x1_9_sig	: STD_LOGIC;
  SIGNAL on12_x1_8_sig	: STD_LOGIC;
  SIGNAL on12_x1_7_sig	: STD_LOGIC;
  SIGNAL on12_x1_6_sig	: STD_LOGIC;
  SIGNAL on12_x1_5_sig	: STD_LOGIC;
  SIGNAL on12_x1_4_sig	: STD_LOGIC;
  SIGNAL on12_x1_3_sig	: STD_LOGIC;
  SIGNAL on12_x1_2_sig	: STD_LOGIC;
  SIGNAL on12_x1_16_sig	: STD_LOGIC;
  SIGNAL on12_x1_15_sig	: STD_LOGIC;
  SIGNAL on12_x1_14_sig	: STD_LOGIC;
  SIGNAL on12_x1_13_sig	: STD_LOGIC;
  SIGNAL on12_x1_12_sig	: STD_LOGIC;
  SIGNAL on12_x1_11_sig	: STD_LOGIC;
  SIGNAL on12_x1_10_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_sig	: STD_LOGIC;
  SIGNAL oa2a22_x2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_6_sig	: STD_LOGIC;
  SIGNAL oa22_x2_5_sig	: STD_LOGIC;
  SIGNAL oa22_x2_4_sig	: STD_LOGIC;
  SIGNAL oa22_x2_3_sig	: STD_LOGIC;
  SIGNAL oa22_x2_2_sig	: STD_LOGIC;
  SIGNAL o4_x2_sig	: STD_LOGIC;
  SIGNAL o4_x2_6_sig	: STD_LOGIC;
  SIGNAL o4_x2_5_sig	: STD_LOGIC;
  SIGNAL o4_x2_4_sig	: STD_LOGIC;
  SIGNAL o4_x2_3_sig	: STD_LOGIC;
  SIGNAL o4_x2_2_sig	: STD_LOGIC;
  SIGNAL o3_x2_sig	: STD_LOGIC;
  SIGNAL o3_x2_9_sig	: STD_LOGIC;
  SIGNAL o3_x2_8_sig	: STD_LOGIC;
  SIGNAL o3_x2_7_sig	: STD_LOGIC;
  SIGNAL o3_x2_6_sig	: STD_LOGIC;
  SIGNAL o3_x2_5_sig	: STD_LOGIC;
  SIGNAL o3_x2_4_sig	: STD_LOGIC;
  SIGNAL o3_x2_3_sig	: STD_LOGIC;
  SIGNAL o3_x2_2_sig	: STD_LOGIC;
  SIGNAL o3_x2_17_sig	: STD_LOGIC;
  SIGNAL o3_x2_16_sig	: STD_LOGIC;
  SIGNAL o3_x2_15_sig	: STD_LOGIC;
  SIGNAL o3_x2_14_sig	: STD_LOGIC;
  SIGNAL o3_x2_13_sig	: STD_LOGIC;
  SIGNAL o3_x2_12_sig	: STD_LOGIC;
  SIGNAL o3_x2_11_sig	: STD_LOGIC;
  SIGNAL o3_x2_10_sig	: STD_LOGIC;
  SIGNAL o2_x2_sig	: STD_LOGIC;
  SIGNAL o2_x2_9_sig	: STD_LOGIC;
  SIGNAL o2_x2_8_sig	: STD_LOGIC;
  SIGNAL o2_x2_7_sig	: STD_LOGIC;
  SIGNAL o2_x2_6_sig	: STD_LOGIC;
  SIGNAL o2_x2_5_sig	: STD_LOGIC;
  SIGNAL o2_x2_4_sig	: STD_LOGIC;
  SIGNAL o2_x2_3_sig	: STD_LOGIC;
  SIGNAL o2_x2_2_sig	: STD_LOGIC;
  SIGNAL o2_x2_13_sig	: STD_LOGIC;
  SIGNAL o2_x2_12_sig	: STD_LOGIC;
  SIGNAL o2_x2_11_sig	: STD_LOGIC;
  SIGNAL o2_x2_10_sig	: STD_LOGIC;
  SIGNAL not_reset	: STD_LOGIC;
  SIGNAL not_c_reset_reg	: STD_LOGIC;
  SIGNAL not_c_nreg	: STD_LOGIC;
  SIGNAL not_aux9	: STD_LOGIC;
  SIGNAL not_aux7	: STD_LOGIC;
  SIGNAL not_aux5	: STD_LOGIC;
  SIGNAL not_aux45	: STD_LOGIC;
  SIGNAL not_aux44	: STD_LOGIC;
  SIGNAL not_aux43	: STD_LOGIC;
  SIGNAL not_aux4	: STD_LOGIC;
  SIGNAL not_aux38	: STD_LOGIC;
  SIGNAL not_aux36	: STD_LOGIC;
  SIGNAL not_aux35	: STD_LOGIC;
  SIGNAL not_aux31	: STD_LOGIC;
  SIGNAL not_aux3	: STD_LOGIC;
  SIGNAL not_aux26	: STD_LOGIC;
  SIGNAL not_aux24	: STD_LOGIC;
  SIGNAL not_aux2	: STD_LOGIC;
  SIGNAL not_aux17	: STD_LOGIC;
  SIGNAL not_aux13	: STD_LOGIC;
  SIGNAL not_aux12	: STD_LOGIC;
  SIGNAL not_aux11	: STD_LOGIC;
  SIGNAL not_aux10	: STD_LOGIC;
  SIGNAL not_aux1	: STD_LOGIC;
  SIGNAL not_aux0	: STD_LOGIC;
  SIGNAL noa22_x1_sig	: STD_LOGIC;
  SIGNAL no4_x1_sig	: STD_LOGIC;
  SIGNAL no4_x1_7_sig	: STD_LOGIC;
  SIGNAL no4_x1_6_sig	: STD_LOGIC;
  SIGNAL no4_x1_5_sig	: STD_LOGIC;
  SIGNAL no4_x1_4_sig	: STD_LOGIC;
  SIGNAL no4_x1_3_sig	: STD_LOGIC;
  SIGNAL no4_x1_2_sig	: STD_LOGIC;
  SIGNAL no3_x1_sig	: STD_LOGIC;
  SIGNAL no3_x1_9_sig	: STD_LOGIC;
  SIGNAL no3_x1_8_sig	: STD_LOGIC;
  SIGNAL no3_x1_7_sig	: STD_LOGIC;
  SIGNAL no3_x1_6_sig	: STD_LOGIC;
  SIGNAL no3_x1_5_sig	: STD_LOGIC;
  SIGNAL no3_x1_4_sig	: STD_LOGIC;
  SIGNAL no3_x1_3_sig	: STD_LOGIC;
  SIGNAL no3_x1_2_sig	: STD_LOGIC;
  SIGNAL no3_x1_13_sig	: STD_LOGIC;
  SIGNAL no3_x1_12_sig	: STD_LOGIC;
  SIGNAL no3_x1_11_sig	: STD_LOGIC;
  SIGNAL no3_x1_10_sig	: STD_LOGIC;
  SIGNAL no2_x1_sig	: STD_LOGIC;
  SIGNAL no2_x1_9_sig	: STD_LOGIC;
  SIGNAL no2_x1_8_sig	: STD_LOGIC;
  SIGNAL no2_x1_7_sig	: STD_LOGIC;
  SIGNAL no2_x1_6_sig	: STD_LOGIC;
  SIGNAL no2_x1_5_sig	: STD_LOGIC;
  SIGNAL no2_x1_4_sig	: STD_LOGIC;
  SIGNAL no2_x1_3_sig	: STD_LOGIC;
  SIGNAL no2_x1_2_sig	: STD_LOGIC;
  SIGNAL nao22_x1_sig	: STD_LOGIC;
  SIGNAL nao22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao22_x1_2_sig	: STD_LOGIC;
  SIGNAL na4_x1_sig	: STD_LOGIC;
  SIGNAL na4_x1_8_sig	: STD_LOGIC;
  SIGNAL na4_x1_7_sig	: STD_LOGIC;
  SIGNAL na4_x1_6_sig	: STD_LOGIC;
  SIGNAL na4_x1_5_sig	: STD_LOGIC;
  SIGNAL na4_x1_4_sig	: STD_LOGIC;
  SIGNAL na4_x1_3_sig	: STD_LOGIC;
  SIGNAL na4_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_sig	: STD_LOGIC;
  SIGNAL na3_x1_9_sig	: STD_LOGIC;
  SIGNAL na3_x1_8_sig	: STD_LOGIC;
  SIGNAL na3_x1_7_sig	: STD_LOGIC;
  SIGNAL na3_x1_6_sig	: STD_LOGIC;
  SIGNAL na3_x1_5_sig	: STD_LOGIC;
  SIGNAL na3_x1_4_sig	: STD_LOGIC;
  SIGNAL na3_x1_3_sig	: STD_LOGIC;
  SIGNAL na3_x1_30_sig	: STD_LOGIC;
  SIGNAL na3_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_29_sig	: STD_LOGIC;
  SIGNAL na3_x1_28_sig	: STD_LOGIC;
  SIGNAL na3_x1_27_sig	: STD_LOGIC;
  SIGNAL na3_x1_26_sig	: STD_LOGIC;
  SIGNAL na3_x1_25_sig	: STD_LOGIC;
  SIGNAL na3_x1_24_sig	: STD_LOGIC;
  SIGNAL na3_x1_23_sig	: STD_LOGIC;
  SIGNAL na3_x1_22_sig	: STD_LOGIC;
  SIGNAL na3_x1_21_sig	: STD_LOGIC;
  SIGNAL na3_x1_20_sig	: STD_LOGIC;
  SIGNAL na3_x1_19_sig	: STD_LOGIC;
  SIGNAL na3_x1_18_sig	: STD_LOGIC;
  SIGNAL na3_x1_17_sig	: STD_LOGIC;
  SIGNAL na3_x1_16_sig	: STD_LOGIC;
  SIGNAL na3_x1_15_sig	: STD_LOGIC;
  SIGNAL na3_x1_14_sig	: STD_LOGIC;
  SIGNAL na3_x1_13_sig	: STD_LOGIC;
  SIGNAL na3_x1_12_sig	: STD_LOGIC;
  SIGNAL na3_x1_11_sig	: STD_LOGIC;
  SIGNAL na3_x1_10_sig	: STD_LOGIC;
  SIGNAL na2_x1_sig	: STD_LOGIC;
  SIGNAL na2_x1_9_sig	: STD_LOGIC;
  SIGNAL na2_x1_8_sig	: STD_LOGIC;
  SIGNAL na2_x1_7_sig	: STD_LOGIC;
  SIGNAL na2_x1_6_sig	: STD_LOGIC;
  SIGNAL na2_x1_5_sig	: STD_LOGIC;
  SIGNAL na2_x1_4_sig	: STD_LOGIC;
  SIGNAL na2_x1_3_sig	: STD_LOGIC;
  SIGNAL na2_x1_2_sig	: STD_LOGIC;
  SIGNAL na2_x1_14_sig	: STD_LOGIC;
  SIGNAL na2_x1_13_sig	: STD_LOGIC;
  SIGNAL na2_x1_12_sig	: STD_LOGIC;
  SIGNAL na2_x1_11_sig	: STD_LOGIC;
  SIGNAL na2_x1_10_sig	: STD_LOGIC;
  SIGNAL inv_x2_sig	: STD_LOGIC;
  SIGNAL inv_x2_9_sig	: STD_LOGIC;
  SIGNAL inv_x2_8_sig	: STD_LOGIC;
  SIGNAL inv_x2_7_sig	: STD_LOGIC;
  SIGNAL inv_x2_6_sig	: STD_LOGIC;
  SIGNAL inv_x2_5_sig	: STD_LOGIC;
  SIGNAL inv_x2_4_sig	: STD_LOGIC;
  SIGNAL inv_x2_3_sig	: STD_LOGIC;
  SIGNAL inv_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_14_sig	: STD_LOGIC;
  SIGNAL inv_x2_13_sig	: STD_LOGIC;
  SIGNAL inv_x2_12_sig	: STD_LOGIC;
  SIGNAL inv_x2_11_sig	: STD_LOGIC;
  SIGNAL inv_x2_10_sig	: STD_LOGIC;
  SIGNAL aux6	: STD_LOGIC;
  SIGNAL aux42	: STD_LOGIC;
  SIGNAL aux41	: STD_LOGIC;
  SIGNAL aux37	: STD_LOGIC;
  SIGNAL aux34	: STD_LOGIC;
  SIGNAL aux33	: STD_LOGIC;
  SIGNAL aux32	: STD_LOGIC;
  SIGNAL aux30	: STD_LOGIC;
  SIGNAL aux29	: STD_LOGIC;
  SIGNAL aux28	: STD_LOGIC;
  SIGNAL aux27	: STD_LOGIC;
  SIGNAL aux21	: STD_LOGIC;
  SIGNAL aux0	: STD_LOGIC;
  SIGNAL ao2o22_x2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_7_sig	: STD_LOGIC;
  SIGNAL ao22_x2_6_sig	: STD_LOGIC;
  SIGNAL ao22_x2_5_sig	: STD_LOGIC;
  SIGNAL ao22_x2_4_sig	: STD_LOGIC;
  SIGNAL ao22_x2_3_sig	: STD_LOGIC;
  SIGNAL ao22_x2_2_sig	: STD_LOGIC;
  SIGNAL an12_x1_sig	: STD_LOGIC;
  SIGNAL an12_x1_2_sig	: STD_LOGIC;
  SIGNAL a4_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_3_sig	: STD_LOGIC;
  SIGNAL a3_x2_2_sig	: STD_LOGIC;
  SIGNAL a2_x2_sig	: STD_LOGIC;
  SIGNAL a2_x2_9_sig	: STD_LOGIC;
  SIGNAL a2_x2_8_sig	: STD_LOGIC;
  SIGNAL a2_x2_7_sig	: STD_LOGIC;
  SIGNAL a2_x2_6_sig	: STD_LOGIC;
  SIGNAL a2_x2_5_sig	: STD_LOGIC;
  SIGNAL a2_x2_4_sig	: STD_LOGIC;
  SIGNAL a2_x2_3_sig	: STD_LOGIC;
  SIGNAL a2_x2_2_sig	: STD_LOGIC;
  SIGNAL a2_x2_17_sig	: STD_LOGIC;
  SIGNAL a2_x2_16_sig	: STD_LOGIC;
  SIGNAL a2_x2_15_sig	: STD_LOGIC;
  SIGNAL a2_x2_14_sig	: STD_LOGIC;
  SIGNAL a2_x2_13_sig	: STD_LOGIC;
  SIGNAL a2_x2_12_sig	: STD_LOGIC;
  SIGNAL a2_x2_11_sig	: STD_LOGIC;
  SIGNAL a2_x2_10_sig	: STD_LOGIC;

  COMPONENT buf_x2
  PORT(
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT sff1_x4
  PORT(
  ck	: IN STD_LOGIC;
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT on12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT an12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT inv_x2
  PORT(
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT sff2_x4
  PORT(
  ck	: IN STD_LOGIC;
  cmd	: IN STD_LOGIC;
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao2o22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT xr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2ao222_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2a22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao2o22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nxr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa2ao222_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

BEGIN
  out_nreg_val_20_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(20),
    q => out_nreg_val(20)
  );
  out_nreg_val_19_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(19),
    q => out_nreg_val(19)
  );
  out_nreg_val_18_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(18),
    q => out_nreg_val(18)
  );
  out_nreg_val_17_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(17),
    q => out_nreg_val(17)
  );
  out_nreg_val_16_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(16),
    q => out_nreg_val(16)
  );
  out_nreg_val_15_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(15),
    q => out_nreg_val(15)
  );
  out_nreg_val_14_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(14),
    q => out_nreg_val(14)
  );
  out_nreg_val_13_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(13),
    q => out_nreg_val(13)
  );
  out_nreg_val_12_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(12),
    q => out_nreg_val(12)
  );
  out_nreg_val_11_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(11),
    q => out_nreg_val(11)
  );
  out_nreg_val_10_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(10),
    q => out_nreg_val(10)
  );
  out_nreg_val_9_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(9),
    q => out_nreg_val(9)
  );
  out_nreg_val_8_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(8),
    q => out_nreg_val(8)
  );
  out_nreg_val_7_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(7),
    q => out_nreg_val(7)
  );
  out_nreg_val_6_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(6),
    q => out_nreg_val(6)
  );
  out_nreg_val_5_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(5),
    q => out_nreg_val(5)
  );
  out_nreg_val_4_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(4),
    q => out_nreg_val(4)
  );
  out_nreg_val_3_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(3),
    q => out_nreg_val(3)
  );
  out_nreg_val_2_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(2),
    q => out_nreg_val(2)
  );
  out_nreg_val_1_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(1),
    q => out_nreg_val(1)
  );
  out_nreg_val_0_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(0),
    q => out_nreg_val(0)
  );
  rtlalc_1_20_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_30_sig,
    q => rtlalc_1(20)
  );
  na3_x1_30_ins : na3_x1
  PORT MAP (
    i0 => not_aux26,
    i1 => on12_x1_16_sig,
    i2 => nao22_x1_6_sig,
    nq => na3_x1_30_sig
  );
  on12_x1_16_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(20),
    i1 => not_aux1,
    q => on12_x1_16_sig
  );
  nao22_x1_6_ins : nao22_x1
  PORT MAP (
    i0 => not_reg_nreg(19),
    i1 => not_rtlcarry_0(19),
    i2 => a2_x2_17_sig,
    nq => nao22_x1_6_sig
  );
  a2_x2_17_ins : a2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => reg_nreg(20),
    q => a2_x2_17_sig
  );
  rtlalc_1_19_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_28_sig,
    q => rtlalc_1(19)
  );
  na3_x1_28_ins : na3_x1
  PORT MAP (
    i0 => on12_x1_15_sig,
    i1 => na3_x1_29_sig,
    i2 => na2_x1_14_sig,
    nq => na3_x1_28_sig
  );
  on12_x1_15_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(19),
    i1 => not_aux1,
    q => on12_x1_15_sig
  );
  na3_x1_29_ins : na3_x1
  PORT MAP (
    i0 => not_rtlcarry_0(19),
    i1 => reg_nreg(19),
    i2 => aux37,
    nq => na3_x1_29_sig
  );
  na2_x1_14_ins : na2_x1
  PORT MAP (
    i0 => not_reg_nreg(19),
    i1 => an12_x1_2_sig,
    nq => na2_x1_14_sig
  );
  an12_x1_2_ins : an12_x1
  PORT MAP (
    i0 => not_rtlcarry_0(19),
    i1 => aux37,
    q => an12_x1_2_sig
  );
  rtlalc_1_18_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_26_sig,
    q => rtlalc_1(18)
  );
  na3_x1_26_ins : na3_x1
  PORT MAP (
    i0 => o3_x2_17_sig,
    i1 => na3_x1_27_sig,
    i2 => o2_x2_13_sig,
    nq => na3_x1_26_sig
  );
  o3_x2_17_ins : o3_x2
  PORT MAP (
    i0 => not_aux44,
    i1 => not_aux36,
    i2 => not_rtlcarry_0(18),
    q => o3_x2_17_sig
  );
  na3_x1_27_ins : na3_x1
  PORT MAP (
    i0 => no2_x1_9_sig,
    i1 => not_rtlcarry_0(18),
    i2 => reg_nreg(18),
    nq => na3_x1_27_sig
  );
  no2_x1_9_ins : no2_x1
  PORT MAP (
    i0 => not_aux36,
    i1 => not_c_nreg,
    nq => no2_x1_9_sig
  );
  o2_x2_13_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => not_rtlalc_1(18),
    q => o2_x2_13_sig
  );
  rtlalc_1_17_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_24_sig,
    q => rtlalc_1(17)
  );
  na3_x1_24_ins : na3_x1
  PORT MAP (
    i0 => o3_x2_16_sig,
    i1 => na3_x1_25_sig,
    i2 => o2_x2_12_sig,
    nq => na3_x1_24_sig
  );
  o3_x2_16_ins : o3_x2
  PORT MAP (
    i0 => not_aux43,
    i1 => not_aux35,
    i2 => not_rtlcarry_0(17),
    q => o3_x2_16_sig
  );
  na3_x1_25_ins : na3_x1
  PORT MAP (
    i0 => no2_x1_8_sig,
    i1 => not_rtlcarry_0(17),
    i2 => reg_nreg(17),
    nq => na3_x1_25_sig
  );
  no2_x1_8_ins : no2_x1
  PORT MAP (
    i0 => not_aux35,
    i1 => not_c_nreg,
    nq => no2_x1_8_sig
  );
  o2_x2_12_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => not_rtlalc_1(17),
    q => o2_x2_12_sig
  );
  rtlalc_1_16_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_7_sig,
    q => rtlalc_1(16)
  );
  ao22_x2_7_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(16),
    i2 => na3_x1_23_sig,
    q => ao22_x2_7_sig
  );
  na3_x1_23_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_13_sig,
    i2 => o2_x2_11_sig,
    nq => na3_x1_23_sig
  );
  na2_x1_13_ins : na2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(16),
    i1 => reg_nreg(16),
    nq => na2_x1_13_sig
  );
  o2_x2_11_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(16),
    i1 => reg_nreg(16),
    q => o2_x2_11_sig
  );
  rtlalc_1_15_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => o3_x2_15_sig,
    q => rtlalc_1(15)
  );
  o3_x2_15_ins : o3_x2
  PORT MAP (
    i0 => aux21,
    i1 => an12_x1_sig,
    i2 => a3_x2_3_sig,
    q => o3_x2_15_sig
  );
  an12_x1_ins : an12_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(15),
    q => an12_x1_sig
  );
  a3_x2_3_ins : a3_x2
  PORT MAP (
    i0 => no3_x1_13_sig,
    i1 => not_rtlcarry_0(15),
    i2 => reg_nreg(15),
    q => a3_x2_3_sig
  );
  no3_x1_13_ins : no3_x1
  PORT MAP (
    i0 => reset,
    i1 => not_c_nreg,
    i2 => c_reset_reg,
    nq => no3_x1_13_sig
  );
  rtlalc_1_14_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_6_sig,
    q => rtlalc_1(14)
  );
  ao22_x2_6_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(14),
    i2 => na3_x1_22_sig,
    q => ao22_x2_6_sig
  );
  na3_x1_22_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_12_sig,
    i2 => o2_x2_10_sig,
    nq => na3_x1_22_sig
  );
  na2_x1_12_ins : na2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(14),
    i1 => reg_nreg(14),
    nq => na2_x1_12_sig
  );
  o2_x2_10_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(14),
    i1 => reg_nreg(14),
    q => o2_x2_10_sig
  );
  rtlalc_1_13_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_5_sig,
    q => rtlalc_1(13)
  );
  ao22_x2_5_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(13),
    i2 => na3_x1_21_sig,
    q => ao22_x2_5_sig
  );
  na3_x1_21_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_11_sig,
    i2 => o2_x2_9_sig,
    nq => na3_x1_21_sig
  );
  na2_x1_11_ins : na2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => reg_nreg(13),
    nq => na2_x1_11_sig
  );
  o2_x2_9_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => reg_nreg(13),
    q => o2_x2_9_sig
  );
  rtlalc_1_12_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_20_sig,
    q => rtlalc_1(12)
  );
  na3_x1_20_ins : na3_x1
  PORT MAP (
    i0 => not_aux17,
    i1 => on12_x1_14_sig,
    i2 => on12_x1_13_sig,
    nq => na3_x1_20_sig
  );
  on12_x1_14_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(12),
    i1 => not_aux1,
    q => on12_x1_14_sig
  );
  on12_x1_13_ins : on12_x1
  PORT MAP (
    i0 => a4_x2_sig,
    i1 => not_aux13,
    q => on12_x1_13_sig
  );
  a4_x2_ins : a4_x2
  PORT MAP (
    i0 => reg_nreg(12),
    i1 => not_reset,
    i2 => not_c_reset_reg,
    i3 => c_nreg,
    q => a4_x2_sig
  );
  rtlalc_1_11_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_4_sig,
    q => rtlalc_1(11)
  );
  ao22_x2_4_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(11),
    i2 => na3_x1_19_sig,
    q => ao22_x2_4_sig
  );
  na3_x1_19_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_10_sig,
    i2 => o2_x2_8_sig,
    nq => na3_x1_19_sig
  );
  na2_x1_10_ins : na2_x1
  PORT MAP (
    i0 => not_aux12,
    i1 => not_reg_nreg(11),
    nq => na2_x1_10_sig
  );
  o2_x2_8_ins : o2_x2
  PORT MAP (
    i0 => not_aux12,
    i1 => not_reg_nreg(11),
    q => o2_x2_8_sig
  );
  rtlalc_1_10_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_17_sig,
    q => rtlalc_1(10)
  );
  na3_x1_17_ins : na3_x1
  PORT MAP (
    i0 => on12_x1_12_sig,
    i1 => na3_x1_18_sig,
    i2 => o3_x2_14_sig,
    nq => na3_x1_17_sig
  );
  on12_x1_12_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(10),
    i1 => not_aux1,
    q => on12_x1_12_sig
  );
  na3_x1_18_ins : na3_x1
  PORT MAP (
    i0 => not_reg_nreg(10),
    i1 => not_aux11,
    i2 => aux34,
    nq => na3_x1_18_sig
  );
  o3_x2_14_ins : o3_x2
  PORT MAP (
    i0 => not_reg_nreg(10),
    i1 => not_aux11,
    i2 => inv_x2_14_sig,
    q => o3_x2_14_sig
  );
  inv_x2_14_ins : inv_x2
  PORT MAP (
    i => aux34,
    nq => inv_x2_14_sig
  );
  rtlalc_1_9_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_3_sig,
    q => rtlalc_1(9)
  );
  ao22_x2_3_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(9),
    i2 => na3_x1_16_sig,
    q => ao22_x2_3_sig
  );
  na3_x1_16_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_9_sig,
    i2 => o2_x2_7_sig,
    nq => na3_x1_16_sig
  );
  na2_x1_9_ins : na2_x1
  PORT MAP (
    i0 => not_aux10,
    i1 => not_reg_nreg(9),
    nq => na2_x1_9_sig
  );
  o2_x2_7_ins : o2_x2
  PORT MAP (
    i0 => not_aux10,
    i1 => not_reg_nreg(9),
    q => o2_x2_7_sig
  );
  rtlalc_1_8_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_6_sig,
    q => rtlalc_1(8)
  );
  oa22_x2_6_ins : oa22_x2
  PORT MAP (
    i0 => rtlalc_1(8),
    i1 => not_c_nreg,
    i2 => a3_x2_2_sig,
    q => oa22_x2_6_sig
  );
  a3_x2_2_ins : a3_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => na3_x1_15_sig,
    i2 => on12_x1_11_sig,
    q => a3_x2_2_sig
  );
  na3_x1_15_ins : na3_x1
  PORT MAP (
    i0 => not_reset,
    i1 => not_aux9,
    i2 => not_c_reset_reg,
    nq => na3_x1_15_sig
  );
  on12_x1_11_ins : on12_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => rtlalc_1(8),
    q => on12_x1_11_sig
  );
  rtlalc_1_7_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => o3_x2_13_sig,
    q => rtlalc_1(7)
  );
  o3_x2_13_ins : o3_x2
  PORT MAP (
    i0 => no2_x1_7_sig,
    i1 => a3_x2_sig,
    i2 => no4_x1_7_sig,
    q => o3_x2_13_sig
  );
  no2_x1_7_ins : no2_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => not_rtlalc_1(7),
    nq => no2_x1_7_sig
  );
  a3_x2_ins : a3_x2
  PORT MAP (
    i0 => aux42,
    i1 => not_aux7,
    i2 => aux33,
    q => a3_x2_sig
  );
  no4_x1_7_ins : no4_x1
  PORT MAP (
    i0 => not_reg_nreg(7),
    i1 => inv_x2_13_sig,
    i2 => not_aux7,
    i3 => not_c_nreg,
    nq => no4_x1_7_sig
  );
  inv_x2_13_ins : inv_x2
  PORT MAP (
    i => aux33,
    nq => inv_x2_13_sig
  );
  rtlalc_1_6_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => c_nreg,
    i0 => rtlalc_1(6),
    i1 => na2_x1_8_sig,
    q => rtlalc_1(6)
  );
  na2_x1_8_ins : na2_x1
  PORT MAP (
    i0 => na3_x1_14_sig,
    i1 => noa22_x1_sig,
    nq => na2_x1_8_sig
  );
  na3_x1_14_ins : na3_x1
  PORT MAP (
    i0 => not_in_nreg_val(6),
    i1 => not_aux31,
    i2 => aux32,
    nq => na3_x1_14_sig
  );
  noa22_x1_ins : noa22_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => rtlalc_1(6),
    i2 => no3_x1_12_sig,
    nq => noa22_x1_sig
  );
  no3_x1_12_ins : no3_x1
  PORT MAP (
    i0 => inv_x2_12_sig,
    i1 => not_aux31,
    i2 => not_in_nreg_val(6),
    nq => no3_x1_12_sig
  );
  inv_x2_12_ins : inv_x2
  PORT MAP (
    i => aux32,
    nq => inv_x2_12_sig
  );
  rtlalc_1_5_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_13_sig,
    q => rtlalc_1(5)
  );
  na3_x1_13_ins : na3_x1
  PORT MAP (
    i0 => o2_x2_6_sig,
    i1 => na4_x1_8_sig,
    i2 => o4_x2_6_sig,
    nq => na3_x1_13_sig
  );
  o2_x2_6_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => not_rtlalc_1(5),
    q => o2_x2_6_sig
  );
  na4_x1_8_ins : na4_x1
  PORT MAP (
    i0 => aux30,
    i1 => c_nreg,
    i2 => not_rtlcarry_0(5),
    i3 => aux29,
    nq => na4_x1_8_sig
  );
  o4_x2_6_ins : o4_x2
  PORT MAP (
    i0 => aux29,
    i1 => not_c_nreg,
    i2 => not_rtlcarry_0(5),
    i3 => inv_x2_11_sig,
    q => o4_x2_6_sig
  );
  inv_x2_11_ins : inv_x2
  PORT MAP (
    i => aux30,
    nq => inv_x2_11_sig
  );
  rtlalc_1_4_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_2_sig,
    q => rtlalc_1(4)
  );
  ao22_x2_2_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(4),
    i2 => na3_x1_12_sig,
    q => ao22_x2_2_sig
  );
  na3_x1_12_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_7_sig,
    i2 => o2_x2_5_sig,
    nq => na3_x1_12_sig
  );
  na2_x1_7_ins : na2_x1
  PORT MAP (
    i0 => not_aux5,
    i1 => not_reg_nreg(4),
    nq => na2_x1_7_sig
  );
  o2_x2_5_ins : o2_x2
  PORT MAP (
    i0 => not_aux5,
    i1 => not_reg_nreg(4),
    q => o2_x2_5_sig
  );
  rtlalc_1_3_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_10_sig,
    q => rtlalc_1(3)
  );
  na3_x1_10_ins : na3_x1
  PORT MAP (
    i0 => on12_x1_10_sig,
    i1 => na3_x1_11_sig,
    i2 => o3_x2_12_sig,
    nq => na3_x1_10_sig
  );
  on12_x1_10_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(3),
    i1 => not_aux1,
    q => on12_x1_10_sig
  );
  na3_x1_11_ins : na3_x1
  PORT MAP (
    i0 => not_reg_nreg(3),
    i1 => not_aux4,
    i2 => aux28,
    nq => na3_x1_11_sig
  );
  o3_x2_12_ins : o3_x2
  PORT MAP (
    i0 => not_reg_nreg(3),
    i1 => not_aux4,
    i2 => inv_x2_10_sig,
    q => o3_x2_12_sig
  );
  inv_x2_10_ins : inv_x2
  PORT MAP (
    i => aux28,
    nq => inv_x2_10_sig
  );
  rtlalc_1_2_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_8_sig,
    q => rtlalc_1(2)
  );
  na3_x1_8_ins : na3_x1
  PORT MAP (
    i0 => on12_x1_9_sig,
    i1 => na3_x1_9_sig,
    i2 => o3_x2_11_sig,
    nq => na3_x1_8_sig
  );
  on12_x1_9_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(2),
    i1 => not_aux1,
    q => on12_x1_9_sig
  );
  na3_x1_9_ins : na3_x1
  PORT MAP (
    i0 => not_reg_nreg(2),
    i1 => not_aux3,
    i2 => aux27,
    nq => na3_x1_9_sig
  );
  o3_x2_11_ins : o3_x2
  PORT MAP (
    i0 => not_reg_nreg(2),
    i1 => not_aux3,
    i2 => inv_x2_9_sig,
    q => o3_x2_11_sig
  );
  inv_x2_9_ins : inv_x2
  PORT MAP (
    i => aux27,
    nq => inv_x2_9_sig
  );
  rtlalc_1_1_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_sig,
    q => rtlalc_1(1)
  );
  ao22_x2_ins : ao22_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(1),
    i2 => na3_x1_7_sig,
    q => ao22_x2_sig
  );
  na3_x1_7_ins : na3_x1
  PORT MAP (
    i0 => not_aux1,
    i1 => na2_x1_6_sig,
    i2 => o2_x2_4_sig,
    nq => na3_x1_7_sig
  );
  na2_x1_6_ins : na2_x1
  PORT MAP (
    i0 => not_aux2,
    i1 => not_reg_nreg(1),
    nq => na2_x1_6_sig
  );
  o2_x2_4_ins : o2_x2
  PORT MAP (
    i0 => not_aux2,
    i1 => not_reg_nreg(1),
    q => o2_x2_4_sig
  );
  rtlalc_1_0_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao2o22_x2_sig,
    q => rtlalc_1(0)
  );
  ao2o22_x2_ins : ao2o22_x2
  PORT MAP (
    i0 => inv_x2_8_sig,
    i1 => xr2_x1_2_sig,
    i2 => not_aux1,
    i3 => rtlalc_1(0),
    q => ao2o22_x2_sig
  );
  inv_x2_8_ins : inv_x2
  PORT MAP (
    i => not_aux1,
    nq => inv_x2_8_sig
  );
  xr2_x1_2_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(0),
    i1 => in_nreg_val(0),
    q => xr2_x1_2_sig
  );
  reg_nreg_20_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_8_sig,
    q => reg_nreg(20)
  );
  on12_x1_8_ins : on12_x1
  PORT MAP (
    i0 => not_aux26,
    i1 => no3_x1_11_sig,
    q => on12_x1_8_sig
  );
  no3_x1_11_ins : no3_x1
  PORT MAP (
    i0 => inv_x2_7_sig,
    i1 => a2_x2_16_sig,
    i2 => not_aux0,
    nq => no3_x1_11_sig
  );
  inv_x2_7_ins : inv_x2
  PORT MAP (
    i => reg_nreg(20),
    nq => inv_x2_7_sig
  );
  a2_x2_16_ins : a2_x2
  PORT MAP (
    i0 => not_aux45,
    i1 => reg_nreg(19),
    q => a2_x2_16_sig
  );
  reg_nreg_19_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_5_sig,
    q => reg_nreg(19)
  );
  nao22_x1_5_ins : nao22_x1
  PORT MAP (
    i0 => reg_nreg(19),
    i1 => not_aux24,
    i2 => o3_x2_10_sig,
    nq => nao22_x1_5_sig
  );
  o3_x2_10_ins : o3_x2
  PORT MAP (
    i0 => not_aux45,
    i1 => not_aux0,
    i2 => not_reg_nreg(19),
    q => o3_x2_10_sig
  );
  reg_nreg_18_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_7_sig,
    q => reg_nreg(18)
  );
  on12_x1_7_ins : on12_x1
  PORT MAP (
    i0 => o4_x2_5_sig,
    i1 => no3_x1_10_sig,
    q => on12_x1_7_sig
  );
  o4_x2_5_ins : o4_x2
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => not_aux44,
    i3 => not_rtlcarry_0(18),
    q => o4_x2_5_sig
  );
  no3_x1_10_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(18),
    i1 => not_aux0,
    i2 => no2_x1_6_sig,
    nq => no3_x1_10_sig
  );
  no2_x1_6_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(18),
    i1 => not_c_nreg,
    nq => no2_x1_6_sig
  );
  reg_nreg_17_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_6_sig,
    q => reg_nreg(17)
  );
  on12_x1_6_ins : on12_x1
  PORT MAP (
    i0 => o4_x2_4_sig,
    i1 => no3_x1_9_sig,
    q => on12_x1_6_sig
  );
  o4_x2_4_ins : o4_x2
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => not_aux43,
    i3 => not_rtlcarry_0(17),
    q => o4_x2_4_sig
  );
  no3_x1_9_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(17),
    i1 => not_aux0,
    i2 => no2_x1_5_sig,
    nq => no3_x1_9_sig
  );
  no2_x1_5_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(17),
    i1 => not_c_nreg,
    nq => no2_x1_5_sig
  );
  reg_nreg_16_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_5_sig,
    q => reg_nreg(16)
  );
  on12_x1_5_ins : on12_x1
  PORT MAP (
    i0 => o3_x2_9_sig,
    i1 => no3_x1_8_sig,
    q => on12_x1_5_sig
  );
  o3_x2_9_ins : o3_x2
  PORT MAP (
    i0 => na3_x1_6_sig,
    i1 => not_rtlcarry_0(16),
    i2 => reg_nreg(16),
    q => o3_x2_9_sig
  );
  na3_x1_6_ins : na3_x1
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    nq => na3_x1_6_sig
  );
  no3_x1_8_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(16),
    i1 => not_aux0,
    i2 => no2_x1_4_sig,
    nq => no3_x1_8_sig
  );
  no2_x1_4_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(16),
    i1 => not_c_nreg,
    nq => no2_x1_4_sig
  );
  reg_nreg_15_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_4_sig,
    q => reg_nreg(15)
  );
  on12_x1_4_ins : on12_x1
  PORT MAP (
    i0 => o3_x2_8_sig,
    i1 => aux21,
    q => on12_x1_4_sig
  );
  o3_x2_8_ins : o3_x2
  PORT MAP (
    i0 => no2_x1_3_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(15),
    q => o3_x2_8_sig
  );
  no2_x1_3_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(15),
    i1 => not_c_nreg,
    nq => no2_x1_3_sig
  );
  reg_nreg_14_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_3_sig,
    q => reg_nreg(14)
  );
  on12_x1_3_ins : on12_x1
  PORT MAP (
    i0 => o3_x2_7_sig,
    i1 => no3_x1_7_sig,
    q => on12_x1_3_sig
  );
  o3_x2_7_ins : o3_x2
  PORT MAP (
    i0 => na3_x1_5_sig,
    i1 => not_rtlcarry_0(14),
    i2 => reg_nreg(14),
    q => o3_x2_7_sig
  );
  na3_x1_5_ins : na3_x1
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    nq => na3_x1_5_sig
  );
  no3_x1_7_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(14),
    i1 => not_aux0,
    i2 => no2_x1_2_sig,
    nq => no3_x1_7_sig
  );
  no2_x1_2_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(14),
    i1 => not_c_nreg,
    nq => no2_x1_2_sig
  );
  reg_nreg_13_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_4_sig,
    q => reg_nreg(13)
  );
  nao22_x1_4_ins : nao22_x1
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => na4_x1_7_sig,
    i2 => o3_x2_6_sig,
    nq => nao22_x1_4_sig
  );
  na4_x1_7_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => c_nreg,
    i3 => not_reg_nreg(13),
    nq => na4_x1_7_sig
  );
  o3_x2_6_ins : o3_x2
  PORT MAP (
    i0 => no2_x1_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(13),
    q => o3_x2_6_sig
  );
  no2_x1_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => not_c_nreg,
    nq => no2_x1_sig
  );
  reg_nreg_12_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_4_sig,
    q => reg_nreg(12)
  );
  na2_x1_4_ins : na2_x1
  PORT MAP (
    i0 => not_aux17,
    i1 => na3_x1_4_sig,
    nq => na2_x1_4_sig
  );
  na3_x1_4_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_5_sig,
    i1 => reg_nreg(12),
    i2 => aux0,
    nq => na3_x1_4_sig
  );
  na2_x1_5_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux13,
    nq => na2_x1_5_sig
  );
  reg_nreg_11_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_3_sig,
    q => reg_nreg(11)
  );
  nao22_x1_3_ins : nao22_x1
  PORT MAP (
    i0 => a2_x2_15_sig,
    i1 => o2_x2_3_sig,
    i2 => o3_x2_5_sig,
    nq => nao22_x1_3_sig
  );
  a2_x2_15_ins : a2_x2
  PORT MAP (
    i0 => na4_x1_6_sig,
    i1 => o4_x2_3_sig,
    q => a2_x2_15_sig
  );
  na4_x1_6_ins : na4_x1
  PORT MAP (
    i0 => not_reset,
    i1 => in_nreg_val(11),
    i2 => not_rtlcarry_0(11),
    i3 => not_c_reset_reg,
    nq => na4_x1_6_sig
  );
  o4_x2_3_ins : o4_x2
  PORT MAP (
    i0 => reset,
    i1 => in_nreg_val(11),
    i2 => c_reset_reg,
    i3 => not_rtlcarry_0(11),
    q => o4_x2_3_sig
  );
  o2_x2_3_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reg_nreg(11),
    q => o2_x2_3_sig
  );
  o3_x2_5_ins : o3_x2
  PORT MAP (
    i0 => a2_x2_14_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(11),
    q => o3_x2_5_sig
  );
  a2_x2_14_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux12,
    q => a2_x2_14_sig
  );
  reg_nreg_10_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_2_sig,
    q => reg_nreg(10)
  );
  nao22_x1_2_ins : nao22_x1
  PORT MAP (
    i0 => a2_x2_13_sig,
    i1 => o2_x2_2_sig,
    i2 => o3_x2_4_sig,
    nq => nao22_x1_2_sig
  );
  a2_x2_13_ins : a2_x2
  PORT MAP (
    i0 => na4_x1_5_sig,
    i1 => o4_x2_2_sig,
    q => a2_x2_13_sig
  );
  na4_x1_5_ins : na4_x1
  PORT MAP (
    i0 => not_reset,
    i1 => in_nreg_val(10),
    i2 => not_rtlcarry_0(10),
    i3 => not_c_reset_reg,
    nq => na4_x1_5_sig
  );
  o4_x2_2_ins : o4_x2
  PORT MAP (
    i0 => reset,
    i1 => in_nreg_val(10),
    i2 => c_reset_reg,
    i3 => not_rtlcarry_0(10),
    q => o4_x2_2_sig
  );
  o2_x2_2_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reg_nreg(10),
    q => o2_x2_2_sig
  );
  o3_x2_4_ins : o3_x2
  PORT MAP (
    i0 => a2_x2_12_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(10),
    q => o3_x2_4_sig
  );
  a2_x2_12_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux11,
    q => a2_x2_12_sig
  );
  reg_nreg_9_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_5_sig,
    q => reg_nreg(9)
  );
  oa22_x2_5_ins : oa22_x2
  PORT MAP (
    i0 => no4_x1_6_sig,
    i1 => not_aux10,
    i2 => no3_x1_6_sig,
    q => oa22_x2_5_sig
  );
  no4_x1_6_ins : no4_x1
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => reg_nreg(9),
    i3 => not_c_nreg,
    nq => no4_x1_6_sig
  );
  no3_x1_6_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(9),
    i1 => not_aux0,
    i2 => a2_x2_11_sig,
    nq => no3_x1_6_sig
  );
  a2_x2_11_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux10,
    q => a2_x2_11_sig
  );
  reg_nreg_8_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_4_sig,
    q => reg_nreg(8)
  );
  oa22_x2_4_ins : oa22_x2
  PORT MAP (
    i0 => reg_nreg(8),
    i1 => no3_x1_5_sig,
    i2 => no4_x1_5_sig,
    q => oa22_x2_4_sig
  );
  no3_x1_5_ins : no3_x1
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => c_nreg,
    nq => no3_x1_5_sig
  );
  no4_x1_5_ins : no4_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reset,
    i2 => not_aux9,
    i3 => c_reset_reg,
    nq => no4_x1_5_sig
  );
  reg_nreg_7_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_3_sig,
    q => reg_nreg(7)
  );
  na2_x1_3_ins : na2_x1
  PORT MAP (
    i0 => na4_x1_4_sig,
    i1 => o3_x2_3_sig,
    nq => na2_x1_3_sig
  );
  na4_x1_4_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => not_aux7,
    i3 => aux42,
    nq => na4_x1_4_sig
  );
  o3_x2_3_ins : o3_x2
  PORT MAP (
    i0 => a2_x2_10_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(7),
    q => o3_x2_3_sig
  );
  a2_x2_10_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux7,
    q => a2_x2_10_sig
  );
  reg_nreg_6_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_3_sig,
    q => reg_nreg(6)
  );
  oa22_x2_3_ins : oa22_x2
  PORT MAP (
    i0 => on12_x1_2_sig,
    i1 => c_nreg,
    i2 => no3_x1_4_sig,
    q => oa22_x2_3_sig
  );
  on12_x1_2_ins : on12_x1
  PORT MAP (
    i0 => na4_x1_3_sig,
    i1 => no4_x1_4_sig,
    q => on12_x1_2_sig
  );
  na4_x1_3_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => not_rtlcarry_0(6),
    i3 => aux6,
    nq => na4_x1_3_sig
  );
  no4_x1_4_ins : no4_x1
  PORT MAP (
    i0 => aux6,
    i1 => reset,
    i2 => not_rtlcarry_0(6),
    i3 => c_reset_reg,
    nq => no4_x1_4_sig
  );
  no3_x1_4_ins : no3_x1
  PORT MAP (
    i0 => inv_x2_6_sig,
    i1 => not_aux0,
    i2 => c_nreg,
    nq => no3_x1_4_sig
  );
  inv_x2_6_ins : inv_x2
  PORT MAP (
    i => reg_nreg(6),
    nq => inv_x2_6_sig
  );
  reg_nreg_5_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => in_nreg_val(5),
    i0 => oa2ao222_x2_sig,
    i1 => oa2a22_x2_sig,
    q => reg_nreg(5)
  );
  oa2ao222_x2_ins : oa2ao222_x2
  PORT MAP (
    i0 => rtlcarry_0(5),
    i1 => aux41,
    i2 => not_rtlcarry_0(5),
    i3 => not_c_nreg,
    i4 => inv_x2_5_sig,
    q => oa2ao222_x2_sig
  );
  inv_x2_5_ins : inv_x2
  PORT MAP (
    i => not_aux38,
    nq => inv_x2_5_sig
  );
  oa2a22_x2_ins : oa2a22_x2
  PORT MAP (
    i0 => aux41,
    i1 => not_rtlcarry_0(5),
    i2 => inv_x2_4_sig,
    i3 => na2_x1_2_sig,
    q => oa2a22_x2_sig
  );
  inv_x2_4_ins : inv_x2
  PORT MAP (
    i => not_aux38,
    nq => inv_x2_4_sig
  );
  na2_x1_2_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_rtlcarry_0(5),
    nq => na2_x1_2_sig
  );
  reg_nreg_4_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_sig,
    q => reg_nreg(4)
  );
  nao22_x1_ins : nao22_x1
  PORT MAP (
    i0 => a2_x2_9_sig,
    i1 => o2_x2_sig,
    i2 => o3_x2_2_sig,
    nq => nao22_x1_sig
  );
  a2_x2_9_ins : a2_x2
  PORT MAP (
    i0 => na4_x1_2_sig,
    i1 => o4_x2_sig,
    q => a2_x2_9_sig
  );
  na4_x1_2_ins : na4_x1
  PORT MAP (
    i0 => not_reset,
    i1 => in_nreg_val(4),
    i2 => not_rtlcarry_0(4),
    i3 => not_c_reset_reg,
    nq => na4_x1_2_sig
  );
  o4_x2_ins : o4_x2
  PORT MAP (
    i0 => reset,
    i1 => in_nreg_val(4),
    i2 => c_reset_reg,
    i3 => not_rtlcarry_0(4),
    q => o4_x2_sig
  );
  o2_x2_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reg_nreg(4),
    q => o2_x2_sig
  );
  o3_x2_2_ins : o3_x2
  PORT MAP (
    i0 => a2_x2_8_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(4),
    q => o3_x2_2_sig
  );
  a2_x2_8_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux5,
    q => a2_x2_8_sig
  );
  reg_nreg_3_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_2_sig,
    q => reg_nreg(3)
  );
  oa22_x2_2_ins : oa22_x2
  PORT MAP (
    i0 => no4_x1_3_sig,
    i1 => not_aux4,
    i2 => no3_x1_3_sig,
    q => oa22_x2_2_sig
  );
  no4_x1_3_ins : no4_x1
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => reg_nreg(3),
    i3 => not_c_nreg,
    nq => no4_x1_3_sig
  );
  no3_x1_3_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(3),
    i1 => not_aux0,
    i2 => a2_x2_7_sig,
    nq => no3_x1_3_sig
  );
  a2_x2_7_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => a2_x2_7_sig
  );
  reg_nreg_2_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_sig,
    q => reg_nreg(2)
  );
  oa22_x2_ins : oa22_x2
  PORT MAP (
    i0 => no4_x1_2_sig,
    i1 => not_aux3,
    i2 => no3_x1_2_sig,
    q => oa22_x2_sig
  );
  no4_x1_2_ins : no4_x1
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => reg_nreg(2),
    i3 => not_c_nreg,
    nq => no4_x1_2_sig
  );
  no3_x1_2_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(2),
    i1 => not_aux0,
    i2 => a2_x2_6_sig,
    nq => no3_x1_2_sig
  );
  a2_x2_6_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux3,
    q => a2_x2_6_sig
  );
  reg_nreg_1_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_sig,
    q => reg_nreg(1)
  );
  na2_x1_ins : na2_x1
  PORT MAP (
    i0 => o3_x2_sig,
    i1 => na4_x1_sig,
    nq => na2_x1_sig
  );
  o3_x2_ins : o3_x2
  PORT MAP (
    i0 => a2_x2_5_sig,
    i1 => not_aux0,
    i2 => not_reg_nreg(1),
    q => o3_x2_sig
  );
  a2_x2_5_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux2,
    q => a2_x2_5_sig
  );
  na4_x1_ins : na4_x1
  PORT MAP (
    i0 => not_reg_nreg(1),
    i1 => c_nreg,
    i2 => not_aux2,
    i3 => aux0,
    nq => na4_x1_sig
  );
  reg_nreg_0_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => on12_x1_sig,
    q => reg_nreg(0)
  );
  on12_x1_ins : on12_x1
  PORT MAP (
    i0 => na3_x1_3_sig,
    i1 => no3_x1_sig,
    q => on12_x1_sig
  );
  na3_x1_3_ins : na3_x1
  PORT MAP (
    i0 => in_nreg_val(0),
    i1 => not_aux1,
    i2 => not_reg_nreg(0),
    nq => na3_x1_3_sig
  );
  no3_x1_ins : no3_x1
  PORT MAP (
    i0 => not_reg_nreg(0),
    i1 => not_aux0,
    i2 => a2_x2_4_sig,
    nq => no3_x1_sig
  );
  a2_x2_4_ins : a2_x2
  PORT MAP (
    i0 => in_nreg_val(0),
    i1 => c_nreg,
    q => a2_x2_4_sig
  );
  rtlcarry_0_12_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(11),
    i1 => in_nreg_val(11),
    i2 => in_nreg_val(11),
    i3 => reg_nreg(11),
    i4 => rtlcarry_0(11),
    q => rtlcarry_0(12)
  );
  rtlcarry_0_11_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(10),
    i1 => in_nreg_val(10),
    i2 => in_nreg_val(10),
    i3 => reg_nreg(10),
    i4 => rtlcarry_0(10),
    q => rtlcarry_0(11)
  );
  rtlcarry_0_10_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_3_sig,
    i1 => a2_x2_3_sig,
    i2 => not_rtlcarry_0(9),
    i3 => not_reg_nreg(9),
    nq => rtlcarry_0(10)
  );
  inv_x2_3_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(9),
    nq => inv_x2_3_sig
  );
  a2_x2_3_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(9),
    i1 => not_reg_nreg(9),
    q => a2_x2_3_sig
  );
  rtlcarry_0_9_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(8),
    i1 => in_nreg_val(8),
    i2 => in_nreg_val(8),
    i3 => reg_nreg(8),
    i4 => rtlcarry_0(8),
    q => rtlcarry_0(9)
  );
  rtlcarry_0_8_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_2_sig,
    i1 => a2_x2_2_sig,
    i2 => not_rtlcarry_0(7),
    i3 => not_reg_nreg(7),
    nq => rtlcarry_0(8)
  );
  inv_x2_2_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(7),
    nq => inv_x2_2_sig
  );
  a2_x2_2_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(7),
    i1 => not_reg_nreg(7),
    q => a2_x2_2_sig
  );
  rtlcarry_0_7_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(6),
    i1 => in_nreg_val(6),
    i2 => in_nreg_val(6),
    i3 => reg_nreg(6),
    i4 => rtlcarry_0(6),
    q => rtlcarry_0(7)
  );
  rtlcarry_0_6_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(5),
    i1 => in_nreg_val(5),
    i2 => in_nreg_val(5),
    i3 => reg_nreg(5),
    i4 => rtlcarry_0(5),
    q => rtlcarry_0(6)
  );
  rtlcarry_0_5_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(4),
    i1 => in_nreg_val(4),
    i2 => in_nreg_val(4),
    i3 => reg_nreg(4),
    i4 => rtlcarry_0(4),
    q => rtlcarry_0(5)
  );
  rtlcarry_0_4_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(3),
    i1 => in_nreg_val(3),
    i2 => in_nreg_val(3),
    i3 => reg_nreg(3),
    i4 => rtlcarry_0(3),
    q => rtlcarry_0(4)
  );
  rtlcarry_0_3_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_sig,
    i1 => a2_x2_sig,
    i2 => not_rtlcarry_0(2),
    i3 => not_reg_nreg(2),
    nq => rtlcarry_0(3)
  );
  inv_x2_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(2),
    nq => inv_x2_sig
  );
  a2_x2_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(2),
    i1 => not_reg_nreg(2),
    q => a2_x2_sig
  );
  rtlcarry_0_2_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(1),
    i1 => in_nreg_val(1),
    i2 => in_nreg_val(1),
    i3 => reg_nreg(1),
    i4 => rtlcarry_0(1),
    q => rtlcarry_0(2)
  );
  rtlcarry_0_1_ins : an12_x1
  PORT MAP (
    i0 => not_reg_nreg(0),
    i1 => in_nreg_val(0),
    q => rtlcarry_0(1)
  );
  aux0_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => c_reset_reg,
    nq => aux0
  );
  aux6_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(6),
    i1 => in_nreg_val(6),
    q => aux6
  );
  aux21_ins : no3_x1
  PORT MAP (
    i0 => na3_x1_2_sig,
    i1 => reg_nreg(15),
    i2 => not_rtlcarry_0(15),
    nq => aux21
  );
  na3_x1_2_ins : na3_x1
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    nq => na3_x1_2_sig
  );
  aux27_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(2),
    q => aux27
  );
  aux28_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(3),
    q => aux28
  );
  aux29_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(5),
    i1 => in_nreg_val(5),
    q => aux29
  );
  aux30_ins : na2_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => not_rtlalc_1(5),
    nq => aux30
  );
  aux32_ins : on12_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => rtlalc_1(6),
    q => aux32
  );
  aux33_ins : na2_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => not_rtlalc_1(7),
    nq => aux33
  );
  aux34_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(10),
    q => aux34
  );
  aux37_ins : o2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => rtlalc_1(19),
    q => aux37
  );
  aux41_ins : no2_x1
  PORT MAP (
    i0 => na3_x1_sig,
    i1 => reg_nreg(5),
    nq => aux41
  );
  na3_x1_ins : na3_x1
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    nq => na3_x1_sig
  );
  aux42_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reg_nreg(7),
    nq => aux42
  );
  not_in_nreg_val_6_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(6),
    nq => not_in_nreg_val(6)
  );
  not_c_nreg_ins : inv_x2
  PORT MAP (
    i => c_nreg,
    nq => not_c_nreg
  );
  not_c_reset_reg_ins : inv_x2
  PORT MAP (
    i => c_reset_reg,
    nq => not_c_reset_reg
  );
  not_reset_ins : inv_x2
  PORT MAP (
    i => reset,
    nq => not_reset
  );
  not_aux0_ins : inv_x2
  PORT MAP (
    i => aux0,
    nq => not_aux0
  );
  not_reg_nreg_0_ins : inv_x2
  PORT MAP (
    i => reg_nreg(0),
    nq => not_reg_nreg(0)
  );
  not_aux1_ins : no2_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => not_c_nreg,
    nq => not_aux1
  );
  not_aux2_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(1),
    i1 => in_nreg_val(1),
    q => not_aux2
  );
  not_reg_nreg_1_ins : inv_x2
  PORT MAP (
    i => reg_nreg(1),
    nq => not_reg_nreg(1)
  );
  not_rtlcarry_0_2_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(2),
    nq => not_rtlcarry_0(2)
  );
  not_aux3_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(2),
    i1 => in_nreg_val(2),
    q => not_aux3
  );
  not_reg_nreg_2_ins : inv_x2
  PORT MAP (
    i => reg_nreg(2),
    nq => not_reg_nreg(2)
  );
  not_aux4_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(3),
    i1 => in_nreg_val(3),
    q => not_aux4
  );
  not_reg_nreg_3_ins : inv_x2
  PORT MAP (
    i => reg_nreg(3),
    nq => not_reg_nreg(3)
  );
  not_rtlcarry_0_4_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(4),
    nq => not_rtlcarry_0(4)
  );
  not_aux5_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(4),
    i1 => in_nreg_val(4),
    q => not_aux5
  );
  not_reg_nreg_4_ins : inv_x2
  PORT MAP (
    i => reg_nreg(4),
    nq => not_reg_nreg(4)
  );
  not_rtlcarry_0_5_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(5),
    nq => not_rtlcarry_0(5)
  );
  not_aux38_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(5),
    i1 => not_aux0,
    q => not_aux38
  );
  not_rtlcarry_0_6_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(6),
    nq => not_rtlcarry_0(6)
  );
  not_rtlcarry_0_7_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(7),
    nq => not_rtlcarry_0(7)
  );
  not_aux7_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(7),
    i1 => in_nreg_val(7),
    q => not_aux7
  );
  not_reg_nreg_7_ins : inv_x2
  PORT MAP (
    i => reg_nreg(7),
    nq => not_reg_nreg(7)
  );
  not_aux9_ins : nxr2_x1
  PORT MAP (
    i0 => rtlcarry_0(8),
    i1 => xr2_x1_sig,
    nq => not_aux9
  );
  xr2_x1_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(8),
    i1 => in_nreg_val(8),
    q => xr2_x1_sig
  );
  not_rtlcarry_0_9_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(9),
    nq => not_rtlcarry_0(9)
  );
  not_aux10_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(9),
    i1 => in_nreg_val(9),
    q => not_aux10
  );
  not_reg_nreg_9_ins : inv_x2
  PORT MAP (
    i => reg_nreg(9),
    nq => not_reg_nreg(9)
  );
  not_rtlcarry_0_10_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(10),
    nq => not_rtlcarry_0(10)
  );
  not_aux11_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(10),
    i1 => in_nreg_val(10),
    q => not_aux11
  );
  not_reg_nreg_10_ins : inv_x2
  PORT MAP (
    i => reg_nreg(10),
    nq => not_reg_nreg(10)
  );
  not_rtlcarry_0_11_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(11),
    nq => not_rtlcarry_0(11)
  );
  not_aux12_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(11),
    i1 => in_nreg_val(11),
    q => not_aux12
  );
  not_reg_nreg_11_ins : inv_x2
  PORT MAP (
    i => reg_nreg(11),
    nq => not_reg_nreg(11)
  );
  not_aux13_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(12),
    i1 => in_nreg_val(12),
    q => not_aux13
  );
  not_aux17_ins : na2_x1
  PORT MAP (
    i0 => not_aux13,
    i1 => no4_x1_sig,
    nq => not_aux17
  );
  no4_x1_ins : no4_x1
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => reg_nreg(12),
    i3 => not_c_nreg,
    nq => no4_x1_sig
  );
  not_rtlcarry_0_13_ins : noa2ao222_x1
  PORT MAP (
    i0 => reg_nreg(12),
    i1 => in_nreg_val(12),
    i2 => reg_nreg(12),
    i3 => in_nreg_val(12),
    i4 => rtlcarry_0(12),
    nq => not_rtlcarry_0(13)
  );
  not_reg_nreg_13_ins : inv_x2
  PORT MAP (
    i => reg_nreg(13),
    nq => not_reg_nreg(13)
  );
  not_rtlcarry_0_14_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => not_reg_nreg(13),
    q => not_rtlcarry_0(14)
  );
  not_reg_nreg_14_ins : inv_x2
  PORT MAP (
    i => reg_nreg(14),
    nq => not_reg_nreg(14)
  );
  not_rtlcarry_0_15_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(14),
    i1 => not_reg_nreg(14),
    q => not_rtlcarry_0(15)
  );
  not_reg_nreg_15_ins : inv_x2
  PORT MAP (
    i => reg_nreg(15),
    nq => not_reg_nreg(15)
  );
  not_rtlcarry_0_16_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(15),
    i1 => not_reg_nreg(15),
    q => not_rtlcarry_0(16)
  );
  not_reg_nreg_16_ins : inv_x2
  PORT MAP (
    i => reg_nreg(16),
    nq => not_reg_nreg(16)
  );
  not_rtlcarry_0_17_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(16),
    i1 => not_reg_nreg(16),
    q => not_rtlcarry_0(17)
  );
  not_reg_nreg_17_ins : inv_x2
  PORT MAP (
    i => reg_nreg(17),
    nq => not_reg_nreg(17)
  );
  not_aux43_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reg_nreg(17),
    q => not_aux43
  );
  not_rtlcarry_0_18_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(17),
    i1 => not_reg_nreg(17),
    q => not_rtlcarry_0(18)
  );
  not_reg_nreg_18_ins : inv_x2
  PORT MAP (
    i => reg_nreg(18),
    nq => not_reg_nreg(18)
  );
  not_aux44_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reg_nreg(18),
    q => not_aux44
  );
  not_rtlcarry_0_19_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(18),
    i1 => not_reg_nreg(18),
    q => not_rtlcarry_0(19)
  );
  not_aux45_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(19),
    i1 => not_c_nreg,
    nq => not_aux45
  );
  not_reg_nreg_19_ins : inv_x2
  PORT MAP (
    i => reg_nreg(19),
    nq => not_reg_nreg(19)
  );
  not_aux24_ins : o4_x2
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => not_rtlcarry_0(19),
    i3 => not_c_nreg,
    q => not_aux24
  );
  not_aux26_ins : o3_x2
  PORT MAP (
    i0 => not_aux24,
    i1 => reg_nreg(20),
    i2 => not_reg_nreg(19),
    q => not_aux26
  );
  not_rtlalc_1_5_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(5),
    nq => not_rtlalc_1(5)
  );
  not_aux31_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(6),
    i1 => reg_nreg(6),
    q => not_aux31
  );
  not_rtlalc_1_7_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(7),
    nq => not_rtlalc_1(7)
  );
  not_rtlalc_1_17_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(17),
    nq => not_rtlalc_1(17)
  );
  not_aux35_ins : a2_x2
  PORT MAP (
    i0 => not_aux0,
    i1 => not_rtlalc_1(17),
    q => not_aux35
  );
  not_rtlalc_1_18_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(18),
    nq => not_rtlalc_1(18)
  );
  not_aux36_ins : a2_x2
  PORT MAP (
    i0 => not_aux0,
    i1 => not_rtlalc_1(18),
    q => not_aux36
  );
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_neuronreg_boog of neuronreg_boog is
  for RTL
    for all: buf_x2 use entity sxlib.buf_x2(vital); end for;
    for all: sff1_x4 use entity sxlib.sff1_x4(vital); end for;
    for all: na3_x1 use entity sxlib.na3_x1(vital); end for;
    for all: on12_x1 use entity sxlib.on12_x1(vital); end for;
    for all: nao22_x1 use entity sxlib.nao22_x1(vital); end for;
    for all: a2_x2 use entity sxlib.a2_x2(vital); end for;
    for all: na2_x1 use entity sxlib.na2_x1(vital); end for;
    for all: an12_x1 use entity sxlib.an12_x1(vital); end for;
    for all: o3_x2 use entity sxlib.o3_x2(vital); end for;
    for all: no2_x1 use entity sxlib.no2_x1(vital); end for;
    for all: o2_x2 use entity sxlib.o2_x2(vital); end for;
    for all: ao22_x2 use entity sxlib.ao22_x2(vital); end for;
    for all: a3_x2 use entity sxlib.a3_x2(vital); end for;
    for all: no3_x1 use entity sxlib.no3_x1(vital); end for;
    for all: a4_x2 use entity sxlib.a4_x2(vital); end for;
    for all: inv_x2 use entity sxlib.inv_x2(vital); end for;
    for all: oa22_x2 use entity sxlib.oa22_x2(vital); end for;
    for all: no4_x1 use entity sxlib.no4_x1(vital); end for;
    for all: sff2_x4 use entity sxlib.sff2_x4(vital); end for;
    for all: noa22_x1 use entity sxlib.noa22_x1(vital); end for;
    for all: na4_x1 use entity sxlib.na4_x1(vital); end for;
    for all: o4_x2 use entity sxlib.o4_x2(vital); end for;
    for all: ao2o22_x2 use entity sxlib.ao2o22_x2(vital); end for;
    for all: xr2_x1 use entity sxlib.xr2_x1(vital); end for;
    for all: oa2ao222_x2 use entity sxlib.oa2ao222_x2(vital); end for;
    for all: oa2a22_x2 use entity sxlib.oa2a22_x2(vital); end for;
    for all: nao2o22_x1 use entity sxlib.nao2o22_x1(vital); end for;
    for all: nxr2_x1 use entity sxlib.nxr2_x1(vital); end for;
    for all: noa2ao222_x1 use entity sxlib.noa2ao222_x1(vital); end for;
  end for;
end CFG_neuronreg_boog;
