-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY neuronreg_boog IS
PORT(
  clk	: IN STD_LOGIC;
  reset	: IN STD_LOGIC;
  c_nreg	: IN STD_LOGIC;
  in_nreg_val	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
  out_nreg_val	: OUT STD_LOGIC_VECTOR(20 DOWNTO 0)
);
END neuronreg_boog;

ARCHITECTURE RTL OF neuronreg_boog IS
  SIGNAL not_reg_nreg	: STD_LOGIC_VECTOR(19 DOWNTO 3);
  SIGNAL not_rtlalc_1	: STD_LOGIC_VECTOR(12 DOWNTO 8);
  SIGNAL not_rtlcarry_0	: STD_LOGIC_VECTOR(19 DOWNTO 4);
  SIGNAL reg_nreg	: STD_LOGIC_VECTOR(20 DOWNTO 0);
  SIGNAL rtlalc_1	: STD_LOGIC_VECTOR(20 DOWNTO 0);
  SIGNAL rtlcarry_0	: STD_LOGIC_VECTOR(13 DOWNTO 1);
  SIGNAL xr2_x1_sig	: STD_LOGIC;
  SIGNAL xr2_x1_6_sig	: STD_LOGIC;
  SIGNAL xr2_x1_5_sig	: STD_LOGIC;
  SIGNAL xr2_x1_4_sig	: STD_LOGIC;
  SIGNAL xr2_x1_3_sig	: STD_LOGIC;
  SIGNAL xr2_x1_2_sig	: STD_LOGIC;
  SIGNAL on12_x1_sig	: STD_LOGIC;
  SIGNAL on12_x1_2_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_5_sig	: STD_LOGIC;
  SIGNAL oa22_x2_4_sig	: STD_LOGIC;
  SIGNAL oa22_x2_3_sig	: STD_LOGIC;
  SIGNAL oa22_x2_2_sig	: STD_LOGIC;
  SIGNAL o3_x2_sig	: STD_LOGIC;
  SIGNAL o3_x2_8_sig	: STD_LOGIC;
  SIGNAL o3_x2_7_sig	: STD_LOGIC;
  SIGNAL o3_x2_6_sig	: STD_LOGIC;
  SIGNAL o3_x2_5_sig	: STD_LOGIC;
  SIGNAL o3_x2_4_sig	: STD_LOGIC;
  SIGNAL o3_x2_3_sig	: STD_LOGIC;
  SIGNAL o3_x2_2_sig	: STD_LOGIC;
  SIGNAL o2_x2_sig	: STD_LOGIC;
  SIGNAL o2_x2_6_sig	: STD_LOGIC;
  SIGNAL o2_x2_5_sig	: STD_LOGIC;
  SIGNAL o2_x2_4_sig	: STD_LOGIC;
  SIGNAL o2_x2_3_sig	: STD_LOGIC;
  SIGNAL o2_x2_2_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_9_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_8_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_7_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_6_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_5_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_4_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_3_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_2_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_11_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_10_sig	: STD_LOGIC;
  SIGNAL not_reset	: STD_LOGIC;
  SIGNAL not_c_nreg	: STD_LOGIC;
  SIGNAL not_aux8	: STD_LOGIC;
  SIGNAL not_aux6	: STD_LOGIC;
  SIGNAL not_aux51	: STD_LOGIC;
  SIGNAL not_aux5	: STD_LOGIC;
  SIGNAL not_aux48	: STD_LOGIC;
  SIGNAL not_aux46	: STD_LOGIC;
  SIGNAL not_aux43	: STD_LOGIC;
  SIGNAL not_aux41	: STD_LOGIC;
  SIGNAL not_aux4	: STD_LOGIC;
  SIGNAL not_aux39	: STD_LOGIC;
  SIGNAL not_aux38	: STD_LOGIC;
  SIGNAL not_aux37	: STD_LOGIC;
  SIGNAL not_aux35	: STD_LOGIC;
  SIGNAL not_aux29	: STD_LOGIC;
  SIGNAL not_aux27	: STD_LOGIC;
  SIGNAL not_aux26	: STD_LOGIC;
  SIGNAL not_aux25	: STD_LOGIC;
  SIGNAL not_aux23	: STD_LOGIC;
  SIGNAL not_aux21	: STD_LOGIC;
  SIGNAL not_aux2	: STD_LOGIC;
  SIGNAL not_aux19	: STD_LOGIC;
  SIGNAL not_aux16	: STD_LOGIC;
  SIGNAL not_aux12	: STD_LOGIC;
  SIGNAL not_aux10	: STD_LOGIC;
  SIGNAL not_aux1	: STD_LOGIC;
  SIGNAL not_aux0	: STD_LOGIC;
  SIGNAL no3_x1_sig	: STD_LOGIC;
  SIGNAL no3_x1_6_sig	: STD_LOGIC;
  SIGNAL no3_x1_5_sig	: STD_LOGIC;
  SIGNAL no3_x1_4_sig	: STD_LOGIC;
  SIGNAL no3_x1_3_sig	: STD_LOGIC;
  SIGNAL no3_x1_2_sig	: STD_LOGIC;
  SIGNAL no2_x1_sig	: STD_LOGIC;
  SIGNAL no2_x1_9_sig	: STD_LOGIC;
  SIGNAL no2_x1_8_sig	: STD_LOGIC;
  SIGNAL no2_x1_7_sig	: STD_LOGIC;
  SIGNAL no2_x1_6_sig	: STD_LOGIC;
  SIGNAL no2_x1_5_sig	: STD_LOGIC;
  SIGNAL no2_x1_4_sig	: STD_LOGIC;
  SIGNAL no2_x1_3_sig	: STD_LOGIC;
  SIGNAL no2_x1_2_sig	: STD_LOGIC;
  SIGNAL no2_x1_19_sig	: STD_LOGIC;
  SIGNAL no2_x1_18_sig	: STD_LOGIC;
  SIGNAL no2_x1_17_sig	: STD_LOGIC;
  SIGNAL no2_x1_16_sig	: STD_LOGIC;
  SIGNAL no2_x1_15_sig	: STD_LOGIC;
  SIGNAL no2_x1_14_sig	: STD_LOGIC;
  SIGNAL no2_x1_13_sig	: STD_LOGIC;
  SIGNAL no2_x1_12_sig	: STD_LOGIC;
  SIGNAL no2_x1_11_sig	: STD_LOGIC;
  SIGNAL no2_x1_10_sig	: STD_LOGIC;
  SIGNAL nao22_x1_sig	: STD_LOGIC;
  SIGNAL nao22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao22_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_sig	: STD_LOGIC;
  SIGNAL na3_x1_9_sig	: STD_LOGIC;
  SIGNAL na3_x1_8_sig	: STD_LOGIC;
  SIGNAL na3_x1_7_sig	: STD_LOGIC;
  SIGNAL na3_x1_6_sig	: STD_LOGIC;
  SIGNAL na3_x1_5_sig	: STD_LOGIC;
  SIGNAL na3_x1_4_sig	: STD_LOGIC;
  SIGNAL na3_x1_3_sig	: STD_LOGIC;
  SIGNAL na3_x1_2_sig	: STD_LOGIC;
  SIGNAL na2_x1_sig	: STD_LOGIC;
  SIGNAL na2_x1_8_sig	: STD_LOGIC;
  SIGNAL na2_x1_7_sig	: STD_LOGIC;
  SIGNAL na2_x1_6_sig	: STD_LOGIC;
  SIGNAL na2_x1_5_sig	: STD_LOGIC;
  SIGNAL na2_x1_4_sig	: STD_LOGIC;
  SIGNAL na2_x1_3_sig	: STD_LOGIC;
  SIGNAL na2_x1_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_sig	: STD_LOGIC;
  SIGNAL inv_x2_9_sig	: STD_LOGIC;
  SIGNAL inv_x2_8_sig	: STD_LOGIC;
  SIGNAL inv_x2_7_sig	: STD_LOGIC;
  SIGNAL inv_x2_6_sig	: STD_LOGIC;
  SIGNAL inv_x2_5_sig	: STD_LOGIC;
  SIGNAL inv_x2_4_sig	: STD_LOGIC;
  SIGNAL inv_x2_3_sig	: STD_LOGIC;
  SIGNAL inv_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_17_sig	: STD_LOGIC;
  SIGNAL inv_x2_16_sig	: STD_LOGIC;
  SIGNAL inv_x2_15_sig	: STD_LOGIC;
  SIGNAL inv_x2_14_sig	: STD_LOGIC;
  SIGNAL inv_x2_13_sig	: STD_LOGIC;
  SIGNAL inv_x2_12_sig	: STD_LOGIC;
  SIGNAL inv_x2_11_sig	: STD_LOGIC;
  SIGNAL inv_x2_10_sig	: STD_LOGIC;
  SIGNAL aux9	: STD_LOGIC;
  SIGNAL aux7	: STD_LOGIC;
  SIGNAL aux56	: STD_LOGIC;
  SIGNAL aux55	: STD_LOGIC;
  SIGNAL aux54	: STD_LOGIC;
  SIGNAL aux53	: STD_LOGIC;
  SIGNAL aux52	: STD_LOGIC;
  SIGNAL aux50	: STD_LOGIC;
  SIGNAL aux49	: STD_LOGIC;
  SIGNAL aux47	: STD_LOGIC;
  SIGNAL aux45	: STD_LOGIC;
  SIGNAL aux44	: STD_LOGIC;
  SIGNAL aux42	: STD_LOGIC;
  SIGNAL aux40	: STD_LOGIC;
  SIGNAL aux36	: STD_LOGIC;
  SIGNAL aux34	: STD_LOGIC;
  SIGNAL aux33	: STD_LOGIC;
  SIGNAL aux32	: STD_LOGIC;
  SIGNAL aux31	: STD_LOGIC;
  SIGNAL aux30	: STD_LOGIC;
  SIGNAL aux3	: STD_LOGIC;
  SIGNAL aux28	: STD_LOGIC;
  SIGNAL aux26	: STD_LOGIC;
  SIGNAL aux22	: STD_LOGIC;
  SIGNAL aux20	: STD_LOGIC;
  SIGNAL aux17	: STD_LOGIC;
  SIGNAL aux15	: STD_LOGIC;
  SIGNAL aux14	: STD_LOGIC;
  SIGNAL aux13	: STD_LOGIC;
  SIGNAL aux11	: STD_LOGIC;
  SIGNAL ao2o22_x2_sig	: STD_LOGIC;
  SIGNAL ao2o22_x2_4_sig	: STD_LOGIC;
  SIGNAL ao2o22_x2_3_sig	: STD_LOGIC;
  SIGNAL ao2o22_x2_2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_3_sig	: STD_LOGIC;
  SIGNAL ao22_x2_2_sig	: STD_LOGIC;
  SIGNAL an12_x1_sig	: STD_LOGIC;
  SIGNAL an12_x1_7_sig	: STD_LOGIC;
  SIGNAL an12_x1_6_sig	: STD_LOGIC;
  SIGNAL an12_x1_5_sig	: STD_LOGIC;
  SIGNAL an12_x1_4_sig	: STD_LOGIC;
  SIGNAL an12_x1_3_sig	: STD_LOGIC;
  SIGNAL an12_x1_2_sig	: STD_LOGIC;
  SIGNAL a3_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_4_sig	: STD_LOGIC;
  SIGNAL a3_x2_3_sig	: STD_LOGIC;
  SIGNAL a3_x2_2_sig	: STD_LOGIC;
  SIGNAL a2_x2_sig	: STD_LOGIC;
  SIGNAL a2_x2_9_sig	: STD_LOGIC;
  SIGNAL a2_x2_8_sig	: STD_LOGIC;
  SIGNAL a2_x2_7_sig	: STD_LOGIC;
  SIGNAL a2_x2_6_sig	: STD_LOGIC;
  SIGNAL a2_x2_5_sig	: STD_LOGIC;
  SIGNAL a2_x2_4_sig	: STD_LOGIC;
  SIGNAL a2_x2_3_sig	: STD_LOGIC;
  SIGNAL a2_x2_2_sig	: STD_LOGIC;

  COMPONENT buf_x2
  PORT(
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT sff1_x4
  PORT(
  ck	: IN STD_LOGIC;
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT on12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT an12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT sff2_x4
  PORT(
  ck	: IN STD_LOGIC;
  cmd	: IN STD_LOGIC;
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT inv_x2
  PORT(
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao2o22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT xr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2ao222_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nxr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao2o22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa2ao222_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

BEGIN
  out_nreg_val_20_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(20),
    q => out_nreg_val(20)
  );
  out_nreg_val_19_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(19),
    q => out_nreg_val(19)
  );
  out_nreg_val_18_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(18),
    q => out_nreg_val(18)
  );
  out_nreg_val_17_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(17),
    q => out_nreg_val(17)
  );
  out_nreg_val_16_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(16),
    q => out_nreg_val(16)
  );
  out_nreg_val_15_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(15),
    q => out_nreg_val(15)
  );
  out_nreg_val_14_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(14),
    q => out_nreg_val(14)
  );
  out_nreg_val_13_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(13),
    q => out_nreg_val(13)
  );
  out_nreg_val_12_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(12),
    q => out_nreg_val(12)
  );
  out_nreg_val_11_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(11),
    q => out_nreg_val(11)
  );
  out_nreg_val_10_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(10),
    q => out_nreg_val(10)
  );
  out_nreg_val_9_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(9),
    q => out_nreg_val(9)
  );
  out_nreg_val_8_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(8),
    q => out_nreg_val(8)
  );
  out_nreg_val_7_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(7),
    q => out_nreg_val(7)
  );
  out_nreg_val_6_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(6),
    q => out_nreg_val(6)
  );
  out_nreg_val_5_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(5),
    q => out_nreg_val(5)
  );
  out_nreg_val_4_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(4),
    q => out_nreg_val(4)
  );
  out_nreg_val_3_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(3),
    q => out_nreg_val(3)
  );
  out_nreg_val_2_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(2),
    q => out_nreg_val(2)
  );
  out_nreg_val_1_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(1),
    q => out_nreg_val(1)
  );
  out_nreg_val_0_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(0),
    q => out_nreg_val(0)
  );
  rtlalc_1_20_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_9_sig,
    q => rtlalc_1(20)
  );
  na3_x1_9_ins : na3_x1
  PORT MAP (
    i0 => not_aux25,
    i1 => on12_x1_2_sig,
    i2 => nao22_x1_6_sig,
    nq => na3_x1_9_sig
  );
  on12_x1_2_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(20),
    i1 => not_aux26,
    q => on12_x1_2_sig
  );
  nao22_x1_6_ins : nao22_x1
  PORT MAP (
    i0 => not_reg_nreg(19),
    i1 => not_rtlcarry_0(19),
    i2 => an12_x1_7_sig,
    nq => nao22_x1_6_sig
  );
  an12_x1_7_ins : an12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => aux52,
    q => an12_x1_7_sig
  );
  rtlalc_1_19_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => not_reset,
    i0 => rtlalc_1(19),
    i1 => o2_x2_6_sig,
    q => rtlalc_1(19)
  );
  o2_x2_6_ins : o2_x2
  PORT MAP (
    i0 => no3_x1_6_sig,
    i1 => no3_x1_5_sig,
    q => o2_x2_6_sig
  );
  no3_x1_6_ins : no3_x1
  PORT MAP (
    i0 => a2_x2_9_sig,
    i1 => reg_nreg(19),
    i2 => not_aux38,
    nq => no3_x1_6_sig
  );
  a2_x2_9_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_rtlcarry_0(19),
    q => a2_x2_9_sig
  );
  no3_x1_5_ins : no3_x1
  PORT MAP (
    i0 => aux22,
    i1 => not_reg_nreg(19),
    i2 => not_aux38,
    nq => no3_x1_5_sig
  );
  rtlalc_1_18_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => not_reset,
    i0 => rtlalc_1(18),
    i1 => oa22_x2_5_sig,
    q => rtlalc_1(18)
  );
  oa22_x2_5_ins : oa22_x2
  PORT MAP (
    i0 => reg_nreg(18),
    i1 => no2_x1_19_sig,
    i2 => no3_x1_4_sig,
    q => oa22_x2_5_sig
  );
  no2_x1_19_ins : no2_x1
  PORT MAP (
    i0 => not_aux37,
    i1 => not_aux21,
    nq => no2_x1_19_sig
  );
  no3_x1_4_ins : no3_x1
  PORT MAP (
    i0 => a2_x2_8_sig,
    i1 => reg_nreg(18),
    i2 => not_aux37,
    nq => no3_x1_4_sig
  );
  a2_x2_8_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_rtlcarry_0(18),
    q => a2_x2_8_sig
  );
  rtlalc_1_17_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_7_sig,
    q => rtlalc_1(17)
  );
  na3_x1_7_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_8_sig,
    i1 => na3_x1_8_sig,
    i2 => o3_x2_8_sig,
    nq => na3_x1_7_sig
  );
  na2_x1_8_ins : na2_x1
  PORT MAP (
    i0 => rtlalc_1(17),
    i1 => aux26,
    nq => na2_x1_8_sig
  );
  na3_x1_8_ins : na3_x1
  PORT MAP (
    i0 => aux50,
    i1 => not_rtlcarry_0(17),
    i2 => aux36,
    nq => na3_x1_8_sig
  );
  o3_x2_8_ins : o3_x2
  PORT MAP (
    i0 => not_aux51,
    i1 => not_rtlcarry_0(17),
    i2 => inv_x2_17_sig,
    q => o3_x2_8_sig
  );
  inv_x2_17_ins : inv_x2
  PORT MAP (
    i => aux36,
    nq => inv_x2_17_sig
  );
  rtlalc_1_16_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_5_sig,
    q => rtlalc_1(16)
  );
  na3_x1_5_ins : na3_x1
  PORT MAP (
    i0 => not_aux19,
    i1 => on12_x1_sig,
    i2 => na3_x1_6_sig,
    nq => na3_x1_5_sig
  );
  on12_x1_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(16),
    i1 => not_aux26,
    q => on12_x1_sig
  );
  na3_x1_6_ins : na3_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_rtlcarry_0(16),
    i2 => aux49,
    nq => na3_x1_6_sig
  );
  rtlalc_1_15_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => not_reset,
    i0 => rtlalc_1(15),
    i1 => oa22_x2_4_sig,
    q => rtlalc_1(15)
  );
  oa22_x2_4_ins : oa22_x2
  PORT MAP (
    i0 => reg_nreg(15),
    i1 => no2_x1_18_sig,
    i2 => no3_x1_3_sig,
    q => oa22_x2_4_sig
  );
  no2_x1_18_ins : no2_x1
  PORT MAP (
    i0 => not_aux35,
    i1 => not_aux16,
    nq => no2_x1_18_sig
  );
  no3_x1_3_ins : no3_x1
  PORT MAP (
    i0 => a2_x2_7_sig,
    i1 => reg_nreg(15),
    i2 => not_aux35,
    nq => no3_x1_3_sig
  );
  a2_x2_7_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_rtlcarry_0(15),
    q => a2_x2_7_sig
  );
  rtlalc_1_14_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_3_sig,
    q => rtlalc_1(14)
  );
  na3_x1_3_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_7_sig,
    i1 => na3_x1_4_sig,
    i2 => o3_x2_7_sig,
    nq => na3_x1_3_sig
  );
  na2_x1_7_ins : na2_x1
  PORT MAP (
    i0 => rtlalc_1(14),
    i1 => aux26,
    nq => na2_x1_7_sig
  );
  na3_x1_4_ins : na3_x1
  PORT MAP (
    i0 => aux47,
    i1 => not_rtlcarry_0(14),
    i2 => aux34,
    nq => na3_x1_4_sig
  );
  o3_x2_7_ins : o3_x2
  PORT MAP (
    i0 => not_aux48,
    i1 => not_rtlcarry_0(14),
    i2 => inv_x2_16_sig,
    q => o3_x2_7_sig
  );
  inv_x2_16_ins : inv_x2
  PORT MAP (
    i => aux34,
    nq => inv_x2_16_sig
  );
  rtlalc_1_13_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao2o22_x2_4_sig,
    q => rtlalc_1(13)
  );
  ao2o22_x2_4_ins : ao2o22_x2
  PORT MAP (
    i0 => na2_x1_6_sig,
    i1 => xr2_x1_6_sig,
    i2 => rtlalc_1(13),
    i3 => not_aux26,
    q => ao2o22_x2_4_sig
  );
  na2_x1_6_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_reset,
    nq => na2_x1_6_sig
  );
  xr2_x1_6_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(13),
    i1 => reg_nreg(13),
    q => xr2_x1_6_sig
  );
  rtlalc_1_12_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => o2_x2_5_sig,
    q => rtlalc_1(12)
  );
  o2_x2_5_ins : o2_x2
  PORT MAP (
    i0 => a3_x2_4_sig,
    i1 => nao22_x1_5_sig,
    q => o2_x2_5_sig
  );
  a3_x2_4_ins : a3_x2
  PORT MAP (
    i0 => aux45,
    i1 => not_rtlcarry_0(12),
    i2 => aux33,
    q => a3_x2_4_sig
  );
  nao22_x1_5_ins : nao22_x1
  PORT MAP (
    i0 => not_rtlalc_1(12),
    i1 => not_aux26,
    i2 => o3_x2_6_sig,
    nq => nao22_x1_5_sig
  );
  o3_x2_6_ins : o3_x2
  PORT MAP (
    i0 => not_aux46,
    i1 => not_rtlcarry_0(12),
    i2 => inv_x2_15_sig,
    q => o3_x2_6_sig
  );
  inv_x2_15_ins : inv_x2
  PORT MAP (
    i => aux33,
    nq => inv_x2_15_sig
  );
  rtlalc_1_11_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => o2_x2_4_sig,
    q => rtlalc_1(11)
  );
  o2_x2_4_ins : o2_x2
  PORT MAP (
    i0 => a3_x2_3_sig,
    i1 => nao22_x1_4_sig,
    q => o2_x2_4_sig
  );
  a3_x2_3_ins : a3_x2
  PORT MAP (
    i0 => aux44,
    i1 => not_aux12,
    i2 => aux32,
    q => a3_x2_3_sig
  );
  nao22_x1_4_ins : nao22_x1
  PORT MAP (
    i0 => not_rtlalc_1(11),
    i1 => not_aux26,
    i2 => o3_x2_5_sig,
    nq => nao22_x1_4_sig
  );
  o3_x2_5_ins : o3_x2
  PORT MAP (
    i0 => not_aux43,
    i1 => not_aux12,
    i2 => inv_x2_14_sig,
    q => o3_x2_5_sig
  );
  inv_x2_14_ins : inv_x2
  PORT MAP (
    i => aux32,
    nq => inv_x2_14_sig
  );
  rtlalc_1_10_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa2ao222_x2_2_sig,
    q => rtlalc_1(10)
  );
  oa2ao222_x2_2_ins : oa2ao222_x2
  PORT MAP (
    i0 => rtlalc_1(10),
    i1 => reset,
    i2 => xr2_x1_5_sig,
    i3 => not_c_nreg,
    i4 => ao22_x2_3_sig,
    q => oa2ao222_x2_2_sig
  );
  xr2_x1_5_ins : xr2_x1
  PORT MAP (
    i0 => aux56,
    i1 => reg_nreg(10),
    q => xr2_x1_5_sig
  );
  ao22_x2_3_ins : ao22_x2
  PORT MAP (
    i0 => rtlalc_1(10),
    i1 => c_nreg,
    i2 => not_reset,
    q => ao22_x2_3_sig
  );
  rtlalc_1_9_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => o2_x2_3_sig,
    q => rtlalc_1(9)
  );
  o2_x2_3_ins : o2_x2
  PORT MAP (
    i0 => a3_x2_2_sig,
    i1 => nao22_x1_3_sig,
    q => o2_x2_3_sig
  );
  a3_x2_2_ins : a3_x2
  PORT MAP (
    i0 => aux42,
    i1 => not_aux10,
    i2 => aux31,
    q => a3_x2_2_sig
  );
  nao22_x1_3_ins : nao22_x1
  PORT MAP (
    i0 => not_rtlalc_1(9),
    i1 => not_aux26,
    i2 => o3_x2_4_sig,
    nq => nao22_x1_3_sig
  );
  o3_x2_4_ins : o3_x2
  PORT MAP (
    i0 => not_aux41,
    i1 => not_aux10,
    i2 => inv_x2_13_sig,
    q => o3_x2_4_sig
  );
  inv_x2_13_ins : inv_x2
  PORT MAP (
    i => aux31,
    nq => inv_x2_13_sig
  );
  rtlalc_1_8_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => o2_x2_2_sig,
    q => rtlalc_1(8)
  );
  o2_x2_2_ins : o2_x2
  PORT MAP (
    i0 => a3_x2_sig,
    i1 => nao22_x1_2_sig,
    q => o2_x2_2_sig
  );
  a3_x2_ins : a3_x2
  PORT MAP (
    i0 => aux40,
    i1 => not_aux8,
    i2 => aux30,
    q => a3_x2_sig
  );
  nao22_x1_2_ins : nao22_x1
  PORT MAP (
    i0 => not_rtlalc_1(8),
    i1 => not_aux26,
    i2 => o3_x2_3_sig,
    nq => nao22_x1_2_sig
  );
  o3_x2_3_ins : o3_x2
  PORT MAP (
    i0 => not_aux39,
    i1 => not_aux8,
    i2 => inv_x2_12_sig,
    q => o3_x2_3_sig
  );
  inv_x2_12_ins : inv_x2
  PORT MAP (
    i => aux30,
    nq => inv_x2_12_sig
  );
  rtlalc_1_7_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao22_x2_2_sig,
    q => rtlalc_1(7)
  );
  ao22_x2_2_ins : ao22_x2
  PORT MAP (
    i0 => rtlalc_1(7),
    i1 => not_aux26,
    i2 => o3_x2_2_sig,
    q => ao22_x2_2_sig
  );
  o3_x2_2_ins : o3_x2
  PORT MAP (
    i0 => aux26,
    i1 => no2_x1_17_sig,
    i2 => a2_x2_6_sig,
    q => o3_x2_2_sig
  );
  no2_x1_17_ins : no2_x1
  PORT MAP (
    i0 => not_aux6,
    i1 => not_reg_nreg(7),
    nq => no2_x1_17_sig
  );
  a2_x2_6_ins : a2_x2
  PORT MAP (
    i0 => not_aux6,
    i1 => not_reg_nreg(7),
    q => a2_x2_6_sig
  );
  rtlalc_1_6_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => not_reset,
    i0 => rtlalc_1(6),
    i1 => oa22_x2_3_sig,
    q => rtlalc_1(6)
  );
  oa22_x2_3_ins : oa22_x2
  PORT MAP (
    i0 => reg_nreg(6),
    i1 => no2_x1_16_sig,
    i2 => no3_x1_2_sig,
    q => oa22_x2_3_sig
  );
  no2_x1_16_ins : no2_x1
  PORT MAP (
    i0 => not_aux29,
    i1 => not_aux5,
    nq => no2_x1_16_sig
  );
  no3_x1_2_ins : no3_x1
  PORT MAP (
    i0 => a2_x2_5_sig,
    i1 => reg_nreg(6),
    i2 => not_aux29,
    nq => no3_x1_2_sig
  );
  a2_x2_5_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => a2_x2_5_sig
  );
  rtlalc_1_5_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa2ao222_x2_sig,
    q => rtlalc_1(5)
  );
  oa2ao222_x2_ins : oa2ao222_x2
  PORT MAP (
    i0 => rtlalc_1(5),
    i1 => reset,
    i2 => xr2_x1_4_sig,
    i3 => not_c_nreg,
    i4 => ao22_x2_sig,
    q => oa2ao222_x2_sig
  );
  xr2_x1_4_ins : xr2_x1
  PORT MAP (
    i0 => aux55,
    i1 => reg_nreg(5),
    q => xr2_x1_4_sig
  );
  ao22_x2_ins : ao22_x2
  PORT MAP (
    i0 => rtlalc_1(5),
    i1 => c_nreg,
    i2 => not_reset,
    q => ao22_x2_sig
  );
  rtlalc_1_4_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao2o22_x2_3_sig,
    q => rtlalc_1(4)
  );
  ao2o22_x2_3_ins : ao2o22_x2
  PORT MAP (
    i0 => na2_x1_5_sig,
    i1 => xr2_x1_3_sig,
    i2 => rtlalc_1(4),
    i3 => not_aux26,
    q => ao2o22_x2_3_sig
  );
  na2_x1_5_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_reset,
    nq => na2_x1_5_sig
  );
  xr2_x1_3_ins : xr2_x1
  PORT MAP (
    i0 => aux54,
    i1 => reg_nreg(4),
    q => xr2_x1_3_sig
  );
  rtlalc_1_3_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_sig,
    q => rtlalc_1(3)
  );
  na3_x1_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_4_sig,
    i1 => na3_x1_2_sig,
    i2 => o3_x2_sig,
    nq => na3_x1_sig
  );
  na2_x1_4_ins : na2_x1
  PORT MAP (
    i0 => rtlalc_1(3),
    i1 => aux26,
    nq => na2_x1_4_sig
  );
  na3_x1_2_ins : na3_x1
  PORT MAP (
    i0 => not_reg_nreg(3),
    i1 => not_aux2,
    i2 => aux28,
    nq => na3_x1_2_sig
  );
  o3_x2_ins : o3_x2
  PORT MAP (
    i0 => not_reg_nreg(3),
    i1 => not_aux2,
    i2 => inv_x2_11_sig,
    q => o3_x2_sig
  );
  inv_x2_11_ins : inv_x2
  PORT MAP (
    i => aux28,
    nq => inv_x2_11_sig
  );
  rtlalc_1_2_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => not_reset,
    i0 => rtlalc_1(2),
    i1 => oa22_x2_2_sig,
    q => rtlalc_1(2)
  );
  oa22_x2_2_ins : oa22_x2
  PORT MAP (
    i0 => reg_nreg(2),
    i1 => no2_x1_15_sig,
    i2 => no3_x1_sig,
    q => oa22_x2_2_sig
  );
  no2_x1_15_ins : no2_x1
  PORT MAP (
    i0 => not_aux27,
    i1 => not_aux1,
    nq => no2_x1_15_sig
  );
  no3_x1_ins : no3_x1
  PORT MAP (
    i0 => a2_x2_4_sig,
    i1 => reg_nreg(2),
    i2 => not_aux27,
    nq => no3_x1_sig
  );
  a2_x2_4_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux0,
    q => a2_x2_4_sig
  );
  rtlalc_1_1_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao2o22_x2_2_sig,
    q => rtlalc_1(1)
  );
  ao2o22_x2_2_ins : ao2o22_x2
  PORT MAP (
    i0 => na2_x1_3_sig,
    i1 => xr2_x1_2_sig,
    i2 => rtlalc_1(1),
    i3 => not_aux26,
    q => ao2o22_x2_2_sig
  );
  na2_x1_3_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_reset,
    nq => na2_x1_3_sig
  );
  xr2_x1_2_ins : xr2_x1
  PORT MAP (
    i0 => aux53,
    i1 => reg_nreg(1),
    q => xr2_x1_2_sig
  );
  rtlalc_1_0_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => ao2o22_x2_sig,
    q => rtlalc_1(0)
  );
  ao2o22_x2_ins : ao2o22_x2
  PORT MAP (
    i0 => na2_x1_2_sig,
    i1 => xr2_x1_sig,
    i2 => rtlalc_1(0),
    i3 => not_aux26,
    q => ao2o22_x2_sig
  );
  na2_x1_2_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_reset,
    nq => na2_x1_2_sig
  );
  xr2_x1_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(0),
    i1 => in_nreg_val(0),
    q => xr2_x1_sig
  );
  reg_nreg_20_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => oa22_x2_sig,
    q => reg_nreg(20)
  );
  oa22_x2_ins : oa22_x2
  PORT MAP (
    i0 => aux52,
    i1 => not_aux23,
    i2 => inv_x2_10_sig,
    q => oa22_x2_sig
  );
  inv_x2_10_ins : inv_x2
  PORT MAP (
    i => not_aux25,
    nq => inv_x2_10_sig
  );
  reg_nreg_19_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_14_sig,
    q => reg_nreg(19)
  );
  no2_x1_14_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_11_sig,
    nq => no2_x1_14_sig
  );
  nxr2_x1_11_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(19),
    i1 => aux22,
    nq => nxr2_x1_11_sig
  );
  reg_nreg_18_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_13_sig,
    q => reg_nreg(18)
  );
  no2_x1_13_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_10_sig,
    nq => no2_x1_13_sig
  );
  nxr2_x1_10_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(18),
    i1 => not_aux21,
    nq => nxr2_x1_10_sig
  );
  reg_nreg_17_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => aux20,
    i0 => inv_x2_9_sig,
    i1 => aux50,
    q => reg_nreg(17)
  );
  inv_x2_9_ins : inv_x2
  PORT MAP (
    i => not_aux51,
    nq => inv_x2_9_sig
  );
  reg_nreg_16_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_sig,
    q => reg_nreg(16)
  );
  nao22_x1_ins : nao22_x1
  PORT MAP (
    i0 => aux17,
    i1 => inv_x2_8_sig,
    i2 => not_aux19,
    nq => nao22_x1_sig
  );
  inv_x2_8_ins : inv_x2
  PORT MAP (
    i => aux49,
    nq => inv_x2_8_sig
  );
  reg_nreg_15_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_12_sig,
    q => reg_nreg(15)
  );
  no2_x1_12_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_9_sig,
    nq => no2_x1_12_sig
  );
  nxr2_x1_9_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(15),
    i1 => not_aux16,
    nq => nxr2_x1_9_sig
  );
  reg_nreg_14_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => aux15,
    i0 => inv_x2_7_sig,
    i1 => aux47,
    q => reg_nreg(14)
  );
  inv_x2_7_ins : inv_x2
  PORT MAP (
    i => not_aux48,
    nq => inv_x2_7_sig
  );
  reg_nreg_13_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_10_sig,
    q => reg_nreg(13)
  );
  no2_x1_10_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_8_sig,
    nq => no2_x1_10_sig
  );
  nxr2_x1_8_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(13),
    i1 => no2_x1_11_sig,
    nq => nxr2_x1_8_sig
  );
  no2_x1_11_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(13),
    nq => no2_x1_11_sig
  );
  reg_nreg_12_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => aux14,
    i0 => inv_x2_6_sig,
    i1 => aux45,
    q => reg_nreg(12)
  );
  inv_x2_6_ins : inv_x2
  PORT MAP (
    i => not_aux46,
    nq => inv_x2_6_sig
  );
  reg_nreg_11_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => aux13,
    i0 => aux44,
    i1 => inv_x2_5_sig,
    q => reg_nreg(11)
  );
  inv_x2_5_ins : inv_x2
  PORT MAP (
    i => not_aux43,
    nq => inv_x2_5_sig
  );
  reg_nreg_10_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_9_sig,
    q => reg_nreg(10)
  );
  no2_x1_9_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_7_sig,
    nq => no2_x1_9_sig
  );
  nxr2_x1_7_ins : nxr2_x1
  PORT MAP (
    i0 => an12_x1_6_sig,
    i1 => reg_nreg(10),
    nq => nxr2_x1_7_sig
  );
  an12_x1_6_ins : an12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => aux56,
    q => an12_x1_6_sig
  );
  reg_nreg_9_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => aux11,
    i0 => aux42,
    i1 => inv_x2_4_sig,
    q => reg_nreg(9)
  );
  inv_x2_4_ins : inv_x2
  PORT MAP (
    i => not_aux41,
    nq => inv_x2_4_sig
  );
  reg_nreg_8_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => aux9,
    i0 => aux40,
    i1 => inv_x2_3_sig,
    q => reg_nreg(8)
  );
  inv_x2_3_ins : inv_x2
  PORT MAP (
    i => not_aux39,
    nq => inv_x2_3_sig
  );
  reg_nreg_7_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => reg_nreg(7),
    i0 => no2_x1_8_sig,
    i1 => an12_x1_5_sig,
    q => reg_nreg(7)
  );
  no2_x1_8_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => aux7,
    nq => no2_x1_8_sig
  );
  an12_x1_5_ins : an12_x1
  PORT MAP (
    i0 => reset,
    i1 => aux7,
    q => an12_x1_5_sig
  );
  reg_nreg_6_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_7_sig,
    q => reg_nreg(6)
  );
  no2_x1_7_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_6_sig,
    nq => no2_x1_7_sig
  );
  nxr2_x1_6_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(6),
    i1 => not_aux5,
    nq => nxr2_x1_6_sig
  );
  reg_nreg_5_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_6_sig,
    q => reg_nreg(5)
  );
  no2_x1_6_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_5_sig,
    nq => no2_x1_6_sig
  );
  nxr2_x1_5_ins : nxr2_x1
  PORT MAP (
    i0 => an12_x1_4_sig,
    i1 => reg_nreg(5),
    nq => nxr2_x1_5_sig
  );
  an12_x1_4_ins : an12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => aux55,
    q => an12_x1_4_sig
  );
  reg_nreg_4_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_5_sig,
    q => reg_nreg(4)
  );
  no2_x1_5_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_4_sig,
    nq => no2_x1_5_sig
  );
  nxr2_x1_4_ins : nxr2_x1
  PORT MAP (
    i0 => an12_x1_3_sig,
    i1 => reg_nreg(4),
    nq => nxr2_x1_4_sig
  );
  an12_x1_3_ins : an12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => aux54,
    q => an12_x1_3_sig
  );
  reg_nreg_3_ins : sff2_x4
  PORT MAP (
    ck => clk,
    cmd => reg_nreg(3),
    i0 => no2_x1_4_sig,
    i1 => an12_x1_2_sig,
    q => reg_nreg(3)
  );
  no2_x1_4_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => aux3,
    nq => no2_x1_4_sig
  );
  an12_x1_2_ins : an12_x1
  PORT MAP (
    i0 => reset,
    i1 => aux3,
    q => an12_x1_2_sig
  );
  reg_nreg_2_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_3_sig,
    q => reg_nreg(2)
  );
  no2_x1_3_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_3_sig,
    nq => no2_x1_3_sig
  );
  nxr2_x1_3_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(2),
    i1 => not_aux1,
    nq => nxr2_x1_3_sig
  );
  reg_nreg_1_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_2_sig,
    q => reg_nreg(1)
  );
  no2_x1_2_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_2_sig,
    nq => no2_x1_2_sig
  );
  nxr2_x1_2_ins : nxr2_x1
  PORT MAP (
    i0 => an12_x1_sig,
    i1 => reg_nreg(1),
    nq => nxr2_x1_2_sig
  );
  an12_x1_ins : an12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => aux53,
    q => an12_x1_sig
  );
  reg_nreg_0_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => no2_x1_sig,
    q => reg_nreg(0)
  );
  no2_x1_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => nxr2_x1_sig,
    nq => no2_x1_sig
  );
  nxr2_x1_ins : nxr2_x1
  PORT MAP (
    i0 => reg_nreg(0),
    i1 => a2_x2_3_sig,
    nq => nxr2_x1_sig
  );
  a2_x2_3_ins : a2_x2
  PORT MAP (
    i0 => in_nreg_val(0),
    i1 => c_nreg,
    q => a2_x2_3_sig
  );
  rtlcarry_0_13_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(12),
    i1 => not_reg_nreg(12),
    nq => rtlcarry_0(13)
  );
  rtlcarry_0_11_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(10),
    i1 => in_nreg_val(10),
    i2 => in_nreg_val(10),
    i3 => reg_nreg(10),
    i4 => rtlcarry_0(10),
    q => rtlcarry_0(11)
  );
  rtlcarry_0_10_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(9),
    i1 => in_nreg_val(9),
    i2 => in_nreg_val(9),
    i3 => reg_nreg(9),
    i4 => rtlcarry_0(9),
    q => rtlcarry_0(10)
  );
  rtlcarry_0_9_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(8),
    i1 => in_nreg_val(8),
    i2 => in_nreg_val(8),
    i3 => reg_nreg(8),
    i4 => rtlcarry_0(8),
    q => rtlcarry_0(9)
  );
  rtlcarry_0_8_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(7),
    i1 => in_nreg_val(7),
    i2 => in_nreg_val(7),
    i3 => reg_nreg(7),
    i4 => rtlcarry_0(7),
    q => rtlcarry_0(8)
  );
  rtlcarry_0_7_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_2_sig,
    i1 => a2_x2_2_sig,
    i2 => not_rtlcarry_0(6),
    i3 => not_reg_nreg(6),
    nq => rtlcarry_0(7)
  );
  inv_x2_2_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(6),
    nq => inv_x2_2_sig
  );
  a2_x2_2_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(6),
    i1 => not_reg_nreg(6),
    q => a2_x2_2_sig
  );
  rtlcarry_0_6_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(5),
    i1 => in_nreg_val(5),
    i2 => in_nreg_val(5),
    i3 => reg_nreg(5),
    i4 => rtlcarry_0(5),
    q => rtlcarry_0(6)
  );
  rtlcarry_0_5_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_sig,
    i1 => a2_x2_sig,
    i2 => not_rtlcarry_0(4),
    i3 => not_reg_nreg(4),
    nq => rtlcarry_0(5)
  );
  inv_x2_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(4),
    nq => inv_x2_sig
  );
  a2_x2_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(4),
    i1 => not_reg_nreg(4),
    q => a2_x2_sig
  );
  rtlcarry_0_4_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(3),
    i1 => in_nreg_val(3),
    i2 => in_nreg_val(3),
    i3 => reg_nreg(3),
    i4 => rtlcarry_0(3),
    q => rtlcarry_0(4)
  );
  rtlcarry_0_3_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(2),
    i1 => in_nreg_val(2),
    i2 => in_nreg_val(2),
    i3 => reg_nreg(2),
    i4 => rtlcarry_0(2),
    q => rtlcarry_0(3)
  );
  rtlcarry_0_2_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(1),
    i1 => in_nreg_val(1),
    i2 => in_nreg_val(1),
    i3 => reg_nreg(1),
    i4 => rtlcarry_0(1),
    q => rtlcarry_0(2)
  );
  rtlcarry_0_1_ins : a2_x2
  PORT MAP (
    i0 => in_nreg_val(0),
    i1 => reg_nreg(0),
    q => rtlcarry_0(1)
  );
  aux3_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux2,
    nq => aux3
  );
  aux7_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux6,
    nq => aux7
  );
  aux9_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux8,
    nq => aux9
  );
  aux11_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux10,
    nq => aux11
  );
  aux13_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux12,
    nq => aux13
  );
  aux14_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(12),
    q => aux14
  );
  aux15_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(14),
    q => aux15
  );
  aux17_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(16),
    nq => aux17
  );
  aux20_ins : o2_x2
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(17),
    q => aux20
  );
  aux22_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(19),
    nq => aux22
  );
  aux26_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_reset,
    nq => aux26
  );
  aux28_ins : o2_x2
  PORT MAP (
    i0 => not_aux26,
    i1 => rtlalc_1(3),
    q => aux28
  );
  aux30_ins : na2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlalc_1(8),
    nq => aux30
  );
  aux31_ins : na2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlalc_1(9),
    nq => aux31
  );
  aux32_ins : na2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlalc_1(11),
    nq => aux32
  );
  aux33_ins : na2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlalc_1(12),
    nq => aux33
  );
  aux34_ins : on12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => rtlalc_1(14),
    q => aux34
  );
  aux36_ins : on12_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => rtlalc_1(17),
    q => aux36
  );
  aux40_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(8),
    nq => aux40
  );
  aux42_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(9),
    nq => aux42
  );
  aux44_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(11),
    nq => aux44
  );
  aux45_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => not_reg_nreg(12),
    nq => aux45
  );
  aux47_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => not_reg_nreg(14),
    nq => aux47
  );
  aux49_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => not_reg_nreg(16),
    nq => aux49
  );
  aux50_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => not_reg_nreg(17),
    nq => aux50
  );
  aux52_ins : an12_x1
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(20),
    q => aux52
  );
  aux53_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(1),
    i1 => in_nreg_val(1),
    q => aux53
  );
  aux54_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(4),
    i1 => in_nreg_val(4),
    q => aux54
  );
  aux55_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(5),
    i1 => in_nreg_val(5),
    q => aux55
  );
  aux56_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(10),
    i1 => in_nreg_val(10),
    q => aux56
  );
  not_c_nreg_ins : inv_x2
  PORT MAP (
    i => c_nreg,
    nq => not_c_nreg
  );
  not_reset_ins : inv_x2
  PORT MAP (
    i => reset,
    nq => not_reset
  );
  not_aux0_ins : nxr2_x1
  PORT MAP (
    i0 => rtlcarry_0(2),
    i1 => in_nreg_val(2),
    nq => not_aux0
  );
  not_aux1_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_aux0,
    nq => not_aux1
  );
  not_aux2_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(3),
    i1 => in_nreg_val(3),
    q => not_aux2
  );
  not_reg_nreg_3_ins : inv_x2
  PORT MAP (
    i => reg_nreg(3),
    nq => not_reg_nreg(3)
  );
  not_rtlcarry_0_4_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(4),
    nq => not_rtlcarry_0(4)
  );
  not_reg_nreg_4_ins : inv_x2
  PORT MAP (
    i => reg_nreg(4),
    nq => not_reg_nreg(4)
  );
  not_rtlcarry_0_6_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(6),
    nq => not_rtlcarry_0(6)
  );
  not_aux4_ins : nxr2_x1
  PORT MAP (
    i0 => rtlcarry_0(6),
    i1 => in_nreg_val(6),
    nq => not_aux4
  );
  not_aux5_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_aux4,
    nq => not_aux5
  );
  not_reg_nreg_6_ins : inv_x2
  PORT MAP (
    i => reg_nreg(6),
    nq => not_reg_nreg(6)
  );
  not_aux6_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(7),
    i1 => in_nreg_val(7),
    q => not_aux6
  );
  not_reg_nreg_7_ins : inv_x2
  PORT MAP (
    i => reg_nreg(7),
    nq => not_reg_nreg(7)
  );
  not_aux8_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(8),
    i1 => in_nreg_val(8),
    q => not_aux8
  );
  not_aux39_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(8),
    i1 => reset,
    q => not_aux39
  );
  not_aux10_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(9),
    i1 => in_nreg_val(9),
    q => not_aux10
  );
  not_aux41_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(9),
    i1 => reset,
    q => not_aux41
  );
  not_aux12_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(11),
    i1 => in_nreg_val(11),
    q => not_aux12
  );
  not_aux43_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(11),
    i1 => reset,
    q => not_aux43
  );
  not_rtlcarry_0_12_ins : noa2ao222_x1
  PORT MAP (
    i0 => reg_nreg(11),
    i1 => in_nreg_val(11),
    i2 => reg_nreg(11),
    i3 => in_nreg_val(11),
    i4 => rtlcarry_0(11),
    nq => not_rtlcarry_0(12)
  );
  not_reg_nreg_12_ins : inv_x2
  PORT MAP (
    i => reg_nreg(12),
    nq => not_reg_nreg(12)
  );
  not_aux46_ins : o2_x2
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(12),
    q => not_aux46
  );
  not_rtlcarry_0_13_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(13),
    nq => not_rtlcarry_0(13)
  );
  not_rtlcarry_0_14_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(13),
    i1 => not_rtlcarry_0(13),
    q => not_rtlcarry_0(14)
  );
  not_reg_nreg_14_ins : inv_x2
  PORT MAP (
    i => reg_nreg(14),
    nq => not_reg_nreg(14)
  );
  not_aux48_ins : o2_x2
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(14),
    q => not_aux48
  );
  not_rtlcarry_0_15_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(14),
    i1 => not_reg_nreg(14),
    q => not_rtlcarry_0(15)
  );
  not_aux16_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(15),
    nq => not_aux16
  );
  not_rtlcarry_0_16_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(15),
    i1 => not_rtlcarry_0(15),
    q => not_rtlcarry_0(16)
  );
  not_reg_nreg_16_ins : inv_x2
  PORT MAP (
    i => reg_nreg(16),
    nq => not_reg_nreg(16)
  );
  not_aux19_ins : o2_x2
  PORT MAP (
    i0 => reg_nreg(16),
    i1 => na2_x1_sig,
    q => not_aux19
  );
  na2_x1_ins : na2_x1
  PORT MAP (
    i0 => not_reset,
    i1 => aux17,
    nq => na2_x1_sig
  );
  not_rtlcarry_0_17_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(16),
    i1 => not_reg_nreg(16),
    q => not_rtlcarry_0(17)
  );
  not_reg_nreg_17_ins : inv_x2
  PORT MAP (
    i => reg_nreg(17),
    nq => not_reg_nreg(17)
  );
  not_aux51_ins : o2_x2
  PORT MAP (
    i0 => reset,
    i1 => reg_nreg(17),
    q => not_aux51
  );
  not_rtlcarry_0_18_ins : o2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(17),
    i1 => not_reg_nreg(17),
    q => not_rtlcarry_0(18)
  );
  not_aux21_ins : no2_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => not_rtlcarry_0(18),
    nq => not_aux21
  );
  not_rtlcarry_0_19_ins : on12_x1
  PORT MAP (
    i0 => reg_nreg(18),
    i1 => not_rtlcarry_0(18),
    q => not_rtlcarry_0(19)
  );
  not_reg_nreg_19_ins : inv_x2
  PORT MAP (
    i => reg_nreg(19),
    nq => not_reg_nreg(19)
  );
  not_aux23_ins : on12_x1
  PORT MAP (
    i0 => aux22,
    i1 => not_reg_nreg(19),
    q => not_aux23
  );
  not_aux25_ins : o2_x2
  PORT MAP (
    i0 => reg_nreg(20),
    i1 => o2_x2_sig,
    q => not_aux25
  );
  o2_x2_ins : o2_x2
  PORT MAP (
    i0 => reset,
    i1 => not_aux23,
    q => o2_x2_sig
  );
  not_aux26_ins : inv_x2
  PORT MAP (
    i => aux26,
    nq => not_aux26
  );
  not_aux27_ins : an12_x1
  PORT MAP (
    i0 => rtlalc_1(2),
    i1 => not_c_nreg,
    q => not_aux27
  );
  not_aux29_ins : an12_x1
  PORT MAP (
    i0 => rtlalc_1(6),
    i1 => not_c_nreg,
    q => not_aux29
  );
  not_rtlalc_1_8_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(8),
    nq => not_rtlalc_1(8)
  );
  not_rtlalc_1_9_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(9),
    nq => not_rtlalc_1(9)
  );
  not_rtlalc_1_11_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(11),
    nq => not_rtlalc_1(11)
  );
  not_rtlalc_1_12_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(12),
    nq => not_rtlalc_1(12)
  );
  not_aux35_ins : an12_x1
  PORT MAP (
    i0 => rtlalc_1(15),
    i1 => not_c_nreg,
    q => not_aux35
  );
  not_aux37_ins : an12_x1
  PORT MAP (
    i0 => rtlalc_1(18),
    i1 => not_c_nreg,
    q => not_aux37
  );
  not_aux38_ins : an12_x1
  PORT MAP (
    i0 => rtlalc_1(19),
    i1 => not_c_nreg,
    q => not_aux38
  );
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_neuronreg_boog of neuronreg_boog is
  for RTL
    for all: buf_x2 use entity sxlib.buf_x2(vital); end for;
    for all: sff1_x4 use entity sxlib.sff1_x4(vital); end for;
    for all: na3_x1 use entity sxlib.na3_x1(vital); end for;
    for all: on12_x1 use entity sxlib.on12_x1(vital); end for;
    for all: nao22_x1 use entity sxlib.nao22_x1(vital); end for;
    for all: an12_x1 use entity sxlib.an12_x1(vital); end for;
    for all: sff2_x4 use entity sxlib.sff2_x4(vital); end for;
    for all: o2_x2 use entity sxlib.o2_x2(vital); end for;
    for all: no3_x1 use entity sxlib.no3_x1(vital); end for;
    for all: a2_x2 use entity sxlib.a2_x2(vital); end for;
    for all: oa22_x2 use entity sxlib.oa22_x2(vital); end for;
    for all: no2_x1 use entity sxlib.no2_x1(vital); end for;
    for all: na2_x1 use entity sxlib.na2_x1(vital); end for;
    for all: o3_x2 use entity sxlib.o3_x2(vital); end for;
    for all: inv_x2 use entity sxlib.inv_x2(vital); end for;
    for all: ao2o22_x2 use entity sxlib.ao2o22_x2(vital); end for;
    for all: xr2_x1 use entity sxlib.xr2_x1(vital); end for;
    for all: a3_x2 use entity sxlib.a3_x2(vital); end for;
    for all: oa2ao222_x2 use entity sxlib.oa2ao222_x2(vital); end for;
    for all: ao22_x2 use entity sxlib.ao22_x2(vital); end for;
    for all: nxr2_x1 use entity sxlib.nxr2_x1(vital); end for;
    for all: nao2o22_x1 use entity sxlib.nao2o22_x1(vital); end for;
    for all: noa2ao222_x1 use entity sxlib.noa2ao222_x1(vital); end for;
  end for;
end CFG_neuronreg_boog;
