-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY neuronreg_boog IS
PORT(
  clk	: IN STD_LOGIC;
  reset	: IN STD_LOGIC;
  c_reset_reg	: IN STD_LOGIC;
  c_nreg	: IN STD_LOGIC;
  in_nreg_val	: IN STD_LOGIC_VECTOR(12 DOWNTO 0);
  out_nreg_val	: OUT STD_LOGIC_VECTOR(20 DOWNTO 0)
);
END neuronreg_boog;

ARCHITECTURE RTL OF neuronreg_boog IS
  SIGNAL not_reg_nreg	: STD_LOGIC_VECTOR(19 DOWNTO 1);
  SIGNAL not_rtlcarry_0	: STD_LOGIC_VECTOR(15 DOWNTO 1);
  SIGNAL reg_nreg	: STD_LOGIC_VECTOR(20 DOWNTO 0);
  SIGNAL rtlalc_1	: STD_LOGIC_VECTOR(20 DOWNTO 0);
  SIGNAL rtlcarry_0	: STD_LOGIC_VECTOR(19 DOWNTO 1);
  SIGNAL xr2_x1_sig	: STD_LOGIC;
  SIGNAL xr2_x1_9_sig	: STD_LOGIC;
  SIGNAL xr2_x1_8_sig	: STD_LOGIC;
  SIGNAL xr2_x1_7_sig	: STD_LOGIC;
  SIGNAL xr2_x1_6_sig	: STD_LOGIC;
  SIGNAL xr2_x1_5_sig	: STD_LOGIC;
  SIGNAL xr2_x1_4_sig	: STD_LOGIC;
  SIGNAL xr2_x1_3_sig	: STD_LOGIC;
  SIGNAL xr2_x1_2_sig	: STD_LOGIC;
  SIGNAL xr2_x1_19_sig	: STD_LOGIC;
  SIGNAL xr2_x1_18_sig	: STD_LOGIC;
  SIGNAL xr2_x1_17_sig	: STD_LOGIC;
  SIGNAL xr2_x1_16_sig	: STD_LOGIC;
  SIGNAL xr2_x1_15_sig	: STD_LOGIC;
  SIGNAL xr2_x1_14_sig	: STD_LOGIC;
  SIGNAL xr2_x1_13_sig	: STD_LOGIC;
  SIGNAL xr2_x1_12_sig	: STD_LOGIC;
  SIGNAL xr2_x1_11_sig	: STD_LOGIC;
  SIGNAL xr2_x1_10_sig	: STD_LOGIC;
  SIGNAL on12_x1_sig	: STD_LOGIC;
  SIGNAL on12_x1_5_sig	: STD_LOGIC;
  SIGNAL on12_x1_4_sig	: STD_LOGIC;
  SIGNAL on12_x1_3_sig	: STD_LOGIC;
  SIGNAL on12_x1_2_sig	: STD_LOGIC;
  SIGNAL o4_x2_sig	: STD_LOGIC;
  SIGNAL o4_x2_3_sig	: STD_LOGIC;
  SIGNAL o4_x2_2_sig	: STD_LOGIC;
  SIGNAL o3_x2_sig	: STD_LOGIC;
  SIGNAL o2_x2_sig	: STD_LOGIC;
  SIGNAL o2_x2_9_sig	: STD_LOGIC;
  SIGNAL o2_x2_8_sig	: STD_LOGIC;
  SIGNAL o2_x2_7_sig	: STD_LOGIC;
  SIGNAL o2_x2_6_sig	: STD_LOGIC;
  SIGNAL o2_x2_5_sig	: STD_LOGIC;
  SIGNAL o2_x2_4_sig	: STD_LOGIC;
  SIGNAL o2_x2_3_sig	: STD_LOGIC;
  SIGNAL o2_x2_2_sig	: STD_LOGIC;
  SIGNAL not_reset	: STD_LOGIC;
  SIGNAL not_c_reset_reg	: STD_LOGIC;
  SIGNAL not_c_nreg	: STD_LOGIC;
  SIGNAL not_aux98	: STD_LOGIC;
  SIGNAL not_aux94	: STD_LOGIC;
  SIGNAL not_aux90	: STD_LOGIC;
  SIGNAL not_aux9	: STD_LOGIC;
  SIGNAL not_aux86	: STD_LOGIC;
  SIGNAL not_aux78	: STD_LOGIC;
  SIGNAL not_aux72	: STD_LOGIC;
  SIGNAL not_aux67	: STD_LOGIC;
  SIGNAL not_aux59	: STD_LOGIC;
  SIGNAL not_aux58	: STD_LOGIC;
  SIGNAL not_aux54	: STD_LOGIC;
  SIGNAL not_aux53	: STD_LOGIC;
  SIGNAL not_aux49	: STD_LOGIC;
  SIGNAL not_aux48	: STD_LOGIC;
  SIGNAL not_aux43	: STD_LOGIC;
  SIGNAL not_aux4	: STD_LOGIC;
  SIGNAL not_aux38	: STD_LOGIC;
  SIGNAL not_aux33	: STD_LOGIC;
  SIGNAL not_aux3	: STD_LOGIC;
  SIGNAL not_aux29	: STD_LOGIC;
  SIGNAL not_aux28	: STD_LOGIC;
  SIGNAL not_aux20	: STD_LOGIC;
  SIGNAL not_aux19	: STD_LOGIC;
  SIGNAL not_aux14	: STD_LOGIC;
  SIGNAL not_aux115	: STD_LOGIC;
  SIGNAL not_aux114	: STD_LOGIC;
  SIGNAL not_aux112	: STD_LOGIC;
  SIGNAL not_aux111	: STD_LOGIC;
  SIGNAL not_aux103	: STD_LOGIC;
  SIGNAL not_aux102	: STD_LOGIC;
  SIGNAL no4_x1_sig	: STD_LOGIC;
  SIGNAL no4_x1_3_sig	: STD_LOGIC;
  SIGNAL no4_x1_2_sig	: STD_LOGIC;
  SIGNAL no3_x1_sig	: STD_LOGIC;
  SIGNAL no3_x1_2_sig	: STD_LOGIC;
  SIGNAL no2_x1_sig	: STD_LOGIC;
  SIGNAL no2_x1_2_sig	: STD_LOGIC;
  SIGNAL nao22_x1_sig	: STD_LOGIC;
  SIGNAL nao22_x1_9_sig	: STD_LOGIC;
  SIGNAL nao22_x1_8_sig	: STD_LOGIC;
  SIGNAL nao22_x1_7_sig	: STD_LOGIC;
  SIGNAL nao22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao22_x1_34_sig	: STD_LOGIC;
  SIGNAL nao22_x1_33_sig	: STD_LOGIC;
  SIGNAL nao22_x1_32_sig	: STD_LOGIC;
  SIGNAL nao22_x1_31_sig	: STD_LOGIC;
  SIGNAL nao22_x1_30_sig	: STD_LOGIC;
  SIGNAL nao22_x1_2_sig	: STD_LOGIC;
  SIGNAL nao22_x1_29_sig	: STD_LOGIC;
  SIGNAL nao22_x1_28_sig	: STD_LOGIC;
  SIGNAL nao22_x1_27_sig	: STD_LOGIC;
  SIGNAL nao22_x1_26_sig	: STD_LOGIC;
  SIGNAL nao22_x1_25_sig	: STD_LOGIC;
  SIGNAL nao22_x1_24_sig	: STD_LOGIC;
  SIGNAL nao22_x1_23_sig	: STD_LOGIC;
  SIGNAL nao22_x1_22_sig	: STD_LOGIC;
  SIGNAL nao22_x1_21_sig	: STD_LOGIC;
  SIGNAL nao22_x1_20_sig	: STD_LOGIC;
  SIGNAL nao22_x1_19_sig	: STD_LOGIC;
  SIGNAL nao22_x1_18_sig	: STD_LOGIC;
  SIGNAL nao22_x1_17_sig	: STD_LOGIC;
  SIGNAL nao22_x1_16_sig	: STD_LOGIC;
  SIGNAL nao22_x1_15_sig	: STD_LOGIC;
  SIGNAL nao22_x1_14_sig	: STD_LOGIC;
  SIGNAL nao22_x1_13_sig	: STD_LOGIC;
  SIGNAL nao22_x1_12_sig	: STD_LOGIC;
  SIGNAL nao22_x1_11_sig	: STD_LOGIC;
  SIGNAL nao22_x1_10_sig	: STD_LOGIC;
  SIGNAL na4_x1_sig	: STD_LOGIC;
  SIGNAL na4_x1_6_sig	: STD_LOGIC;
  SIGNAL na4_x1_5_sig	: STD_LOGIC;
  SIGNAL na4_x1_4_sig	: STD_LOGIC;
  SIGNAL na4_x1_3_sig	: STD_LOGIC;
  SIGNAL na4_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_sig	: STD_LOGIC;
  SIGNAL na3_x1_9_sig	: STD_LOGIC;
  SIGNAL na3_x1_8_sig	: STD_LOGIC;
  SIGNAL na3_x1_7_sig	: STD_LOGIC;
  SIGNAL na3_x1_6_sig	: STD_LOGIC;
  SIGNAL na3_x1_5_sig	: STD_LOGIC;
  SIGNAL na3_x1_4_sig	: STD_LOGIC;
  SIGNAL na3_x1_3_sig	: STD_LOGIC;
  SIGNAL na3_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_10_sig	: STD_LOGIC;
  SIGNAL na2_x1_sig	: STD_LOGIC;
  SIGNAL na2_x1_9_sig	: STD_LOGIC;
  SIGNAL na2_x1_8_sig	: STD_LOGIC;
  SIGNAL na2_x1_7_sig	: STD_LOGIC;
  SIGNAL na2_x1_6_sig	: STD_LOGIC;
  SIGNAL na2_x1_5_sig	: STD_LOGIC;
  SIGNAL na2_x1_4_sig	: STD_LOGIC;
  SIGNAL na2_x1_3_sig	: STD_LOGIC;
  SIGNAL na2_x1_2_sig	: STD_LOGIC;
  SIGNAL na2_x1_10_sig	: STD_LOGIC;
  SIGNAL inv_x2_sig	: STD_LOGIC;
  SIGNAL inv_x2_9_sig	: STD_LOGIC;
  SIGNAL inv_x2_8_sig	: STD_LOGIC;
  SIGNAL inv_x2_7_sig	: STD_LOGIC;
  SIGNAL inv_x2_6_sig	: STD_LOGIC;
  SIGNAL inv_x2_5_sig	: STD_LOGIC;
  SIGNAL inv_x2_4_sig	: STD_LOGIC;
  SIGNAL inv_x2_3_sig	: STD_LOGIC;
  SIGNAL inv_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_27_sig	: STD_LOGIC;
  SIGNAL inv_x2_26_sig	: STD_LOGIC;
  SIGNAL inv_x2_25_sig	: STD_LOGIC;
  SIGNAL inv_x2_24_sig	: STD_LOGIC;
  SIGNAL inv_x2_23_sig	: STD_LOGIC;
  SIGNAL inv_x2_22_sig	: STD_LOGIC;
  SIGNAL inv_x2_21_sig	: STD_LOGIC;
  SIGNAL inv_x2_20_sig	: STD_LOGIC;
  SIGNAL inv_x2_19_sig	: STD_LOGIC;
  SIGNAL inv_x2_18_sig	: STD_LOGIC;
  SIGNAL inv_x2_17_sig	: STD_LOGIC;
  SIGNAL inv_x2_16_sig	: STD_LOGIC;
  SIGNAL inv_x2_15_sig	: STD_LOGIC;
  SIGNAL inv_x2_14_sig	: STD_LOGIC;
  SIGNAL inv_x2_13_sig	: STD_LOGIC;
  SIGNAL inv_x2_12_sig	: STD_LOGIC;
  SIGNAL inv_x2_11_sig	: STD_LOGIC;
  SIGNAL inv_x2_10_sig	: STD_LOGIC;
  SIGNAL aux4	: STD_LOGIC;
  SIGNAL a4_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_9_sig	: STD_LOGIC;
  SIGNAL a3_x2_8_sig	: STD_LOGIC;
  SIGNAL a3_x2_7_sig	: STD_LOGIC;
  SIGNAL a3_x2_6_sig	: STD_LOGIC;
  SIGNAL a3_x2_5_sig	: STD_LOGIC;
  SIGNAL a3_x2_4_sig	: STD_LOGIC;
  SIGNAL a3_x2_3_sig	: STD_LOGIC;
  SIGNAL a3_x2_2_sig	: STD_LOGIC;
  SIGNAL a3_x2_13_sig	: STD_LOGIC;
  SIGNAL a3_x2_12_sig	: STD_LOGIC;
  SIGNAL a3_x2_11_sig	: STD_LOGIC;
  SIGNAL a3_x2_10_sig	: STD_LOGIC;
  SIGNAL a2_x2_sig	: STD_LOGIC;
  SIGNAL a2_x2_8_sig	: STD_LOGIC;
  SIGNAL a2_x2_7_sig	: STD_LOGIC;
  SIGNAL a2_x2_6_sig	: STD_LOGIC;
  SIGNAL a2_x2_5_sig	: STD_LOGIC;
  SIGNAL a2_x2_4_sig	: STD_LOGIC;
  SIGNAL a2_x2_3_sig	: STD_LOGIC;
  SIGNAL a2_x2_2_sig	: STD_LOGIC;

  COMPONENT buf_x2
  PORT(
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT sff1_x4
  PORT(
  ck	: IN STD_LOGIC;
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT inv_x2
  PORT(
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT on12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT an12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2ao222_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao2o22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT xr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao2o22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

BEGIN
  out_nreg_val_20_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(20),
    q => out_nreg_val(20)
  );
  out_nreg_val_19_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(19),
    q => out_nreg_val(19)
  );
  out_nreg_val_18_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(18),
    q => out_nreg_val(18)
  );
  out_nreg_val_17_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(17),
    q => out_nreg_val(17)
  );
  out_nreg_val_16_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(16),
    q => out_nreg_val(16)
  );
  out_nreg_val_15_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(15),
    q => out_nreg_val(15)
  );
  out_nreg_val_14_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(14),
    q => out_nreg_val(14)
  );
  out_nreg_val_13_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(13),
    q => out_nreg_val(13)
  );
  out_nreg_val_12_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(12),
    q => out_nreg_val(12)
  );
  out_nreg_val_11_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(11),
    q => out_nreg_val(11)
  );
  out_nreg_val_10_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(10),
    q => out_nreg_val(10)
  );
  out_nreg_val_9_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(9),
    q => out_nreg_val(9)
  );
  out_nreg_val_8_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(8),
    q => out_nreg_val(8)
  );
  out_nreg_val_7_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(7),
    q => out_nreg_val(7)
  );
  out_nreg_val_6_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(6),
    q => out_nreg_val(6)
  );
  out_nreg_val_5_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(5),
    q => out_nreg_val(5)
  );
  out_nreg_val_4_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(4),
    q => out_nreg_val(4)
  );
  out_nreg_val_3_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(3),
    q => out_nreg_val(3)
  );
  out_nreg_val_2_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(2),
    q => out_nreg_val(2)
  );
  out_nreg_val_1_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(1),
    q => out_nreg_val(1)
  );
  out_nreg_val_0_ins : buf_x2
  PORT MAP (
    i => rtlalc_1(0),
    q => out_nreg_val(0)
  );
  rtlalc_1_20_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_34_sig,
    q => rtlalc_1(20)
  );
  nao22_x1_34_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_27_sig,
    i2 => not_aux111,
    nq => nao22_x1_34_sig
  );
  inv_x2_27_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(20),
    nq => inv_x2_27_sig
  );
  rtlalc_1_19_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_33_sig,
    q => rtlalc_1(19)
  );
  nao22_x1_33_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_26_sig,
    i2 => not_aux102,
    nq => nao22_x1_33_sig
  );
  inv_x2_26_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(19),
    nq => inv_x2_26_sig
  );
  rtlalc_1_18_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_32_sig,
    q => rtlalc_1(18)
  );
  nao22_x1_32_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_25_sig,
    i2 => not_aux98,
    nq => nao22_x1_32_sig
  );
  inv_x2_25_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(18),
    nq => inv_x2_25_sig
  );
  rtlalc_1_17_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_31_sig,
    q => rtlalc_1(17)
  );
  nao22_x1_31_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_24_sig,
    i2 => not_aux94,
    nq => nao22_x1_31_sig
  );
  inv_x2_24_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(17),
    nq => inv_x2_24_sig
  );
  rtlalc_1_16_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_30_sig,
    q => rtlalc_1(16)
  );
  nao22_x1_30_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_23_sig,
    i2 => not_aux90,
    nq => nao22_x1_30_sig
  );
  inv_x2_23_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(16),
    nq => inv_x2_23_sig
  );
  rtlalc_1_15_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_29_sig,
    q => rtlalc_1(15)
  );
  nao22_x1_29_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_22_sig,
    i2 => not_aux86,
    nq => nao22_x1_29_sig
  );
  inv_x2_22_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(15),
    nq => inv_x2_22_sig
  );
  rtlalc_1_14_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_28_sig,
    q => rtlalc_1(14)
  );
  nao22_x1_28_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_21_sig,
    i2 => not_aux78,
    nq => nao22_x1_28_sig
  );
  inv_x2_21_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(14),
    nq => inv_x2_21_sig
  );
  rtlalc_1_13_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_27_sig,
    q => rtlalc_1(13)
  );
  nao22_x1_27_ins : nao22_x1
  PORT MAP (
    i0 => not_aux115,
    i1 => not_aux112,
    i2 => o4_x2_3_sig,
    nq => nao22_x1_27_sig
  );
  o4_x2_3_ins : o4_x2
  PORT MAP (
    i0 => not_aux4,
    i1 => a2_x2_8_sig,
    i2 => not_aux112,
    i3 => reg_nreg(13),
    q => o4_x2_3_sig
  );
  a2_x2_8_ins : a2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_rtlcarry_0(13),
    q => a2_x2_8_sig
  );
  rtlalc_1_12_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_26_sig,
    q => rtlalc_1(12)
  );
  nao22_x1_26_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_20_sig,
    i2 => not_aux72,
    nq => nao22_x1_26_sig
  );
  inv_x2_20_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(12),
    nq => inv_x2_20_sig
  );
  rtlalc_1_11_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_25_sig,
    q => rtlalc_1(11)
  );
  nao22_x1_25_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_19_sig,
    i2 => not_aux67,
    nq => nao22_x1_25_sig
  );
  inv_x2_19_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(11),
    nq => inv_x2_19_sig
  );
  rtlalc_1_10_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_10_sig,
    q => rtlalc_1(10)
  );
  na3_x1_10_ins : na3_x1
  PORT MAP (
    i0 => not_aux58,
    i1 => on12_x1_5_sig,
    i2 => o2_x2_9_sig,
    nq => na3_x1_10_sig
  );
  on12_x1_5_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(10),
    i1 => not_aux114,
    q => on12_x1_5_sig
  );
  o2_x2_9_ins : o2_x2
  PORT MAP (
    i0 => not_aux54,
    i1 => na4_x1_6_sig,
    q => o2_x2_9_sig
  );
  na4_x1_6_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => c_nreg,
    i3 => reg_nreg(10),
    nq => na4_x1_6_sig
  );
  rtlalc_1_9_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_9_sig,
    q => rtlalc_1(9)
  );
  na3_x1_9_ins : na3_x1
  PORT MAP (
    i0 => not_aux53,
    i1 => on12_x1_4_sig,
    i2 => o2_x2_8_sig,
    nq => na3_x1_9_sig
  );
  on12_x1_4_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(9),
    i1 => not_aux114,
    q => on12_x1_4_sig
  );
  o2_x2_8_ins : o2_x2
  PORT MAP (
    i0 => not_aux49,
    i1 => na4_x1_5_sig,
    q => o2_x2_8_sig
  );
  na4_x1_5_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => c_nreg,
    i3 => reg_nreg(9),
    nq => na4_x1_5_sig
  );
  rtlalc_1_8_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_24_sig,
    q => rtlalc_1(8)
  );
  nao22_x1_24_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_18_sig,
    i2 => not_aux48,
    nq => nao22_x1_24_sig
  );
  inv_x2_18_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(8),
    nq => inv_x2_18_sig
  );
  rtlalc_1_7_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_23_sig,
    q => rtlalc_1(7)
  );
  nao22_x1_23_ins : nao22_x1
  PORT MAP (
    i0 => o2_x2_7_sig,
    i1 => inv_x2_17_sig,
    i2 => not_aux43,
    nq => nao22_x1_23_sig
  );
  o2_x2_7_ins : o2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => o2_x2_7_sig
  );
  inv_x2_17_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(7),
    nq => inv_x2_17_sig
  );
  rtlalc_1_6_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_22_sig,
    q => rtlalc_1(6)
  );
  nao22_x1_22_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_16_sig,
    i2 => not_aux38,
    nq => nao22_x1_22_sig
  );
  inv_x2_16_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(6),
    nq => inv_x2_16_sig
  );
  rtlalc_1_5_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_8_sig,
    q => rtlalc_1(5)
  );
  na3_x1_8_ins : na3_x1
  PORT MAP (
    i0 => not_aux33,
    i1 => on12_x1_3_sig,
    i2 => o2_x2_6_sig,
    nq => na3_x1_8_sig
  );
  on12_x1_3_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(5),
    i1 => not_aux114,
    q => on12_x1_3_sig
  );
  o2_x2_6_ins : o2_x2
  PORT MAP (
    i0 => not_aux29,
    i1 => na4_x1_4_sig,
    q => o2_x2_6_sig
  );
  na4_x1_4_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => c_nreg,
    i3 => reg_nreg(5),
    nq => na4_x1_4_sig
  );
  rtlalc_1_4_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_21_sig,
    q => rtlalc_1(4)
  );
  nao22_x1_21_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_15_sig,
    i2 => not_aux28,
    nq => nao22_x1_21_sig
  );
  inv_x2_15_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(4),
    nq => inv_x2_15_sig
  );
  rtlalc_1_3_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_20_sig,
    q => rtlalc_1(3)
  );
  nao22_x1_20_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_14_sig,
    i2 => not_aux19,
    nq => nao22_x1_20_sig
  );
  inv_x2_14_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(3),
    nq => inv_x2_14_sig
  );
  rtlalc_1_2_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_19_sig,
    q => rtlalc_1(2)
  );
  nao22_x1_19_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_13_sig,
    i2 => not_aux14,
    nq => nao22_x1_19_sig
  );
  inv_x2_13_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(2),
    nq => inv_x2_13_sig
  );
  rtlalc_1_1_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_18_sig,
    q => rtlalc_1(1)
  );
  nao22_x1_18_ins : nao22_x1
  PORT MAP (
    i0 => o2_x2_5_sig,
    i1 => inv_x2_12_sig,
    i2 => not_aux9,
    nq => nao22_x1_18_sig
  );
  o2_x2_5_ins : o2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => o2_x2_5_sig
  );
  inv_x2_12_ins : inv_x2
  PORT MAP (
    i => rtlalc_1(1),
    nq => inv_x2_12_sig
  );
  rtlalc_1_0_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na3_x1_6_sig,
    q => rtlalc_1(0)
  );
  na3_x1_6_ins : na3_x1
  PORT MAP (
    i0 => not_aux3,
    i1 => on12_x1_2_sig,
    i2 => na3_x1_7_sig,
    nq => na3_x1_6_sig
  );
  on12_x1_2_ins : on12_x1
  PORT MAP (
    i0 => rtlalc_1(0),
    i1 => not_aux114,
    q => on12_x1_2_sig
  );
  na3_x1_7_ins : na3_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => no3_x1_2_sig,
    i2 => reg_nreg(0),
    nq => na3_x1_7_sig
  );
  no3_x1_2_ins : no3_x1
  PORT MAP (
    i0 => reset,
    i1 => in_nreg_val(0),
    i2 => c_reset_reg,
    nq => no3_x1_2_sig
  );
  reg_nreg_20_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_17_sig,
    q => reg_nreg(20)
  );
  nao22_x1_17_ins : nao22_x1
  PORT MAP (
    i0 => o2_x2_4_sig,
    i1 => inv_x2_11_sig,
    i2 => not_aux111,
    nq => nao22_x1_17_sig
  );
  o2_x2_4_ins : o2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => o2_x2_4_sig
  );
  inv_x2_11_ins : inv_x2
  PORT MAP (
    i => reg_nreg(20),
    nq => inv_x2_11_sig
  );
  reg_nreg_19_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_16_sig,
    q => reg_nreg(19)
  );
  nao22_x1_16_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(19),
    i2 => not_aux102,
    nq => nao22_x1_16_sig
  );
  reg_nreg_18_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_15_sig,
    q => reg_nreg(18)
  );
  nao22_x1_15_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(18),
    i2 => not_aux98,
    nq => nao22_x1_15_sig
  );
  reg_nreg_17_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_14_sig,
    q => reg_nreg(17)
  );
  nao22_x1_14_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(17),
    i2 => not_aux94,
    nq => nao22_x1_14_sig
  );
  reg_nreg_16_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_13_sig,
    q => reg_nreg(16)
  );
  nao22_x1_13_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(16),
    i2 => not_aux90,
    nq => nao22_x1_13_sig
  );
  reg_nreg_15_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_12_sig,
    q => reg_nreg(15)
  );
  nao22_x1_12_ins : nao22_x1
  PORT MAP (
    i0 => o2_x2_3_sig,
    i1 => inv_x2_10_sig,
    i2 => not_aux86,
    nq => nao22_x1_12_sig
  );
  o2_x2_3_ins : o2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => o2_x2_3_sig
  );
  inv_x2_10_ins : inv_x2
  PORT MAP (
    i => reg_nreg(15),
    nq => inv_x2_10_sig
  );
  reg_nreg_14_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_11_sig,
    q => reg_nreg(14)
  );
  nao22_x1_11_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(14),
    i2 => not_aux78,
    nq => nao22_x1_11_sig
  );
  reg_nreg_13_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_10_sig,
    q => reg_nreg(13)
  );
  nao22_x1_10_ins : nao22_x1
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => na4_x1_3_sig,
    i2 => not_aux115,
    nq => nao22_x1_10_sig
  );
  na4_x1_3_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => c_nreg,
    i3 => not_reg_nreg(13),
    nq => na4_x1_3_sig
  );
  reg_nreg_12_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_9_sig,
    q => reg_nreg(12)
  );
  nao22_x1_9_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(12),
    i2 => not_aux72,
    nq => nao22_x1_9_sig
  );
  reg_nreg_11_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_8_sig,
    q => reg_nreg(11)
  );
  nao22_x1_8_ins : nao22_x1
  PORT MAP (
    i0 => o2_x2_2_sig,
    i1 => not_reg_nreg(11),
    i2 => not_aux67,
    nq => nao22_x1_8_sig
  );
  o2_x2_2_ins : o2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => o2_x2_2_sig
  );
  reg_nreg_10_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_9_sig,
    q => reg_nreg(10)
  );
  na2_x1_9_ins : na2_x1
  PORT MAP (
    i0 => not_aux58,
    i1 => na3_x1_5_sig,
    nq => na2_x1_9_sig
  );
  na3_x1_5_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_10_sig,
    i1 => reg_nreg(10),
    i2 => aux4,
    nq => na3_x1_5_sig
  );
  na2_x1_10_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux54,
    nq => na2_x1_10_sig
  );
  reg_nreg_9_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_7_sig,
    q => reg_nreg(9)
  );
  na2_x1_7_ins : na2_x1
  PORT MAP (
    i0 => not_aux53,
    i1 => na3_x1_4_sig,
    nq => na2_x1_7_sig
  );
  na3_x1_4_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_8_sig,
    i1 => reg_nreg(9),
    i2 => aux4,
    nq => na3_x1_4_sig
  );
  na2_x1_8_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux49,
    nq => na2_x1_8_sig
  );
  reg_nreg_8_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_7_sig,
    q => reg_nreg(8)
  );
  nao22_x1_7_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(8),
    i2 => not_aux48,
    nq => nao22_x1_7_sig
  );
  reg_nreg_7_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_6_sig,
    q => reg_nreg(7)
  );
  nao22_x1_6_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(7),
    i2 => not_aux43,
    nq => nao22_x1_6_sig
  );
  reg_nreg_6_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_5_sig,
    q => reg_nreg(6)
  );
  nao22_x1_5_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_9_sig,
    i2 => not_aux38,
    nq => nao22_x1_5_sig
  );
  inv_x2_9_ins : inv_x2
  PORT MAP (
    i => reg_nreg(6),
    nq => inv_x2_9_sig
  );
  reg_nreg_5_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_5_sig,
    q => reg_nreg(5)
  );
  na2_x1_5_ins : na2_x1
  PORT MAP (
    i0 => not_aux33,
    i1 => na3_x1_3_sig,
    nq => na2_x1_5_sig
  );
  na3_x1_3_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_6_sig,
    i1 => reg_nreg(5),
    i2 => aux4,
    nq => na3_x1_3_sig
  );
  na2_x1_6_ins : na2_x1
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux29,
    nq => na2_x1_6_sig
  );
  reg_nreg_4_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_4_sig,
    q => reg_nreg(4)
  );
  nao22_x1_4_ins : nao22_x1
  PORT MAP (
    i0 => o2_x2_sig,
    i1 => not_reg_nreg(4),
    i2 => not_aux28,
    nq => nao22_x1_4_sig
  );
  o2_x2_ins : o2_x2
  PORT MAP (
    i0 => c_nreg,
    i1 => not_aux4,
    q => o2_x2_sig
  );
  reg_nreg_3_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_3_sig,
    q => reg_nreg(3)
  );
  nao22_x1_3_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => inv_x2_8_sig,
    i2 => not_aux19,
    nq => nao22_x1_3_sig
  );
  inv_x2_8_ins : inv_x2
  PORT MAP (
    i => reg_nreg(3),
    nq => inv_x2_8_sig
  );
  reg_nreg_2_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_2_sig,
    q => reg_nreg(2)
  );
  nao22_x1_2_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(2),
    i2 => not_aux14,
    nq => nao22_x1_2_sig
  );
  reg_nreg_1_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => nao22_x1_sig,
    q => reg_nreg(1)
  );
  nao22_x1_ins : nao22_x1
  PORT MAP (
    i0 => not_aux114,
    i1 => not_reg_nreg(1),
    i2 => not_aux9,
    nq => nao22_x1_sig
  );
  reg_nreg_0_ins : sff1_x4
  PORT MAP (
    ck => clk,
    i => na2_x1_3_sig,
    q => reg_nreg(0)
  );
  na2_x1_3_ins : na2_x1
  PORT MAP (
    i0 => not_aux3,
    i1 => na3_x1_2_sig,
    nq => na2_x1_3_sig
  );
  na3_x1_2_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_4_sig,
    i1 => reg_nreg(0),
    i2 => aux4,
    nq => na3_x1_2_sig
  );
  na2_x1_4_ins : na2_x1
  PORT MAP (
    i0 => in_nreg_val(0),
    i1 => c_nreg,
    nq => na2_x1_4_sig
  );
  rtlcarry_0_19_ins : an12_x1
  PORT MAP (
    i0 => not_reg_nreg(18),
    i1 => rtlcarry_0(18),
    q => rtlcarry_0(19)
  );
  rtlcarry_0_18_ins : an12_x1
  PORT MAP (
    i0 => not_reg_nreg(17),
    i1 => rtlcarry_0(17),
    q => rtlcarry_0(18)
  );
  rtlcarry_0_17_ins : an12_x1
  PORT MAP (
    i0 => not_reg_nreg(16),
    i1 => rtlcarry_0(16),
    q => rtlcarry_0(17)
  );
  rtlcarry_0_16_ins : an12_x1
  PORT MAP (
    i0 => not_rtlcarry_0(15),
    i1 => reg_nreg(15),
    q => rtlcarry_0(16)
  );
  rtlcarry_0_14_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => not_reg_nreg(13),
    nq => rtlcarry_0(14)
  );
  rtlcarry_0_12_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(11),
    i1 => in_nreg_val(11),
    i2 => in_nreg_val(11),
    i3 => reg_nreg(11),
    i4 => rtlcarry_0(11),
    q => rtlcarry_0(12)
  );
  rtlcarry_0_11_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_7_sig,
    i1 => a2_x2_7_sig,
    i2 => not_rtlcarry_0(10),
    i3 => not_reg_nreg(10),
    nq => rtlcarry_0(11)
  );
  inv_x2_7_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(10),
    nq => inv_x2_7_sig
  );
  a2_x2_7_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(10),
    i1 => not_reg_nreg(10),
    q => a2_x2_7_sig
  );
  rtlcarry_0_10_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(9),
    i1 => in_nreg_val(9),
    i2 => in_nreg_val(9),
    i3 => reg_nreg(9),
    i4 => rtlcarry_0(9),
    q => rtlcarry_0(10)
  );
  rtlcarry_0_9_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_6_sig,
    i1 => a2_x2_6_sig,
    i2 => not_rtlcarry_0(8),
    i3 => not_reg_nreg(8),
    nq => rtlcarry_0(9)
  );
  inv_x2_6_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(8),
    nq => inv_x2_6_sig
  );
  a2_x2_6_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(8),
    i1 => not_reg_nreg(8),
    q => a2_x2_6_sig
  );
  rtlcarry_0_8_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_5_sig,
    i1 => a2_x2_5_sig,
    i2 => not_rtlcarry_0(7),
    i3 => not_reg_nreg(7),
    nq => rtlcarry_0(8)
  );
  inv_x2_5_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(7),
    nq => inv_x2_5_sig
  );
  a2_x2_5_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(7),
    i1 => not_reg_nreg(7),
    q => a2_x2_5_sig
  );
  rtlcarry_0_7_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(6),
    i1 => in_nreg_val(6),
    i2 => in_nreg_val(6),
    i3 => reg_nreg(6),
    i4 => rtlcarry_0(6),
    q => rtlcarry_0(7)
  );
  rtlcarry_0_6_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_4_sig,
    i1 => a2_x2_4_sig,
    i2 => not_rtlcarry_0(5),
    i3 => not_reg_nreg(5),
    nq => rtlcarry_0(6)
  );
  inv_x2_4_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(5),
    nq => inv_x2_4_sig
  );
  a2_x2_4_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(5),
    i1 => not_reg_nreg(5),
    q => a2_x2_4_sig
  );
  rtlcarry_0_5_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(4),
    i1 => in_nreg_val(4),
    i2 => in_nreg_val(4),
    i3 => reg_nreg(4),
    i4 => rtlcarry_0(4),
    q => rtlcarry_0(5)
  );
  rtlcarry_0_4_ins : oa2ao222_x2
  PORT MAP (
    i0 => reg_nreg(3),
    i1 => in_nreg_val(3),
    i2 => in_nreg_val(3),
    i3 => reg_nreg(3),
    i4 => rtlcarry_0(3),
    q => rtlcarry_0(4)
  );
  rtlcarry_0_3_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_3_sig,
    i1 => a2_x2_3_sig,
    i2 => not_rtlcarry_0(2),
    i3 => not_reg_nreg(2),
    nq => rtlcarry_0(3)
  );
  inv_x2_3_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(2),
    nq => inv_x2_3_sig
  );
  a2_x2_3_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(2),
    i1 => not_reg_nreg(2),
    q => a2_x2_3_sig
  );
  rtlcarry_0_2_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_2_sig,
    i1 => a2_x2_2_sig,
    i2 => not_reg_nreg(1),
    i3 => not_rtlcarry_0(1),
    nq => rtlcarry_0(2)
  );
  inv_x2_2_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(1),
    nq => inv_x2_2_sig
  );
  a2_x2_2_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(1),
    i1 => not_reg_nreg(1),
    q => a2_x2_2_sig
  );
  rtlcarry_0_1_ins : a2_x2
  PORT MAP (
    i0 => in_nreg_val(0),
    i1 => reg_nreg(0),
    q => rtlcarry_0(1)
  );
  aux4_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => c_reset_reg,
    nq => aux4
  );
  not_c_nreg_ins : inv_x2
  PORT MAP (
    i => c_nreg,
    nq => not_c_nreg
  );
  not_c_reset_reg_ins : inv_x2
  PORT MAP (
    i => c_reset_reg,
    nq => not_c_reset_reg
  );
  not_reset_ins : inv_x2
  PORT MAP (
    i => reset,
    nq => not_reset
  );
  not_aux4_ins : inv_x2
  PORT MAP (
    i => aux4,
    nq => not_aux4
  );
  not_aux3_ins : on12_x1
  PORT MAP (
    i0 => a4_x2_sig,
    i1 => reg_nreg(0),
    q => not_aux3
  );
  a4_x2_ins : a4_x2
  PORT MAP (
    i0 => not_reset,
    i1 => in_nreg_val(0),
    i2 => c_nreg,
    i3 => not_c_reset_reg,
    q => a4_x2_sig
  );
  not_rtlcarry_0_1_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(1),
    nq => not_rtlcarry_0(1)
  );
  not_reg_nreg_1_ins : inv_x2
  PORT MAP (
    i => reg_nreg(1),
    nq => not_reg_nreg(1)
  );
  not_aux9_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_13_sig,
    i1 => xr2_x1_18_sig,
    nq => not_aux9
  );
  a3_x2_13_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_13_sig
  );
  xr2_x1_18_ins : xr2_x1
  PORT MAP (
    i0 => xr2_x1_19_sig,
    i1 => reg_nreg(1),
    q => xr2_x1_18_sig
  );
  xr2_x1_19_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(1),
    i1 => in_nreg_val(1),
    q => xr2_x1_19_sig
  );
  not_aux114_ins : o3_x2
  PORT MAP (
    i0 => reset,
    i1 => c_reset_reg,
    i2 => c_nreg,
    q => not_aux114
  );
  not_rtlcarry_0_2_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(2),
    nq => not_rtlcarry_0(2)
  );
  not_reg_nreg_2_ins : inv_x2
  PORT MAP (
    i => reg_nreg(2),
    nq => not_reg_nreg(2)
  );
  not_aux14_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_12_sig,
    i1 => xr2_x1_16_sig,
    nq => not_aux14
  );
  a3_x2_12_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_12_sig
  );
  xr2_x1_16_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(2),
    i1 => xr2_x1_17_sig,
    q => xr2_x1_16_sig
  );
  xr2_x1_17_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(2),
    i1 => in_nreg_val(2),
    q => xr2_x1_17_sig
  );
  not_aux19_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_11_sig,
    i1 => xr2_x1_14_sig,
    nq => not_aux19
  );
  a3_x2_11_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_11_sig
  );
  xr2_x1_14_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(3),
    i1 => xr2_x1_15_sig,
    q => xr2_x1_14_sig
  );
  xr2_x1_15_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(3),
    i1 => in_nreg_val(3),
    q => xr2_x1_15_sig
  );
  not_aux20_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(4),
    i1 => in_nreg_val(4),
    q => not_aux20
  );
  not_reg_nreg_4_ins : inv_x2
  PORT MAP (
    i => reg_nreg(4),
    nq => not_reg_nreg(4)
  );
  not_aux28_ins : oa22_x2
  PORT MAP (
    i0 => o4_x2_2_sig,
    i1 => na4_x1_2_sig,
    i2 => not_c_nreg,
    q => not_aux28
  );
  o4_x2_2_ins : o4_x2
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => not_aux20,
    i3 => not_reg_nreg(4),
    q => o4_x2_2_sig
  );
  na4_x1_2_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => not_aux20,
    i3 => not_reg_nreg(4),
    nq => na4_x1_2_sig
  );
  not_rtlcarry_0_5_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(5),
    nq => not_rtlcarry_0(5)
  );
  not_aux29_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(5),
    i1 => in_nreg_val(5),
    q => not_aux29
  );
  not_reg_nreg_5_ins : inv_x2
  PORT MAP (
    i => reg_nreg(5),
    nq => not_reg_nreg(5)
  );
  not_aux33_ins : na2_x1
  PORT MAP (
    i0 => not_aux29,
    i1 => no4_x1_3_sig,
    nq => not_aux33
  );
  no4_x1_3_ins : no4_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reset,
    i2 => reg_nreg(5),
    i3 => c_reset_reg,
    nq => no4_x1_3_sig
  );
  not_aux38_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_10_sig,
    i1 => xr2_x1_12_sig,
    nq => not_aux38
  );
  a3_x2_10_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_10_sig
  );
  xr2_x1_12_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(6),
    i1 => xr2_x1_13_sig,
    q => xr2_x1_12_sig
  );
  xr2_x1_13_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(6),
    i1 => in_nreg_val(6),
    q => xr2_x1_13_sig
  );
  not_rtlcarry_0_7_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(7),
    nq => not_rtlcarry_0(7)
  );
  not_reg_nreg_7_ins : inv_x2
  PORT MAP (
    i => reg_nreg(7),
    nq => not_reg_nreg(7)
  );
  not_aux43_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_9_sig,
    i1 => xr2_x1_10_sig,
    nq => not_aux43
  );
  a3_x2_9_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_9_sig
  );
  xr2_x1_10_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(7),
    i1 => xr2_x1_11_sig,
    q => xr2_x1_10_sig
  );
  xr2_x1_11_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(7),
    i1 => in_nreg_val(7),
    q => xr2_x1_11_sig
  );
  not_reg_nreg_8_ins : inv_x2
  PORT MAP (
    i => reg_nreg(8),
    nq => not_reg_nreg(8)
  );
  not_rtlcarry_0_8_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(8),
    nq => not_rtlcarry_0(8)
  );
  not_aux48_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_8_sig,
    i1 => xr2_x1_8_sig,
    nq => not_aux48
  );
  a3_x2_8_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_8_sig
  );
  xr2_x1_8_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(8),
    i1 => xr2_x1_9_sig,
    q => xr2_x1_8_sig
  );
  xr2_x1_9_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(8),
    i1 => in_nreg_val(8),
    q => xr2_x1_9_sig
  );
  not_aux49_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(9),
    i1 => in_nreg_val(9),
    q => not_aux49
  );
  not_aux53_ins : na2_x1
  PORT MAP (
    i0 => not_aux49,
    i1 => no4_x1_2_sig,
    nq => not_aux53
  );
  no4_x1_2_ins : no4_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reset,
    i2 => reg_nreg(9),
    i3 => c_reset_reg,
    nq => no4_x1_2_sig
  );
  not_rtlcarry_0_10_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(10),
    nq => not_rtlcarry_0(10)
  );
  not_aux54_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(10),
    i1 => in_nreg_val(10),
    q => not_aux54
  );
  not_reg_nreg_10_ins : inv_x2
  PORT MAP (
    i => reg_nreg(10),
    nq => not_reg_nreg(10)
  );
  not_aux58_ins : na2_x1
  PORT MAP (
    i0 => not_aux54,
    i1 => no4_x1_sig,
    nq => not_aux58
  );
  no4_x1_ins : no4_x1
  PORT MAP (
    i0 => not_c_nreg,
    i1 => reset,
    i2 => reg_nreg(10),
    i3 => c_reset_reg,
    nq => no4_x1_sig
  );
  not_aux59_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(11),
    i1 => in_nreg_val(11),
    q => not_aux59
  );
  not_reg_nreg_11_ins : inv_x2
  PORT MAP (
    i => reg_nreg(11),
    nq => not_reg_nreg(11)
  );
  not_aux67_ins : oa22_x2
  PORT MAP (
    i0 => o4_x2_sig,
    i1 => na4_x1_sig,
    i2 => not_c_nreg,
    q => not_aux67
  );
  o4_x2_ins : o4_x2
  PORT MAP (
    i0 => c_reset_reg,
    i1 => reset,
    i2 => not_aux59,
    i3 => not_reg_nreg(11),
    q => o4_x2_sig
  );
  na4_x1_ins : na4_x1
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => not_aux59,
    i3 => not_reg_nreg(11),
    nq => na4_x1_sig
  );
  not_rtlcarry_0_12_ins : inv_x2
  PORT MAP (
    i => rtlcarry_0(12),
    nq => not_rtlcarry_0(12)
  );
  not_reg_nreg_12_ins : inv_x2
  PORT MAP (
    i => reg_nreg(12),
    nq => not_reg_nreg(12)
  );
  not_aux72_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_7_sig,
    i1 => xr2_x1_6_sig,
    nq => not_aux72
  );
  a3_x2_7_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_7_sig
  );
  xr2_x1_6_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(12),
    i1 => xr2_x1_7_sig,
    q => xr2_x1_6_sig
  );
  xr2_x1_7_ins : xr2_x1
  PORT MAP (
    i0 => reg_nreg(12),
    i1 => in_nreg_val(12),
    q => xr2_x1_7_sig
  );
  not_rtlcarry_0_13_ins : ao2o22_x2
  PORT MAP (
    i0 => inv_x2_sig,
    i1 => a2_x2_sig,
    i2 => not_rtlcarry_0(12),
    i3 => not_reg_nreg(12),
    q => not_rtlcarry_0(13)
  );
  inv_x2_ins : inv_x2
  PORT MAP (
    i => in_nreg_val(12),
    nq => inv_x2_sig
  );
  a2_x2_ins : a2_x2
  PORT MAP (
    i0 => not_rtlcarry_0(12),
    i1 => not_reg_nreg(12),
    q => a2_x2_sig
  );
  not_reg_nreg_13_ins : inv_x2
  PORT MAP (
    i => reg_nreg(13),
    nq => not_reg_nreg(13)
  );
  not_aux115_ins : o3_x2
  PORT MAP (
    i0 => not_aux4,
    i1 => not_reg_nreg(13),
    i2 => no2_x1_2_sig,
    q => not_aux115
  );
  no2_x1_2_ins : no2_x1
  PORT MAP (
    i0 => not_rtlcarry_0(13),
    i1 => not_c_nreg,
    nq => no2_x1_2_sig
  );
  not_reg_nreg_14_ins : inv_x2
  PORT MAP (
    i => reg_nreg(14),
    nq => not_reg_nreg(14)
  );
  not_aux78_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_6_sig,
    i1 => xr2_x1_5_sig,
    nq => not_aux78
  );
  a3_x2_6_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_6_sig
  );
  xr2_x1_5_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(14),
    i1 => reg_nreg(14),
    q => xr2_x1_5_sig
  );
  not_rtlcarry_0_15_ins : on12_x1
  PORT MAP (
    i0 => rtlcarry_0(14),
    i1 => not_reg_nreg(14),
    q => not_rtlcarry_0(15)
  );
  not_aux86_ins : oa22_x2
  PORT MAP (
    i0 => o3_x2_sig,
    i1 => na3_x1_sig,
    i2 => not_c_nreg,
    q => not_aux86
  );
  o3_x2_ins : o3_x2
  PORT MAP (
    i0 => na2_x1_2_sig,
    i1 => not_rtlcarry_0(15),
    i2 => reg_nreg(15),
    q => o3_x2_sig
  );
  na2_x1_2_ins : na2_x1
  PORT MAP (
    i0 => not_reset,
    i1 => not_c_reset_reg,
    nq => na2_x1_2_sig
  );
  na3_x1_ins : na3_x1
  PORT MAP (
    i0 => no2_x1_sig,
    i1 => not_rtlcarry_0(15),
    i2 => reg_nreg(15),
    nq => na3_x1_sig
  );
  no2_x1_ins : no2_x1
  PORT MAP (
    i0 => reset,
    i1 => c_reset_reg,
    nq => no2_x1_sig
  );
  not_reg_nreg_16_ins : inv_x2
  PORT MAP (
    i => reg_nreg(16),
    nq => not_reg_nreg(16)
  );
  not_aux90_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_5_sig,
    i1 => xr2_x1_4_sig,
    nq => not_aux90
  );
  a3_x2_5_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_5_sig
  );
  xr2_x1_4_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(16),
    i1 => reg_nreg(16),
    q => xr2_x1_4_sig
  );
  not_reg_nreg_17_ins : inv_x2
  PORT MAP (
    i => reg_nreg(17),
    nq => not_reg_nreg(17)
  );
  not_aux94_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_4_sig,
    i1 => xr2_x1_3_sig,
    nq => not_aux94
  );
  a3_x2_4_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_4_sig
  );
  xr2_x1_3_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(17),
    i1 => reg_nreg(17),
    q => xr2_x1_3_sig
  );
  not_reg_nreg_18_ins : inv_x2
  PORT MAP (
    i => reg_nreg(18),
    nq => not_reg_nreg(18)
  );
  not_aux98_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_3_sig,
    i1 => xr2_x1_2_sig,
    nq => not_aux98
  );
  a3_x2_3_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_3_sig
  );
  xr2_x1_2_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(18),
    i1 => reg_nreg(18),
    q => xr2_x1_2_sig
  );
  not_reg_nreg_19_ins : inv_x2
  PORT MAP (
    i => reg_nreg(19),
    nq => not_reg_nreg(19)
  );
  not_aux102_ins : na2_x1
  PORT MAP (
    i0 => a3_x2_2_sig,
    i1 => xr2_x1_sig,
    nq => not_aux102
  );
  a3_x2_2_ins : a3_x2
  PORT MAP (
    i0 => not_reset,
    i1 => c_nreg,
    i2 => not_c_reset_reg,
    q => a3_x2_2_sig
  );
  xr2_x1_ins : xr2_x1
  PORT MAP (
    i0 => rtlcarry_0(19),
    i1 => reg_nreg(19),
    q => xr2_x1_sig
  );
  not_aux103_ins : an12_x1
  PORT MAP (
    i0 => not_reg_nreg(19),
    i1 => rtlcarry_0(19),
    q => not_aux103
  );
  not_aux111_ins : oa22_x2
  PORT MAP (
    i0 => on12_x1_sig,
    i1 => na2_x1_sig,
    i2 => not_c_nreg,
    q => not_aux111
  );
  on12_x1_ins : on12_x1
  PORT MAP (
    i0 => a3_x2_sig,
    i1 => reg_nreg(20),
    q => on12_x1_sig
  );
  a3_x2_ins : a3_x2
  PORT MAP (
    i0 => not_c_reset_reg,
    i1 => not_reset,
    i2 => not_aux103,
    q => a3_x2_sig
  );
  na2_x1_ins : na2_x1
  PORT MAP (
    i0 => no3_x1_sig,
    i1 => reg_nreg(20),
    nq => na2_x1_sig
  );
  no3_x1_ins : no3_x1
  PORT MAP (
    i0 => reset,
    i1 => not_aux103,
    i2 => c_reset_reg,
    nq => no3_x1_sig
  );
  not_aux112_ins : an12_x1
  PORT MAP (
    i0 => rtlalc_1(13),
    i1 => not_c_nreg,
    q => not_aux112
  );
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_neuronreg_boog of neuronreg_boog is
  for RTL
    for all: buf_x2 use entity sxlib.buf_x2(vital); end for;
    for all: sff1_x4 use entity sxlib.sff1_x4(vital); end for;
    for all: nao22_x1 use entity sxlib.nao22_x1(vital); end for;
    for all: inv_x2 use entity sxlib.inv_x2(vital); end for;
    for all: o4_x2 use entity sxlib.o4_x2(vital); end for;
    for all: a2_x2 use entity sxlib.a2_x2(vital); end for;
    for all: na3_x1 use entity sxlib.na3_x1(vital); end for;
    for all: on12_x1 use entity sxlib.on12_x1(vital); end for;
    for all: o2_x2 use entity sxlib.o2_x2(vital); end for;
    for all: na4_x1 use entity sxlib.na4_x1(vital); end for;
    for all: no3_x1 use entity sxlib.no3_x1(vital); end for;
    for all: na2_x1 use entity sxlib.na2_x1(vital); end for;
    for all: an12_x1 use entity sxlib.an12_x1(vital); end for;
    for all: no2_x1 use entity sxlib.no2_x1(vital); end for;
    for all: oa2ao222_x2 use entity sxlib.oa2ao222_x2(vital); end for;
    for all: nao2o22_x1 use entity sxlib.nao2o22_x1(vital); end for;
    for all: a4_x2 use entity sxlib.a4_x2(vital); end for;
    for all: a3_x2 use entity sxlib.a3_x2(vital); end for;
    for all: xr2_x1 use entity sxlib.xr2_x1(vital); end for;
    for all: o3_x2 use entity sxlib.o3_x2(vital); end for;
    for all: oa22_x2 use entity sxlib.oa22_x2(vital); end for;
    for all: no4_x1 use entity sxlib.no4_x1(vital); end for;
    for all: ao2o22_x2 use entity sxlib.ao2o22_x2(vital); end for;
  end for;
end CFG_neuronreg_boog;
