-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ram_boog IS
PORT(
  in_ram_input_index	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
  out_data_ram	: OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
);
END ram_boog;

ARCHITECTURE RTL OF ram_boog IS
  SIGNAL not_in_ram_input_index	: STD_LOGIC_VECTOR(7 DOWNTO 0);
  SIGNAL xr2_x1_sig	: STD_LOGIC;
  SIGNAL on12_x1_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_4_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_3_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_2_sig	: STD_LOGIC;
  SIGNAL oa2a22_x2_sig	: STD_LOGIC;
  SIGNAL oa2a22_x2_3_sig	: STD_LOGIC;
  SIGNAL oa2a22_x2_2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_9_sig	: STD_LOGIC;
  SIGNAL oa22_x2_8_sig	: STD_LOGIC;
  SIGNAL oa22_x2_7_sig	: STD_LOGIC;
  SIGNAL oa22_x2_6_sig	: STD_LOGIC;
  SIGNAL oa22_x2_5_sig	: STD_LOGIC;
  SIGNAL oa22_x2_4_sig	: STD_LOGIC;
  SIGNAL oa22_x2_3_sig	: STD_LOGIC;
  SIGNAL oa22_x2_2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_10_sig	: STD_LOGIC;
  SIGNAL o4_x2_sig	: STD_LOGIC;
  SIGNAL o3_x2_sig	: STD_LOGIC;
  SIGNAL o3_x2_6_sig	: STD_LOGIC;
  SIGNAL o3_x2_5_sig	: STD_LOGIC;
  SIGNAL o3_x2_4_sig	: STD_LOGIC;
  SIGNAL o3_x2_3_sig	: STD_LOGIC;
  SIGNAL o3_x2_2_sig	: STD_LOGIC;
  SIGNAL o2_x2_sig	: STD_LOGIC;
  SIGNAL not_aux99	: STD_LOGIC;
  SIGNAL not_aux93	: STD_LOGIC;
  SIGNAL not_aux90	: STD_LOGIC;
  SIGNAL not_aux9	: STD_LOGIC;
  SIGNAL not_aux87	: STD_LOGIC;
  SIGNAL not_aux86	: STD_LOGIC;
  SIGNAL not_aux85	: STD_LOGIC;
  SIGNAL not_aux84	: STD_LOGIC;
  SIGNAL not_aux82	: STD_LOGIC;
  SIGNAL not_aux80	: STD_LOGIC;
  SIGNAL not_aux8	: STD_LOGIC;
  SIGNAL not_aux78	: STD_LOGIC;
  SIGNAL not_aux76	: STD_LOGIC;
  SIGNAL not_aux74	: STD_LOGIC;
  SIGNAL not_aux71	: STD_LOGIC;
  SIGNAL not_aux7	: STD_LOGIC;
  SIGNAL not_aux66	: STD_LOGIC;
  SIGNAL not_aux64	: STD_LOGIC;
  SIGNAL not_aux63	: STD_LOGIC;
  SIGNAL not_aux61	: STD_LOGIC;
  SIGNAL not_aux6	: STD_LOGIC;
  SIGNAL not_aux59	: STD_LOGIC;
  SIGNAL not_aux56	: STD_LOGIC;
  SIGNAL not_aux54	: STD_LOGIC;
  SIGNAL not_aux53	: STD_LOGIC;
  SIGNAL not_aux49	: STD_LOGIC;
  SIGNAL not_aux48	: STD_LOGIC;
  SIGNAL not_aux46	: STD_LOGIC;
  SIGNAL not_aux41	: STD_LOGIC;
  SIGNAL not_aux4	: STD_LOGIC;
  SIGNAL not_aux38	: STD_LOGIC;
  SIGNAL not_aux37	: STD_LOGIC;
  SIGNAL not_aux36	: STD_LOGIC;
  SIGNAL not_aux35	: STD_LOGIC;
  SIGNAL not_aux33	: STD_LOGIC;
  SIGNAL not_aux32	: STD_LOGIC;
  SIGNAL not_aux31	: STD_LOGIC;
  SIGNAL not_aux30	: STD_LOGIC;
  SIGNAL not_aux3	: STD_LOGIC;
  SIGNAL not_aux28	: STD_LOGIC;
  SIGNAL not_aux27	: STD_LOGIC;
  SIGNAL not_aux26	: STD_LOGIC;
  SIGNAL not_aux25	: STD_LOGIC;
  SIGNAL not_aux24	: STD_LOGIC;
  SIGNAL not_aux23	: STD_LOGIC;
  SIGNAL not_aux22	: STD_LOGIC;
  SIGNAL not_aux20	: STD_LOGIC;
  SIGNAL not_aux19	: STD_LOGIC;
  SIGNAL not_aux17	: STD_LOGIC;
  SIGNAL not_aux16	: STD_LOGIC;
  SIGNAL not_aux15	: STD_LOGIC;
  SIGNAL not_aux14	: STD_LOGIC;
  SIGNAL not_aux13	: STD_LOGIC;
  SIGNAL not_aux123	: STD_LOGIC;
  SIGNAL not_aux122	: STD_LOGIC;
  SIGNAL not_aux121	: STD_LOGIC;
  SIGNAL not_aux120	: STD_LOGIC;
  SIGNAL not_aux119	: STD_LOGIC;
  SIGNAL not_aux117	: STD_LOGIC;
  SIGNAL not_aux116	: STD_LOGIC;
  SIGNAL not_aux115	: STD_LOGIC;
  SIGNAL not_aux113	: STD_LOGIC;
  SIGNAL not_aux111	: STD_LOGIC;
  SIGNAL not_aux11	: STD_LOGIC;
  SIGNAL not_aux106	: STD_LOGIC;
  SIGNAL not_aux105	: STD_LOGIC;
  SIGNAL not_aux103	: STD_LOGIC;
  SIGNAL not_aux101	: STD_LOGIC;
  SIGNAL not_aux1	: STD_LOGIC;
  SIGNAL not_aux0	: STD_LOGIC;
  SIGNAL noa2ao222_x1_sig	: STD_LOGIC;
  SIGNAL noa22_x1_sig	: STD_LOGIC;
  SIGNAL noa22_x1_5_sig	: STD_LOGIC;
  SIGNAL noa22_x1_4_sig	: STD_LOGIC;
  SIGNAL noa22_x1_3_sig	: STD_LOGIC;
  SIGNAL noa22_x1_2_sig	: STD_LOGIC;
  SIGNAL no4_x1_sig	: STD_LOGIC;
  SIGNAL no2_x1_sig	: STD_LOGIC;
  SIGNAL no2_x1_6_sig	: STD_LOGIC;
  SIGNAL no2_x1_5_sig	: STD_LOGIC;
  SIGNAL no2_x1_4_sig	: STD_LOGIC;
  SIGNAL no2_x1_3_sig	: STD_LOGIC;
  SIGNAL no2_x1_2_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_7_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_2_sig	: STD_LOGIC;
  SIGNAL nao22_x1_sig	: STD_LOGIC;
  SIGNAL nao22_x1_9_sig	: STD_LOGIC;
  SIGNAL nao22_x1_8_sig	: STD_LOGIC;
  SIGNAL nao22_x1_7_sig	: STD_LOGIC;
  SIGNAL nao22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao22_x1_2_sig	: STD_LOGIC;
  SIGNAL nao22_x1_18_sig	: STD_LOGIC;
  SIGNAL nao22_x1_17_sig	: STD_LOGIC;
  SIGNAL nao22_x1_16_sig	: STD_LOGIC;
  SIGNAL nao22_x1_15_sig	: STD_LOGIC;
  SIGNAL nao22_x1_14_sig	: STD_LOGIC;
  SIGNAL nao22_x1_13_sig	: STD_LOGIC;
  SIGNAL nao22_x1_12_sig	: STD_LOGIC;
  SIGNAL nao22_x1_11_sig	: STD_LOGIC;
  SIGNAL nao22_x1_10_sig	: STD_LOGIC;
  SIGNAL na3_x1_sig	: STD_LOGIC;
  SIGNAL na3_x1_4_sig	: STD_LOGIC;
  SIGNAL na3_x1_3_sig	: STD_LOGIC;
  SIGNAL na3_x1_2_sig	: STD_LOGIC;
  SIGNAL na2_x1_sig	: STD_LOGIC;
  SIGNAL na2_x1_9_sig	: STD_LOGIC;
  SIGNAL na2_x1_8_sig	: STD_LOGIC;
  SIGNAL na2_x1_7_sig	: STD_LOGIC;
  SIGNAL na2_x1_6_sig	: STD_LOGIC;
  SIGNAL na2_x1_5_sig	: STD_LOGIC;
  SIGNAL na2_x1_4_sig	: STD_LOGIC;
  SIGNAL na2_x1_3_sig	: STD_LOGIC;
  SIGNAL na2_x1_2_sig	: STD_LOGIC;
  SIGNAL na2_x1_15_sig	: STD_LOGIC;
  SIGNAL na2_x1_14_sig	: STD_LOGIC;
  SIGNAL na2_x1_13_sig	: STD_LOGIC;
  SIGNAL na2_x1_12_sig	: STD_LOGIC;
  SIGNAL na2_x1_11_sig	: STD_LOGIC;
  SIGNAL na2_x1_10_sig	: STD_LOGIC;
  SIGNAL mx3_x2_sig	: STD_LOGIC;
  SIGNAL mx3_x2_3_sig	: STD_LOGIC;
  SIGNAL mx3_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_sig	: STD_LOGIC;
  SIGNAL inv_x2_9_sig	: STD_LOGIC;
  SIGNAL inv_x2_8_sig	: STD_LOGIC;
  SIGNAL inv_x2_7_sig	: STD_LOGIC;
  SIGNAL inv_x2_6_sig	: STD_LOGIC;
  SIGNAL inv_x2_5_sig	: STD_LOGIC;
  SIGNAL inv_x2_4_sig	: STD_LOGIC;
  SIGNAL inv_x2_3_sig	: STD_LOGIC;
  SIGNAL inv_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_17_sig	: STD_LOGIC;
  SIGNAL inv_x2_16_sig	: STD_LOGIC;
  SIGNAL inv_x2_15_sig	: STD_LOGIC;
  SIGNAL inv_x2_14_sig	: STD_LOGIC;
  SIGNAL inv_x2_13_sig	: STD_LOGIC;
  SIGNAL inv_x2_12_sig	: STD_LOGIC;
  SIGNAL inv_x2_11_sig	: STD_LOGIC;
  SIGNAL inv_x2_10_sig	: STD_LOGIC;
  SIGNAL aux93	: STD_LOGIC;
  SIGNAL aux92	: STD_LOGIC;
  SIGNAL aux91	: STD_LOGIC;
  SIGNAL aux9	: STD_LOGIC;
  SIGNAL aux74	: STD_LOGIC;
  SIGNAL aux66	: STD_LOGIC;
  SIGNAL aux65	: STD_LOGIC;
  SIGNAL aux52	: STD_LOGIC;
  SIGNAL aux51	: STD_LOGIC;
  SIGNAL aux42	: STD_LOGIC;
  SIGNAL aux41	: STD_LOGIC;
  SIGNAL aux36	: STD_LOGIC;
  SIGNAL aux32	: STD_LOGIC;
  SIGNAL aux20	: STD_LOGIC;
  SIGNAL aux122	: STD_LOGIC;
  SIGNAL aux118	: STD_LOGIC;
  SIGNAL aux117	: STD_LOGIC;
  SIGNAL aux105	: STD_LOGIC;
  SIGNAL ao22_x2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_2_sig	: STD_LOGIC;
  SIGNAL an12_x1_sig	: STD_LOGIC;
  SIGNAL an12_x1_2_sig	: STD_LOGIC;
  SIGNAL a4_x2_sig	: STD_LOGIC;
  SIGNAL a2_x2_sig	: STD_LOGIC;
  SIGNAL a2_x2_9_sig	: STD_LOGIC;
  SIGNAL a2_x2_8_sig	: STD_LOGIC;
  SIGNAL a2_x2_7_sig	: STD_LOGIC;
  SIGNAL a2_x2_6_sig	: STD_LOGIC;
  SIGNAL a2_x2_5_sig	: STD_LOGIC;
  SIGNAL a2_x2_4_sig	: STD_LOGIC;
  SIGNAL a2_x2_3_sig	: STD_LOGIC;
  SIGNAL a2_x2_2_sig	: STD_LOGIC;
  SIGNAL a2_x2_13_sig	: STD_LOGIC;
  SIGNAL a2_x2_12_sig	: STD_LOGIC;
  SIGNAL a2_x2_11_sig	: STD_LOGIC;
  SIGNAL a2_x2_10_sig	: STD_LOGIC;

  COMPONENT mx3_x2
  PORT(
  cmd0	: IN STD_LOGIC;
  cmd1	: IN STD_LOGIC;
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2a22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao2o22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT an12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT on12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT inv_x2
  PORT(
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2a2a23_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  i5	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2ao222_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa2ao222_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT xr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nxr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC
   );
  END COMPONENT;

BEGIN
  out_data_ram_11_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => mx3_x2_3_sig,
    i1 => oa22_x2_10_sig,
    i2 => nao22_x1_16_sig,
    q => out_data_ram(11)
  );
  mx3_x2_3_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(2),
    cmd1 => in_ram_input_index(0),
    i0 => oa2a22_x2_3_sig,
    i1 => nao22_x1_18_sig,
    i2 => na2_x1_13_sig,
    q => mx3_x2_3_sig
  );
  oa2a22_x2_3_ins : oa2a22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => na2_x1_15_sig,
    i2 => na2_x1_14_sig,
    i3 => in_ram_input_index(0),
    q => oa2a22_x2_3_sig
  );
  na2_x1_15_ins : na2_x1
  PORT MAP (
    i0 => not_aux101,
    i1 => not_aux22,
    nq => na2_x1_15_sig
  );
  na2_x1_14_ins : na2_x1
  PORT MAP (
    i0 => not_aux105,
    i1 => not_aux115,
    nq => na2_x1_14_sig
  );
  nao22_x1_18_ins : nao22_x1
  PORT MAP (
    i0 => not_aux123,
    i1 => a2_x2_13_sig,
    i2 => not_aux11,
    nq => nao22_x1_18_sig
  );
  a2_x2_13_ins : a2_x2
  PORT MAP (
    i0 => not_aux23,
    i1 => not_aux1,
    q => a2_x2_13_sig
  );
  na2_x1_13_ins : na2_x1
  PORT MAP (
    i0 => not_aux113,
    i1 => not_aux14,
    nq => na2_x1_13_sig
  );
  oa22_x2_10_ins : oa22_x2
  PORT MAP (
    i0 => nao22_x1_17_sig,
    i1 => in_ram_input_index(0),
    i2 => nao2o22_x1_7_sig,
    q => oa22_x2_10_sig
  );
  nao22_x1_17_ins : nao22_x1
  PORT MAP (
    i0 => not_aux123,
    i1 => a2_x2_12_sig,
    i2 => not_aux3,
    nq => nao22_x1_17_sig
  );
  a2_x2_12_ins : a2_x2
  PORT MAP (
    i0 => not_aux85,
    i1 => not_aux41,
    q => a2_x2_12_sig
  );
  nao2o22_x1_7_ins : nao2o22_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => ao22_x2_2_sig,
    i2 => not_aux9,
    i3 => not_in_ram_input_index(5),
    nq => nao2o22_x1_7_sig
  );
  ao22_x2_2_ins : ao22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(5),
    i1 => not_aux38,
    i2 => not_aux36,
    q => ao22_x2_2_sig
  );
  nao22_x1_16_ins : nao22_x1
  PORT MAP (
    i0 => not_aux121,
    i1 => a2_x2_11_sig,
    i2 => not_aux111,
    nq => nao22_x1_16_sig
  );
  a2_x2_11_ins : a2_x2
  PORT MAP (
    i0 => not_aux106,
    i1 => not_aux38,
    q => a2_x2_11_sig
  );
  out_data_ram_10_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => mx3_x2_2_sig,
    i1 => nao2o22_x1_5_sig,
    i2 => nao22_x1_15_sig,
    q => out_data_ram(10)
  );
  mx3_x2_2_ins : mx3_x2
  PORT MAP (
    cmd0 => in_ram_input_index(2),
    cmd1 => not_in_ram_input_index(0),
    i0 => nao2o22_x1_6_sig,
    i1 => on12_x1_sig,
    i2 => na2_x1_12_sig,
    q => mx3_x2_2_sig
  );
  nao2o22_x1_6_ins : nao2o22_x1
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => an12_x1_2_sig,
    i2 => not_aux113,
    i3 => in_ram_input_index(0),
    nq => nao2o22_x1_6_sig
  );
  an12_x1_2_ins : an12_x1
  PORT MAP (
    i0 => aux92,
    i1 => not_aux11,
    q => an12_x1_2_sig
  );
  on12_x1_ins : on12_x1
  PORT MAP (
    i0 => o3_x2_6_sig,
    i1 => aux51,
    q => on12_x1_sig
  );
  o3_x2_6_ins : o3_x2
  PORT MAP (
    i0 => not_aux87,
    i1 => not_aux123,
    i2 => aux41,
    q => o3_x2_6_sig
  );
  na2_x1_12_ins : na2_x1
  PORT MAP (
    i0 => not_aux25,
    i1 => not_aux115,
    nq => na2_x1_12_sig
  );
  nao2o22_x1_5_ins : nao2o22_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => noa22_x1_5_sig,
    i2 => not_aux59,
    i3 => not_in_ram_input_index(0),
    nq => nao2o22_x1_5_sig
  );
  noa22_x1_5_ins : noa22_x1
  PORT MAP (
    i0 => oa22_x2_9_sig,
    i1 => in_ram_input_index(5),
    i2 => aux36,
    nq => noa22_x1_5_sig
  );
  oa22_x2_9_ins : oa22_x2
  PORT MAP (
    i0 => aux93,
    i1 => in_ram_input_index(7),
    i2 => inv_x2_17_sig,
    q => oa22_x2_9_sig
  );
  inv_x2_17_ins : inv_x2
  PORT MAP (
    i => not_aux56,
    nq => inv_x2_17_sig
  );
  nao22_x1_15_ins : nao22_x1
  PORT MAP (
    i0 => not_aux121,
    i1 => a2_x2_10_sig,
    i2 => not_aux111,
    nq => nao22_x1_15_sig
  );
  a2_x2_10_ins : a2_x2
  PORT MAP (
    i0 => not_aux9,
    i1 => not_aux38,
    q => a2_x2_10_sig
  );
  out_data_ram_9_ins : oa2a2a23_x2
  PORT MAP (
    i0 => inv_x2_16_sig,
    i1 => in_ram_input_index(2),
    i2 => no4_x1_sig,
    i3 => nao22_x1_14_sig,
    i4 => na2_x1_11_sig,
    i5 => in_ram_input_index(1),
    q => out_data_ram(9)
  );
  inv_x2_16_ins : inv_x2
  PORT MAP (
    i => not_aux80,
    nq => inv_x2_16_sig
  );
  no4_x1_ins : no4_x1
  PORT MAP (
    i0 => in_ram_input_index(1),
    i1 => in_ram_input_index(5),
    i2 => in_ram_input_index(2),
    i3 => in_ram_input_index(0),
    nq => no4_x1_sig
  );
  nao22_x1_14_ins : nao22_x1
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux8,
    i2 => not_aux33,
    nq => nao22_x1_14_sig
  );
  na2_x1_11_ins : na2_x1
  PORT MAP (
    i0 => o3_x2_5_sig,
    i1 => o3_x2_4_sig,
    nq => na2_x1_11_sig
  );
  o3_x2_5_ins : o3_x2
  PORT MAP (
    i0 => not_aux120,
    i1 => in_ram_input_index(5),
    i2 => not_aux106,
    q => o3_x2_5_sig
  );
  o3_x2_4_ins : o3_x2
  PORT MAP (
    i0 => not_aux119,
    i1 => not_aux33,
    i2 => not_in_ram_input_index(5),
    q => o3_x2_4_sig
  );
  out_data_ram_8_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => mx3_x2_sig,
    i1 => nao22_x1_13_sig,
    i2 => nao2o22_x1_4_sig,
    q => out_data_ram(8)
  );
  mx3_x2_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(2),
    cmd1 => not_in_ram_input_index(0),
    i0 => oa22_x2_8_sig,
    i1 => oa22_x2_7_sig,
    i2 => na2_x1_9_sig,
    q => mx3_x2_sig
  );
  oa22_x2_8_ins : oa22_x2
  PORT MAP (
    i0 => aux105,
    i1 => in_ram_input_index(0),
    i2 => inv_x2_15_sig,
    q => oa22_x2_8_sig
  );
  inv_x2_15_ins : inv_x2
  PORT MAP (
    i => not_aux103,
    nq => inv_x2_15_sig
  );
  oa22_x2_7_ins : oa22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(5),
    i1 => na2_x1_10_sig,
    i2 => inv_x2_14_sig,
    q => oa22_x2_7_sig
  );
  na2_x1_10_ins : na2_x1
  PORT MAP (
    i0 => not_aux27,
    i1 => not_aux33,
    nq => na2_x1_10_sig
  );
  inv_x2_14_ins : inv_x2
  PORT MAP (
    i => not_aux14,
    nq => inv_x2_14_sig
  );
  na2_x1_9_ins : na2_x1
  PORT MAP (
    i0 => not_aux11,
    i1 => not_aux74,
    nq => na2_x1_9_sig
  );
  nao22_x1_13_ins : nao22_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => noa22_x1_4_sig,
    i2 => not_aux99,
    nq => nao22_x1_13_sig
  );
  noa22_x1_4_ins : noa22_x1
  PORT MAP (
    i0 => aux91,
    i1 => in_ram_input_index(5),
    i2 => aux36,
    nq => noa22_x1_4_sig
  );
  nao2o22_x1_4_ins : nao2o22_x1
  PORT MAP (
    i0 => a2_x2_9_sig,
    i1 => not_aux121,
    i2 => a2_x2_8_sig,
    i3 => not_aux122,
    nq => nao2o22_x1_4_sig
  );
  a2_x2_9_ins : a2_x2
  PORT MAP (
    i0 => not_aux6,
    i1 => not_aux82,
    q => a2_x2_9_sig
  );
  a2_x2_8_ins : a2_x2
  PORT MAP (
    i0 => not_aux24,
    i1 => not_aux63,
    q => a2_x2_8_sig
  );
  out_data_ram_7_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => oa2ao222_x2_4_sig,
    i1 => nao22_x1_12_sig,
    i2 => nao22_x1_11_sig,
    q => out_data_ram(7)
  );
  oa2ao222_x2_4_ins : oa2ao222_x2
  PORT MAP (
    i0 => oa22_x2_6_sig,
    i1 => not_in_ram_input_index(2),
    i2 => noa22_x1_3_sig,
    i3 => inv_x2_12_sig,
    i4 => in_ram_input_index(2),
    q => oa2ao222_x2_4_sig
  );
  oa22_x2_6_ins : oa22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => na2_x1_8_sig,
    i2 => inv_x2_13_sig,
    q => oa22_x2_6_sig
  );
  na2_x1_8_ins : na2_x1
  PORT MAP (
    i0 => not_aux25,
    i1 => not_aux14,
    nq => na2_x1_8_sig
  );
  inv_x2_13_ins : inv_x2
  PORT MAP (
    i => not_aux76,
    nq => inv_x2_13_sig
  );
  noa22_x1_3_ins : noa22_x1
  PORT MAP (
    i0 => o2_x2_sig,
    i1 => not_aux105,
    i2 => not_in_ram_input_index(0),
    nq => noa22_x1_3_sig
  );
  o2_x2_ins : o2_x2
  PORT MAP (
    i0 => not_aux93,
    i1 => not_aux123,
    q => o2_x2_sig
  );
  inv_x2_12_ins : inv_x2
  PORT MAP (
    i => not_aux103,
    nq => inv_x2_12_sig
  );
  nao22_x1_12_ins : nao22_x1
  PORT MAP (
    i0 => not_aux117,
    i1 => a2_x2_7_sig,
    i2 => not_aux99,
    nq => nao22_x1_12_sig
  );
  a2_x2_7_ins : a2_x2
  PORT MAP (
    i0 => na3_x1_4_sig,
    i1 => not_aux9,
    q => a2_x2_7_sig
  );
  na3_x1_4_ins : na3_x1
  PORT MAP (
    i0 => in_ram_input_index(3),
    i1 => not_aux93,
    i2 => not_in_ram_input_index(7),
    nq => na3_x1_4_sig
  );
  nao22_x1_11_ins : nao22_x1
  PORT MAP (
    i0 => not_aux33,
    i1 => not_aux122,
    i2 => not_aux84,
    nq => nao22_x1_11_sig
  );
  out_data_ram_6_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => oa2ao222_x2_3_sig,
    i1 => oa2ao222_x2_2_sig,
    i2 => oa2a22_x2_2_sig,
    q => out_data_ram(6)
  );
  oa2ao222_x2_3_ins : oa2ao222_x2
  PORT MAP (
    i0 => nao22_x1_10_sig,
    i1 => in_ram_input_index(2),
    i2 => a2_x2_6_sig,
    i3 => an12_x1_sig,
    i4 => not_in_ram_input_index(2),
    q => oa2ao222_x2_3_sig
  );
  nao22_x1_10_ins : nao22_x1
  PORT MAP (
    i0 => not_aux117,
    i1 => not_aux6,
    i2 => na3_x1_3_sig,
    nq => nao22_x1_10_sig
  );
  na3_x1_3_ins : na3_x1
  PORT MAP (
    i0 => not_in_ram_input_index(7),
    i1 => na2_x1_7_sig,
    i2 => aux118,
    nq => na3_x1_3_sig
  );
  na2_x1_7_ins : na2_x1
  PORT MAP (
    i0 => not_aux26,
    i1 => not_aux32,
    nq => na2_x1_7_sig
  );
  a2_x2_6_ins : a2_x2
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => aux92,
    q => a2_x2_6_sig
  );
  an12_x1_ins : an12_x1
  PORT MAP (
    i0 => not_aux122,
    i1 => aux91,
    q => an12_x1_sig
  );
  oa2ao222_x2_2_ins : oa2ao222_x2
  PORT MAP (
    i0 => aux74,
    i1 => in_ram_input_index(0),
    i2 => noa22_x1_2_sig,
    i3 => aux36,
    i4 => not_in_ram_input_index(0),
    q => oa2ao222_x2_2_sig
  );
  noa22_x1_2_ins : noa22_x1
  PORT MAP (
    i0 => not_aux9,
    i1 => not_aux13,
    i2 => not_in_ram_input_index(5),
    nq => noa22_x1_2_sig
  );
  oa2a22_x2_2_ins : oa2a22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => na2_x1_6_sig,
    i2 => aux20,
    i3 => in_ram_input_index(0),
    q => oa2a22_x2_2_sig
  );
  na2_x1_6_ins : na2_x1
  PORT MAP (
    i0 => not_aux28,
    i1 => not_aux3,
    nq => na2_x1_6_sig
  );
  out_data_ram_5_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => nao22_x1_9_sig,
    i1 => oa22_x2_5_sig,
    i2 => nao22_x1_7_sig,
    q => out_data_ram(5)
  );
  nao22_x1_9_ins : nao22_x1
  PORT MAP (
    i0 => not_in_ram_input_index(2),
    i1 => noa2ao222_x1_sig,
    i2 => not_aux78,
    nq => nao22_x1_9_sig
  );
  noa2ao222_x1_ins : noa2ao222_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => aux65,
    i2 => inv_x2_11_sig,
    i3 => no2_x1_6_sig,
    i4 => not_in_ram_input_index(0),
    nq => noa2ao222_x1_sig
  );
  inv_x2_11_ins : inv_x2
  PORT MAP (
    i => not_aux90,
    nq => inv_x2_11_sig
  );
  no2_x1_6_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux86,
    nq => no2_x1_6_sig
  );
  oa22_x2_5_ins : oa22_x2
  PORT MAP (
    i0 => nao22_x1_8_sig,
    i1 => aux118,
    i2 => inv_x2_10_sig,
    q => oa22_x2_5_sig
  );
  nao22_x1_8_ins : nao22_x1
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux85,
    i2 => not_aux9,
    nq => nao22_x1_8_sig
  );
  inv_x2_10_ins : inv_x2
  PORT MAP (
    i => not_aux71,
    nq => inv_x2_10_sig
  );
  nao22_x1_7_ins : nao22_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_aux64,
    i2 => not_aux84,
    nq => nao22_x1_7_sig
  );
  out_data_ram_4_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => nao22_x1_6_sig,
    i1 => nao22_x1_5_sig,
    i2 => nao2o22_x1_3_sig,
    q => out_data_ram(4)
  );
  nao22_x1_6_ins : nao22_x1
  PORT MAP (
    i0 => not_in_ram_input_index(2),
    i1 => a2_x2_5_sig,
    i2 => not_aux78,
    nq => nao22_x1_6_sig
  );
  a2_x2_5_ins : a2_x2
  PORT MAP (
    i0 => na3_x1_2_sig,
    i1 => not_aux80,
    q => a2_x2_5_sig
  );
  na3_x1_2_ins : na3_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => xr2_x1_sig,
    i2 => aux32,
    nq => na3_x1_2_sig
  );
  xr2_x1_ins : xr2_x1
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => in_ram_input_index(7),
    q => xr2_x1_sig
  );
  nao22_x1_5_ins : nao22_x1
  PORT MAP (
    i0 => inv_x2_9_sig,
    i1 => a2_x2_4_sig,
    i2 => not_aux71,
    nq => nao22_x1_5_sig
  );
  inv_x2_9_ins : inv_x2
  PORT MAP (
    i => aux118,
    nq => inv_x2_9_sig
  );
  a2_x2_4_ins : a2_x2
  PORT MAP (
    i0 => not_aux9,
    i1 => o3_x2_3_sig,
    q => a2_x2_4_sig
  );
  o3_x2_3_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(3),
    i1 => in_ram_input_index(7),
    i2 => not_aux66,
    q => o3_x2_3_sig
  );
  nao2o22_x1_3_ins : nao2o22_x1
  PORT MAP (
    i0 => inv_x2_8_sig,
    i1 => in_ram_input_index(0),
    i2 => not_aux121,
    i3 => a2_x2_3_sig,
    nq => nao2o22_x1_3_sig
  );
  inv_x2_8_ins : inv_x2
  PORT MAP (
    i => aux65,
    nq => inv_x2_8_sig
  );
  a2_x2_3_ins : a2_x2
  PORT MAP (
    i0 => not_aux24,
    i1 => not_aux9,
    q => a2_x2_3_sig
  );
  out_data_ram_3_ins : oa2ao222_x2
  PORT MAP (
    i0 => nao2o22_x1_2_sig,
    i1 => not_in_ram_input_index(1),
    i2 => ao22_x2_sig,
    i3 => no2_x1_3_sig,
    i4 => in_ram_input_index(1),
    q => out_data_ram(3)
  );
  nao2o22_x1_2_ins : nao2o22_x1
  PORT MAP (
    i0 => not_aux61,
    i1 => not_aux116,
    i2 => not_aux120,
    i3 => not_aux28,
    nq => nao2o22_x1_2_sig
  );
  ao22_x2_ins : ao22_x2
  PORT MAP (
    i0 => no2_x1_5_sig,
    i1 => no2_x1_4_sig,
    i2 => in_ram_input_index(2),
    q => ao22_x2_sig
  );
  no2_x1_5_ins : no2_x1
  PORT MAP (
    i0 => not_aux3,
    i1 => not_in_ram_input_index(0),
    nq => no2_x1_5_sig
  );
  no2_x1_4_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_aux20,
    nq => no2_x1_4_sig
  );
  no2_x1_3_ins : no2_x1
  PORT MAP (
    i0 => not_aux36,
    i1 => not_aux119,
    nq => no2_x1_3_sig
  );
  out_data_ram_2_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => in_ram_input_index(2),
    i0 => oa22_x2_4_sig,
    i1 => oa2a22_x2_sig,
    i2 => nao22_x1_3_sig,
    q => out_data_ram(2)
  );
  oa22_x2_4_ins : oa22_x2
  PORT MAP (
    i0 => nao22_x1_4_sig,
    i1 => in_ram_input_index(2),
    i2 => inv_x2_7_sig,
    q => oa22_x2_4_sig
  );
  nao22_x1_4_ins : nao22_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_aux59,
    i2 => not_aux53,
    nq => nao22_x1_4_sig
  );
  inv_x2_7_ins : inv_x2
  PORT MAP (
    i => not_aux46,
    nq => inv_x2_7_sig
  );
  oa2a22_x2_ins : oa2a22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => na2_x1_5_sig,
    i2 => na2_x1_4_sig,
    i3 => aux118,
    q => oa2a22_x2_sig
  );
  na2_x1_5_ins : na2_x1
  PORT MAP (
    i0 => not_aux54,
    i1 => not_aux35,
    nq => na2_x1_5_sig
  );
  na2_x1_4_ins : na2_x1
  PORT MAP (
    i0 => not_aux56,
    i1 => not_aux9,
    nq => na2_x1_4_sig
  );
  nao22_x1_3_ins : nao22_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => inv_x2_6_sig,
    i2 => not_aux30,
    nq => nao22_x1_3_sig
  );
  inv_x2_6_ins : inv_x2
  PORT MAP (
    i => aux52,
    nq => inv_x2_6_sig
  );
  out_data_ram_1_ins : mx3_x2
  PORT MAP (
    cmd0 => not_in_ram_input_index(1),
    cmd1 => not_in_ram_input_index(2),
    i0 => oa22_x2_3_sig,
    i1 => oa22_x2_2_sig,
    i2 => nao2o22_x1_sig,
    q => out_data_ram(1)
  );
  oa22_x2_3_ins : oa22_x2
  PORT MAP (
    i0 => nao22_x1_2_sig,
    i1 => in_ram_input_index(2),
    i2 => inv_x2_5_sig,
    q => oa22_x2_3_sig
  );
  nao22_x1_2_ins : nao22_x1
  PORT MAP (
    i0 => not_aux117,
    i1 => not_aux48,
    i2 => not_aux53,
    nq => nao22_x1_2_sig
  );
  inv_x2_5_ins : inv_x2
  PORT MAP (
    i => not_aux46,
    nq => inv_x2_5_sig
  );
  oa22_x2_2_ins : oa22_x2
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => na2_x1_3_sig,
    i2 => inv_x2_4_sig,
    q => oa22_x2_2_sig
  );
  na2_x1_3_ins : na2_x1
  PORT MAP (
    i0 => not_aux20,
    i1 => not_aux22,
    nq => na2_x1_3_sig
  );
  inv_x2_4_ins : inv_x2
  PORT MAP (
    i => not_aux30,
    nq => inv_x2_4_sig
  );
  nao2o22_x1_ins : nao2o22_x1
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => a2_x2_2_sig,
    i2 => not_aux35,
    i3 => in_ram_input_index(0),
    nq => nao2o22_x1_sig
  );
  a2_x2_2_ins : a2_x2
  PORT MAP (
    i0 => not_aux36,
    i1 => not_aux19,
    q => a2_x2_2_sig
  );
  out_data_ram_0_ins : oa22_x2
  PORT MAP (
    i0 => oa2ao222_x2_sig,
    i1 => not_in_ram_input_index(1),
    i2 => a4_x2_sig,
    q => out_data_ram(0)
  );
  oa2ao222_x2_ins : oa2ao222_x2
  PORT MAP (
    i0 => inv_x2_3_sig,
    i1 => inv_x2_2_sig,
    i2 => no2_x1_2_sig,
    i3 => no2_x1_sig,
    i4 => in_ram_input_index(2),
    q => oa2ao222_x2_sig
  );
  inv_x2_3_ins : inv_x2
  PORT MAP (
    i => not_aux3,
    nq => inv_x2_3_sig
  );
  inv_x2_2_ins : inv_x2
  PORT MAP (
    i => not_aux116,
    nq => inv_x2_2_sig
  );
  no2_x1_2_ins : no2_x1
  PORT MAP (
    i0 => not_aux14,
    i1 => not_in_ram_input_index(0),
    nq => no2_x1_2_sig
  );
  no2_x1_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_aux11,
    nq => no2_x1_sig
  );
  a4_x2_ins : a4_x2
  PORT MAP (
    i0 => not_in_ram_input_index(0),
    i1 => in_ram_input_index(2),
    i2 => na2_x1_2_sig,
    i3 => in_ram_input_index(1),
    q => a4_x2_sig
  );
  na2_x1_2_ins : na2_x1
  PORT MAP (
    i0 => not_aux19,
    i1 => not_aux3,
    nq => na2_x1_2_sig
  );
  aux9_ins : no2_x1
  PORT MAP (
    i0 => not_aux8,
    i1 => not_in_ram_input_index(7),
    nq => aux9
  );
  aux20_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux13,
    nq => aux20
  );
  aux32_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(6),
    i1 => not_aux4,
    nq => aux32
  );
  aux36_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux27,
    nq => aux36
  );
  aux41_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(3),
    i1 => not_in_ram_input_index(6),
    nq => aux41
  );
  aux42_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux41,
    nq => aux42
  );
  aux51_ins : no3_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => not_aux49,
    i2 => in_ram_input_index(5),
    nq => aux51
  );
  aux52_ins : on12_x1
  PORT MAP (
    i0 => not_aux22,
    i1 => aux51,
    q => aux52
  );
  aux65_ins : na2_x1
  PORT MAP (
    i0 => not_aux64,
    i1 => not_aux61,
    nq => aux65
  );
  aux66_ins : xr2_x1
  PORT MAP (
    i0 => in_ram_input_index(4),
    i1 => in_ram_input_index(6),
    q => aux66
  );
  aux74_ins : no2_x1
  PORT MAP (
    i0 => not_aux24,
    i1 => not_in_ram_input_index(5),
    nq => aux74
  );
  aux91_ins : no2_x1
  PORT MAP (
    i0 => not_aux49,
    i1 => not_aux4,
    nq => aux91
  );
  aux92_ins : no2_x1
  PORT MAP (
    i0 => not_aux31,
    i1 => not_in_ram_input_index(5),
    nq => aux92
  );
  aux93_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(4),
    i1 => in_ram_input_index(6),
    nq => aux93
  );
  aux105_ins : noa22_x1
  PORT MAP (
    i0 => not_aux33,
    i1 => not_aux24,
    i2 => in_ram_input_index(5),
    nq => aux105
  );
  aux117_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_in_ram_input_index(5),
    nq => aux117
  );
  aux118_ins : a2_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => in_ram_input_index(0),
    q => aux118
  );
  aux122_ins : no2_x1
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => in_ram_input_index(0),
    nq => aux122
  );
  not_in_ram_input_index_0_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(0),
    nq => not_in_ram_input_index(0)
  );
  not_in_ram_input_index_1_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(1),
    nq => not_in_ram_input_index(1)
  );
  not_in_ram_input_index_2_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(2),
    nq => not_in_ram_input_index(2)
  );
  not_in_ram_input_index_3_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(3),
    nq => not_in_ram_input_index(3)
  );
  not_in_ram_input_index_4_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(4),
    nq => not_in_ram_input_index(4)
  );
  not_in_ram_input_index_5_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(5),
    nq => not_in_ram_input_index(5)
  );
  not_in_ram_input_index_6_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(6),
    nq => not_in_ram_input_index(6)
  );
  not_in_ram_input_index_7_ins : inv_x2
  PORT MAP (
    i => in_ram_input_index(7),
    nq => not_in_ram_input_index(7)
  );
  not_aux7_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(4),
    i1 => in_ram_input_index(3),
    q => not_aux7
  );
  not_aux8_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(6),
    i1 => not_aux7,
    q => not_aux8
  );
  not_aux9_ins : inv_x2
  PORT MAP (
    i => aux9,
    nq => not_aux9
  );
  not_aux15_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(3),
    i1 => not_in_ram_input_index(4),
    q => not_aux15
  );
  not_aux16_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(6),
    i1 => not_aux15,
    q => not_aux16
  );
  not_aux17_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux16,
    q => not_aux17
  );
  not_aux19_ins : oa22_x2
  PORT MAP (
    i0 => not_aux9,
    i1 => not_aux17,
    i2 => not_in_ram_input_index(5),
    q => not_aux19
  );
  not_aux0_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(4),
    i1 => in_ram_input_index(3),
    nq => not_aux0
  );
  not_aux1_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(6),
    i1 => not_aux0,
    q => not_aux1
  );
  not_aux3_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux1,
    i2 => not_in_ram_input_index(7),
    q => not_aux3
  );
  not_aux13_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux0,
    i2 => not_in_ram_input_index(6),
    q => not_aux13
  );
  not_aux14_ins : o2_x2
  PORT MAP (
    i0 => not_aux13,
    i1 => not_in_ram_input_index(5),
    q => not_aux14
  );
  not_aux4_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(4),
    i1 => not_in_ram_input_index(3),
    q => not_aux4
  );
  not_aux6_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux4,
    i2 => not_in_ram_input_index(6),
    q => not_aux6
  );
  not_aux11_ins : oa22_x2
  PORT MAP (
    i0 => not_aux9,
    i1 => not_aux6,
    i2 => in_ram_input_index(5),
    q => not_aux11
  );
  not_aux116_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(2),
    i1 => in_ram_input_index(0),
    q => not_aux116
  );
  not_aux22_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux4,
    i2 => not_in_ram_input_index(5),
    q => not_aux22
  );
  not_aux49_ins : nxr2_x1
  PORT MAP (
    i0 => in_ram_input_index(6),
    i1 => in_ram_input_index(7),
    nq => not_aux49
  );
  not_aux53_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => aux52,
    nq => not_aux53
  );
  not_aux41_ins : inv_x2
  PORT MAP (
    i => aux41,
    nq => not_aux41
  );
  not_aux32_ins : inv_x2
  PORT MAP (
    i => aux32,
    nq => not_aux32
  );
  not_aux48_ins : oa22_x2
  PORT MAP (
    i0 => not_aux41,
    i1 => not_aux32,
    i2 => in_ram_input_index(7),
    q => not_aux48
  );
  not_aux117_ins : inv_x2
  PORT MAP (
    i => aux117,
    nq => not_aux117
  );
  not_aux37_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(3),
    i1 => in_ram_input_index(6),
    nq => not_aux37
  );
  not_aux38_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux37,
    q => not_aux38
  );
  not_aux46_ins : oa22_x2
  PORT MAP (
    i0 => na3_x1_sig,
    i1 => o3_x2_2_sig,
    i2 => in_ram_input_index(2),
    q => not_aux46
  );
  na3_x1_ins : na3_x1
  PORT MAP (
    i0 => not_in_ram_input_index(5),
    i1 => in_ram_input_index(0),
    i2 => aux42,
    nq => na3_x1_sig
  );
  o3_x2_2_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => in_ram_input_index(0),
    i2 => not_aux38,
    q => o3_x2_2_sig
  );
  not_aux26_ins : o2_x2
  PORT MAP (
    i0 => not_aux7,
    i1 => not_in_ram_input_index(6),
    q => not_aux26
  );
  not_aux27_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux26,
    q => not_aux27
  );
  not_aux36_ins : inv_x2
  PORT MAP (
    i => aux36,
    nq => not_aux36
  );
  not_aux33_ins : o2_x2
  PORT MAP (
    i0 => not_aux32,
    i1 => not_in_ram_input_index(7),
    q => not_aux33
  );
  not_aux31_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux1,
    q => not_aux31
  );
  not_aux35_ins : oa22_x2
  PORT MAP (
    i0 => not_aux33,
    i1 => not_aux31,
    i2 => not_in_ram_input_index(5),
    q => not_aux35
  );
  not_aux28_ins : o2_x2
  PORT MAP (
    i0 => not_aux27,
    i1 => not_in_ram_input_index(5),
    q => not_aux28
  );
  not_aux23_ins : o2_x2
  PORT MAP (
    i0 => not_aux15,
    i1 => not_in_ram_input_index(6),
    q => not_aux23
  );
  not_aux24_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux23,
    q => not_aux24
  );
  not_aux25_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux24,
    q => not_aux25
  );
  not_aux30_ins : oa22_x2
  PORT MAP (
    i0 => not_aux28,
    i1 => not_aux25,
    i2 => not_in_ram_input_index(0),
    q => not_aux30
  );
  not_aux20_ins : inv_x2
  PORT MAP (
    i => aux20,
    nq => not_aux20
  );
  not_aux59_ins : ao22_x2
  PORT MAP (
    i0 => a2_x2_sig,
    i1 => not_in_ram_input_index(5),
    i2 => not_aux3,
    q => not_aux59
  );
  a2_x2_ins : a2_x2
  PORT MAP (
    i0 => not_aux48,
    i1 => not_aux9,
    q => a2_x2_sig
  );
  not_aux56_ins : oa22_x2
  PORT MAP (
    i0 => not_aux16,
    i1 => not_aux37,
    i2 => in_ram_input_index(7),
    q => not_aux56
  );
  not_aux54_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux6,
    q => not_aux54
  );
  not_aux119_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_in_ram_input_index(2),
    nq => not_aux119
  );
  not_aux120_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(2),
    i1 => in_ram_input_index(0),
    nq => not_aux120
  );
  not_aux61_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux32,
    i2 => not_in_ram_input_index(5),
    q => not_aux61
  );
  not_aux80_ins : o3_x2
  PORT MAP (
    i0 => not_aux17,
    i1 => in_ram_input_index(0),
    i2 => not_in_ram_input_index(5),
    q => not_aux80
  );
  not_aux74_ins : inv_x2
  PORT MAP (
    i => aux74,
    nq => not_aux74
  );
  not_aux76_ins : oa22_x2
  PORT MAP (
    i0 => not_aux74,
    i1 => not_aux36,
    i2 => not_in_ram_input_index(0),
    q => not_aux76
  );
  not_aux78_ins : oa22_x2
  PORT MAP (
    i0 => oa22_x2_sig,
    i1 => not_aux76,
    i2 => in_ram_input_index(2),
    q => not_aux78
  );
  oa22_x2_ins : oa22_x2
  PORT MAP (
    i0 => not_aux14,
    i1 => not_aux54,
    i2 => in_ram_input_index(0),
    q => oa22_x2_sig
  );
  not_aux66_ins : inv_x2
  PORT MAP (
    i => aux66,
    nq => not_aux66
  );
  not_aux71_ins : oa22_x2
  PORT MAP (
    i0 => o3_x2_sig,
    i1 => not_aux33,
    i2 => na2_x1_sig,
    q => not_aux71
  );
  o3_x2_ins : o3_x2
  PORT MAP (
    i0 => not_in_ram_input_index(3),
    i1 => in_ram_input_index(7),
    i2 => not_aux66,
    q => o3_x2_sig
  );
  na2_x1_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_in_ram_input_index(0),
    nq => na2_x1_sig
  );
  not_aux121_ins : na2_x1
  PORT MAP (
    i0 => in_ram_input_index(0),
    i1 => not_in_ram_input_index(5),
    nq => not_aux121
  );
  not_aux63_ins : na3_x1
  PORT MAP (
    i0 => in_ram_input_index(3),
    i1 => in_ram_input_index(7),
    i2 => not_in_ram_input_index(6),
    nq => not_aux63
  );
  not_aux64_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux63,
    q => not_aux64
  );
  not_aux87_ins : nxr2_x1
  PORT MAP (
    i0 => in_ram_input_index(4),
    i1 => in_ram_input_index(3),
    nq => not_aux87
  );
  not_aux90_ins : o4_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => in_ram_input_index(6),
    i2 => not_aux87,
    i3 => not_in_ram_input_index(5),
    q => not_aux90
  );
  not_aux85_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(6),
    i1 => not_in_ram_input_index(4),
    q => not_aux85
  );
  not_aux86_ins : o2_x2
  PORT MAP (
    i0 => not_aux85,
    i1 => not_in_ram_input_index(7),
    q => not_aux86
  );
  not_aux82_ins : na3_x1
  PORT MAP (
    i0 => not_in_ram_input_index(3),
    i1 => in_ram_input_index(7),
    i2 => not_in_ram_input_index(6),
    nq => not_aux82
  );
  not_aux84_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => not_aux82,
    i2 => not_in_ram_input_index(0),
    q => not_aux84
  );
  not_aux122_ins : inv_x2
  PORT MAP (
    i => aux122,
    nq => not_aux122
  );
  not_aux93_ins : inv_x2
  PORT MAP (
    i => aux93,
    nq => not_aux93
  );
  not_aux123_ins : o2_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_in_ram_input_index(5),
    q => not_aux123
  );
  not_aux105_ins : inv_x2
  PORT MAP (
    i => aux105,
    nq => not_aux105
  );
  not_aux101_ins : oa22_x2
  PORT MAP (
    i0 => not_aux86,
    i1 => not_aux13,
    i2 => in_ram_input_index(5),
    q => not_aux101
  );
  not_aux103_ins : oa22_x2
  PORT MAP (
    i0 => not_aux90,
    i1 => not_aux101,
    i2 => in_ram_input_index(0),
    q => not_aux103
  );
  not_aux99_ins : oa22_x2
  PORT MAP (
    i0 => nao22_x1_sig,
    i1 => not_aux3,
    i2 => not_in_ram_input_index(0),
    q => not_aux99
  );
  nao22_x1_ins : nao22_x1
  PORT MAP (
    i0 => noa22_x1_sig,
    i1 => aux9,
    i2 => in_ram_input_index(5),
    nq => nao22_x1_sig
  );
  noa22_x1_ins : noa22_x1
  PORT MAP (
    i0 => not_aux26,
    i1 => not_aux85,
    i2 => in_ram_input_index(7),
    nq => noa22_x1_sig
  );
  not_aux106_ins : o2_x2
  PORT MAP (
    i0 => not_aux16,
    i1 => not_in_ram_input_index(7),
    q => not_aux106
  );
  not_aux115_ins : o3_x2
  PORT MAP (
    i0 => in_ram_input_index(7),
    i1 => not_aux7,
    i2 => not_in_ram_input_index(5),
    q => not_aux115
  );
  not_aux113_ins : oa22_x2
  PORT MAP (
    i0 => inv_x2_sig,
    i1 => not_aux33,
    i2 => in_ram_input_index(5),
    q => not_aux113
  );
  inv_x2_ins : inv_x2
  PORT MAP (
    i => aux42,
    nq => inv_x2_sig
  );
  not_aux111_ins : oa22_x2
  PORT MAP (
    i0 => o4_x2_sig,
    i1 => not_aux28,
    i2 => in_ram_input_index(0),
    q => not_aux111
  );
  o4_x2_ins : o4_x2
  PORT MAP (
    i0 => in_ram_input_index(5),
    i1 => in_ram_input_index(3),
    i2 => in_ram_input_index(7),
    i3 => aux66,
    q => o4_x2_sig
  );
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_ram_boog of ram_boog is
  for RTL
    for all: mx3_x2 use entity sxlib.mx3_x2(vital); end for;
    for all: oa2a22_x2 use entity sxlib.oa2a22_x2(vital); end for;
    for all: na2_x1 use entity sxlib.na2_x1(vital); end for;
    for all: nao22_x1 use entity sxlib.nao22_x1(vital); end for;
    for all: a2_x2 use entity sxlib.a2_x2(vital); end for;
    for all: oa22_x2 use entity sxlib.oa22_x2(vital); end for;
    for all: nao2o22_x1 use entity sxlib.nao2o22_x1(vital); end for;
    for all: ao22_x2 use entity sxlib.ao22_x2(vital); end for;
    for all: an12_x1 use entity sxlib.an12_x1(vital); end for;
    for all: on12_x1 use entity sxlib.on12_x1(vital); end for;
    for all: o3_x2 use entity sxlib.o3_x2(vital); end for;
    for all: noa22_x1 use entity sxlib.noa22_x1(vital); end for;
    for all: inv_x2 use entity sxlib.inv_x2(vital); end for;
    for all: oa2a2a23_x2 use entity sxlib.oa2a2a23_x2(vital); end for;
    for all: no4_x1 use entity sxlib.no4_x1(vital); end for;
    for all: oa2ao222_x2 use entity sxlib.oa2ao222_x2(vital); end for;
    for all: o2_x2 use entity sxlib.o2_x2(vital); end for;
    for all: na3_x1 use entity sxlib.na3_x1(vital); end for;
    for all: noa2ao222_x1 use entity sxlib.noa2ao222_x1(vital); end for;
    for all: no2_x1 use entity sxlib.no2_x1(vital); end for;
    for all: xr2_x1 use entity sxlib.xr2_x1(vital); end for;
    for all: a4_x2 use entity sxlib.a4_x2(vital); end for;
    for all: no3_x1 use entity sxlib.no3_x1(vital); end for;
    for all: nxr2_x1 use entity sxlib.nxr2_x1(vital); end for;
    for all: o4_x2 use entity sxlib.o4_x2(vital); end for;
  end for;
end CFG_ram_boog;
