-- Generated by vxx2ghdl
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ram_boom IS
PORT(
  in_ram_input_index	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
  out_data_ram	: OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
);
END ram_boom;

ARCHITECTURE RTL OF ram_boom IS
  SIGNAL aux0	: STD_LOGIC;
  SIGNAL aux1	: STD_LOGIC;
  SIGNAL aux3	: STD_LOGIC;
  SIGNAL aux4	: STD_LOGIC;
  SIGNAL aux6	: STD_LOGIC;
  SIGNAL aux7	: STD_LOGIC;
  SIGNAL aux8	: STD_LOGIC;
  SIGNAL aux9	: STD_LOGIC;
  SIGNAL aux11	: STD_LOGIC;
  SIGNAL aux13	: STD_LOGIC;
  SIGNAL aux14	: STD_LOGIC;
  SIGNAL aux15	: STD_LOGIC;
  SIGNAL aux16	: STD_LOGIC;
  SIGNAL aux17	: STD_LOGIC;
  SIGNAL aux19	: STD_LOGIC;
  SIGNAL aux20	: STD_LOGIC;
  SIGNAL aux22	: STD_LOGIC;
  SIGNAL aux23	: STD_LOGIC;
  SIGNAL aux24	: STD_LOGIC;
  SIGNAL aux25	: STD_LOGIC;
  SIGNAL aux26	: STD_LOGIC;
  SIGNAL aux27	: STD_LOGIC;
  SIGNAL aux28	: STD_LOGIC;
  SIGNAL aux30	: STD_LOGIC;
  SIGNAL aux31	: STD_LOGIC;
  SIGNAL aux32	: STD_LOGIC;
  SIGNAL aux33	: STD_LOGIC;
  SIGNAL aux35	: STD_LOGIC;
  SIGNAL aux36	: STD_LOGIC;
  SIGNAL aux37	: STD_LOGIC;
  SIGNAL aux38	: STD_LOGIC;
  SIGNAL aux41	: STD_LOGIC;
  SIGNAL aux42	: STD_LOGIC;
  SIGNAL aux46	: STD_LOGIC;
  SIGNAL aux48	: STD_LOGIC;
  SIGNAL aux49	: STD_LOGIC;
  SIGNAL aux51	: STD_LOGIC;
  SIGNAL aux52	: STD_LOGIC;
  SIGNAL aux53	: STD_LOGIC;
  SIGNAL aux54	: STD_LOGIC;
  SIGNAL aux56	: STD_LOGIC;
  SIGNAL aux59	: STD_LOGIC;
  SIGNAL aux61	: STD_LOGIC;
  SIGNAL aux63	: STD_LOGIC;
  SIGNAL aux64	: STD_LOGIC;
  SIGNAL aux65	: STD_LOGIC;
  SIGNAL aux66	: STD_LOGIC;
  SIGNAL aux71	: STD_LOGIC;
  SIGNAL aux74	: STD_LOGIC;
  SIGNAL aux76	: STD_LOGIC;
  SIGNAL aux78	: STD_LOGIC;
  SIGNAL aux80	: STD_LOGIC;
  SIGNAL aux82	: STD_LOGIC;
  SIGNAL aux84	: STD_LOGIC;
  SIGNAL aux85	: STD_LOGIC;
  SIGNAL aux86	: STD_LOGIC;
  SIGNAL aux87	: STD_LOGIC;
  SIGNAL aux90	: STD_LOGIC;
  SIGNAL aux91	: STD_LOGIC;
  SIGNAL aux92	: STD_LOGIC;
  SIGNAL aux93	: STD_LOGIC;
  SIGNAL aux99	: STD_LOGIC;
  SIGNAL aux101	: STD_LOGIC;
  SIGNAL aux103	: STD_LOGIC;
  SIGNAL aux105	: STD_LOGIC;
  SIGNAL aux106	: STD_LOGIC;
  SIGNAL aux111	: STD_LOGIC;
  SIGNAL aux113	: STD_LOGIC;
  SIGNAL aux115	: STD_LOGIC;
  SIGNAL aux116	: STD_LOGIC;
  SIGNAL aux117	: STD_LOGIC;
  SIGNAL aux118	: STD_LOGIC;
  SIGNAL aux119	: STD_LOGIC;
  SIGNAL aux120	: STD_LOGIC;
  SIGNAL aux121	: STD_LOGIC;
  SIGNAL aux122	: STD_LOGIC;
  SIGNAL aux123	: STD_LOGIC;

BEGIN
  out_data_ram(11) <= (((((((aux115 OR aux105) AND in_ram_input_index(0)) OR ((aux22 OR aux101) AND 
NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR ((((((aux23 OR aux1) 
AND aux123) OR aux11) AND in_ram_input_index(0)) OR ((aux14 OR aux113) AND NOT(in_ram_input_index(0)
))) AND NOT(in_ram_input_index(2)))) AND in_ram_input_index(1)) OR ((((((aux9 
AND in_ram_input_index(5)) OR ((((aux41 OR aux85) AND aux123) OR aux3) AND in_ram_input_index(0)
)) OR (((aux38 AND in_ram_input_index(5)) OR aux36) AND NOT(in_ram_input_index(0)
))) AND in_ram_input_index(2)) OR ((((aux106 OR aux38) AND aux121) OR aux111) 
AND NOT(in_ram_input_index(2)))) AND NOT(in_ram_input_index(1))));
  out_data_ram(10) <= (((((((aux115 OR aux25) AND in_ram_input_index(0)) OR ((((NOT(aux41) AND aux87)
 AND aux123) OR aux51) AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)
) OR ((((aux92 OR aux11) AND in_ram_input_index(0)) OR (aux113 AND NOT(in_ram_input_index(0)
))) AND NOT(in_ram_input_index(2)))) AND in_ram_input_index(1)) OR (((((aux59 
AND in_ram_input_index(0)) OR (((((aux93 AND in_ram_input_index(7)) OR aux56) AND in_ram_input_index(5)
) OR aux36) AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR ((((aux9
 OR aux38) AND aux121) OR aux111) AND NOT(in_ram_input_index(2)))) AND NOT(in_ram_input_index(1)
)));
  out_data_ram(9) <= (((aux80 AND in_ram_input_index(2)) OR ((((aux106 AND NOT(in_ram_input_index(5)
)) AND aux120) OR ((aux33 AND in_ram_input_index(5)) AND aux119)) AND in_ram_input_index(1)
)) OR (((((aux33 OR (aux8 AND NOT(in_ram_input_index(7)))) AND NOT(in_ram_input_index(5)
)) AND NOT(in_ram_input_index(0))) AND NOT(in_ram_input_index(2))) AND NOT(in_ram_input_index(1)
)));
  out_data_ram(8) <= ((((((aux105 AND in_ram_input_index(0)) OR aux103) AND in_ram_input_index(2)) 
OR ((((aux74 OR aux11) AND in_ram_input_index(0)) OR ((aux14 OR ((aux33 OR aux27)
 AND NOT(in_ram_input_index(5)))) AND NOT(in_ram_input_index(0)))) AND NOT(in_ram_input_index(2)
))) AND in_ram_input_index(1)) OR ((((aux99 OR (((aux91 AND in_ram_input_index(5)
) OR aux36) AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR ((((aux82
 OR aux6) AND aux121) OR ((aux63 OR aux24) AND aux122)) AND NOT(in_ram_input_index(2)
))) AND NOT(in_ram_input_index(1))));
  out_data_ram(7) <= ((((((((aux93 AND aux123) OR aux105) AND in_ram_input_index(0)) OR aux103) AND in_ram_input_index(2)
) OR ((aux76 OR ((aux14 OR aux25) AND NOT(in_ram_input_index(0)))) AND NOT(in_ram_input_index(2)
))) AND in_ram_input_index(1)) OR ((((aux99 OR ((aux9 OR ((in_ram_input_index(3)
 AND NOT(aux93)) AND NOT(in_ram_input_index(7)))) AND aux117)) AND in_ram_input_index(2)
) OR ((aux84 OR (aux33 AND aux122)) AND NOT(in_ram_input_index(2)))) AND NOT(in_ram_input_index(1)
)));
  out_data_ram(6) <= ((((((((aux26 OR aux32) AND NOT(in_ram_input_index(7))) AND aux118) OR (aux6 
AND aux117)) AND in_ram_input_index(2)) OR (((aux92 AND in_ram_input_index(0)) OR 
(aux91 AND aux122)) AND NOT(in_ram_input_index(2)))) AND in_ram_input_index(1)) 
OR (((((aux74 AND in_ram_input_index(0)) OR ((((aux9 OR aux13) AND in_ram_input_index(5)
) OR aux36) AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR (((aux20
 AND in_ram_input_index(0)) OR ((aux28 OR aux3) AND NOT(in_ram_input_index(0))))
 AND NOT(in_ram_input_index(2)))) AND NOT(in_ram_input_index(1))));
  out_data_ram(5) <= ((((((aux65 AND in_ram_input_index(0)) OR ((aux90 OR (aux86 AND NOT(in_ram_input_index(5)
))) AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR aux78) AND in_ram_input_index(1)
) OR ((((((aux9 OR (aux85 AND NOT(in_ram_input_index(7)))) AND aux118) OR aux71)
 AND in_ram_input_index(2)) OR ((aux84 OR (aux64 AND NOT(in_ram_input_index(0)))
) AND NOT(in_ram_input_index(2)))) AND NOT(in_ram_input_index(1))));
  out_data_ram(4) <= (((((((aux32 AND (in_ram_input_index(7) XOR in_ram_input_index(5))) AND in_ram_input_index(0)
) OR aux80) AND in_ram_input_index(2)) OR aux78) AND in_ram_input_index(1)) OR (
(((((aux9 OR ((NOT(in_ram_input_index(3)) AND aux66) AND NOT(in_ram_input_index(7)
))) AND aux118) OR aux71) AND in_ram_input_index(2)) OR ((((aux9 OR aux24) AND aux121
) OR (aux65 AND NOT(in_ram_input_index(0)))) AND NOT(in_ram_input_index(2)))) 
AND NOT(in_ram_input_index(1))));
  out_data_ram(3) <= ((((((aux3 AND in_ram_input_index(0)) OR (aux20 AND NOT(in_ram_input_index(0)))
) AND in_ram_input_index(2)) OR (aux36 AND aux119)) AND in_ram_input_index(1)) 
OR (((aux28 AND aux120) OR (aux61 AND aux116)) AND NOT(in_ram_input_index(1))));
  out_data_ram(2) <= (((((aux53 OR (aux59 AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)
) OR aux46) AND in_ram_input_index(1)) OR ((((((aux9 OR aux56) AND aux118) OR ((aux35
 OR aux54) AND NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR ((aux30
 OR (aux52 AND NOT(in_ram_input_index(0)))) AND NOT(in_ram_input_index(2)))) AND
 NOT(in_ram_input_index(1))));
  out_data_ram(1) <= (((((aux53 OR (aux48 AND aux117)) AND in_ram_input_index(2)) OR aux46) AND in_ram_input_index(1)
) OR ((((((aux19 OR aux36) AND in_ram_input_index(0)) OR (aux35 AND NOT(in_ram_input_index(0)
))) AND in_ram_input_index(2)) OR ((aux30 OR ((aux22 OR aux20) AND NOT(in_ram_input_index(0)
))) AND NOT(in_ram_input_index(2)))) AND NOT(in_ram_input_index(1))));
  out_data_ram(0) <= (((((aux19 OR aux3) AND NOT(in_ram_input_index(0))) AND in_ram_input_index(2)) 
AND in_ram_input_index(1)) OR (((((aux14 AND in_ram_input_index(0)) OR (aux11 AND 
NOT(in_ram_input_index(0)))) AND in_ram_input_index(2)) OR (aux3 AND aux116)) AND 
NOT(in_ram_input_index(1))));
  aux0 <= (in_ram_input_index(3) AND in_ram_input_index(4));
  aux1 <= (aux0 AND NOT(in_ram_input_index(6)));
  aux3 <= ((aux1 AND in_ram_input_index(7)) AND NOT(in_ram_input_index(5)));
  aux4 <= (in_ram_input_index(3) AND NOT(in_ram_input_index(4)));
  aux6 <= ((aux4 AND in_ram_input_index(6)) AND NOT(in_ram_input_index(7)));
  aux7 <= (NOT(in_ram_input_index(3)) AND NOT(in_ram_input_index(4)));
  aux8 <= (aux7 AND NOT(in_ram_input_index(6)));
  aux9 <= (aux8 AND in_ram_input_index(7));
  aux11 <= ((aux9 OR aux6) AND NOT(in_ram_input_index(5)));
  aux13 <= ((aux0 AND in_ram_input_index(6)) AND NOT(in_ram_input_index(7)));
  aux14 <= (aux13 AND in_ram_input_index(5));
  aux15 <= (NOT(in_ram_input_index(3)) AND in_ram_input_index(4));
  aux16 <= (aux15 AND NOT(in_ram_input_index(6)));
  aux17 <= (aux16 AND NOT(in_ram_input_index(7)));
  aux19 <= ((aux9 OR aux17) AND in_ram_input_index(5));
  aux20 <= (aux13 AND NOT(in_ram_input_index(5)));
  aux22 <= ((aux4 AND NOT(in_ram_input_index(7))) AND in_ram_input_index(5));
  aux23 <= (aux15 AND in_ram_input_index(6));
  aux24 <= (aux23 AND NOT(in_ram_input_index(7)));
  aux25 <= (aux24 AND NOT(in_ram_input_index(5)));
  aux26 <= (aux7 AND in_ram_input_index(6));
  aux27 <= (aux26 AND NOT(in_ram_input_index(7)));
  aux28 <= (aux27 AND in_ram_input_index(5));
  aux30 <= ((aux28 OR aux25) AND in_ram_input_index(0));
  aux31 <= (aux1 AND NOT(in_ram_input_index(7)));
  aux32 <= (aux4 AND NOT(in_ram_input_index(6)));
  aux33 <= (aux32 AND in_ram_input_index(7));
  aux35 <= ((aux33 OR aux31) AND in_ram_input_index(5));
  aux36 <= (aux27 AND NOT(in_ram_input_index(5)));
  aux37 <= (in_ram_input_index(3) AND in_ram_input_index(6));
  aux38 <= (aux37 AND NOT(in_ram_input_index(7)));
  aux41 <= (NOT(in_ram_input_index(3)) AND in_ram_input_index(6));
  aux42 <= (aux41 AND NOT(in_ram_input_index(7)));
  aux46 <= ((((aux42 AND NOT(in_ram_input_index(5))) AND in_ram_input_index(0)) OR ((aux38
 AND NOT(in_ram_input_index(5))) AND NOT(in_ram_input_index(0)))) AND NOT(in_ram_input_index(2)
));
  aux48 <= ((aux41 OR aux32) AND NOT(in_ram_input_index(7)));
  aux49 <= (in_ram_input_index(6) XOR in_ram_input_index(7));
  aux51 <= ((aux0 AND aux49) AND NOT(in_ram_input_index(5)));
  aux52 <= (aux22 OR aux51);
  aux53 <= (aux52 AND in_ram_input_index(0));
  aux54 <= (aux6 AND NOT(in_ram_input_index(5)));
  aux56 <= ((aux37 OR aux16) AND NOT(in_ram_input_index(7)));
  aux59 <= (((aux9 OR aux48) AND in_ram_input_index(5)) OR aux3);
  aux61 <= ((aux32 AND NOT(in_ram_input_index(7))) AND in_ram_input_index(5));
  aux63 <= ((in_ram_input_index(3) AND NOT(in_ram_input_index(6))) AND in_ram_input_index(7)
);
  aux64 <= (aux63 AND NOT(in_ram_input_index(5)));
  aux65 <= (aux61 OR aux64);
  aux66 <= (in_ram_input_index(4) XOR in_ram_input_index(6));
  aux71 <= (((aux33 OR ((in_ram_input_index(3) AND aux66) AND NOT(in_ram_input_index(7))))
 AND in_ram_input_index(5)) AND NOT(in_ram_input_index(0)));
  aux74 <= (aux24 AND in_ram_input_index(5));
  aux76 <= ((aux74 OR aux36) AND in_ram_input_index(0));
  aux78 <= ((aux76 OR ((aux14 OR aux54) AND NOT(in_ram_input_index(0)))) AND NOT(in_ram_input_index(2)
));
  aux80 <= ((aux17 AND in_ram_input_index(5)) AND NOT(in_ram_input_index(0)));
  aux82 <= ((NOT(in_ram_input_index(3)) AND NOT(in_ram_input_index(6))) AND in_ram_input_index(7)
);
  aux84 <= ((aux82 AND NOT(in_ram_input_index(5))) AND in_ram_input_index(0));
  aux85 <= (in_ram_input_index(4) AND NOT(in_ram_input_index(6)));
  aux86 <= (aux85 AND in_ram_input_index(7));
  aux87 <= (in_ram_input_index(3) XOR in_ram_input_index(4));
  aux90 <= (((aux87 AND NOT(in_ram_input_index(6))) AND NOT(in_ram_input_index(7))) AND in_ram_input_index(5)
);
  aux91 <= (aux4 AND aux49);
  aux92 <= (aux31 AND in_ram_input_index(5));
  aux93 <= NOT((in_ram_input_index(4) OR in_ram_input_index(6)));
  aux99 <= ((((aux9 OR ((aux26 OR aux85) AND NOT(in_ram_input_index(7)))) AND in_ram_input_index(5)
) OR aux3) AND in_ram_input_index(0));
  aux101 <= ((aux86 OR aux13) AND NOT(in_ram_input_index(5)));
  aux103 <= ((aux90 OR aux101) AND NOT(in_ram_input_index(0)));
  aux105 <= ((aux33 OR aux24) AND NOT(in_ram_input_index(5)));
  aux106 <= (aux16 AND in_ram_input_index(7));
  aux111 <= ((aux28 OR (((NOT(in_ram_input_index(3)) AND NOT(aux66)) AND NOT(in_ram_input_index(7)
)) AND NOT(in_ram_input_index(5)))) AND NOT(in_ram_input_index(0)));
  aux113 <= ((aux33 OR aux42) AND NOT(in_ram_input_index(5)));
  aux115 <= ((aux7 AND NOT(in_ram_input_index(7))) AND in_ram_input_index(5));
  aux116 <= (NOT(in_ram_input_index(0)) AND NOT(in_ram_input_index(2)));
  aux117 <= (in_ram_input_index(5) AND NOT(in_ram_input_index(0)));
  aux118 <= (in_ram_input_index(5) AND in_ram_input_index(0));
  aux119 <= (in_ram_input_index(0) AND NOT(in_ram_input_index(2)));
  aux120 <= (in_ram_input_index(0) AND in_ram_input_index(2));
  aux121 <= (NOT(in_ram_input_index(5)) AND in_ram_input_index(0));
  aux122 <= (NOT(in_ram_input_index(5)) AND NOT(in_ram_input_index(0)));
  aux123 <= (NOT(in_ram_input_index(7)) AND in_ram_input_index(5));
END RTL;



-- Configuration for sxlib/VITAL library...
library sxlib;
use sxlib.vcomponents.all;

configuration CFG_ram_boom of ram_boom is
  for RTL
  end for;
end CFG_ram_boom;
